// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package store

import (
	"context"
)

const getDailySummary = `-- name: GetDailySummary :one
SELECT
    COUNT(*) AS transaction_count,
    COALESCE(SUM(subtotal), 0) AS gross_sales,
    COALESCE(SUM(discount_total), 0) AS discount_total,
    COALESCE(SUM(grand_total), 0) AS net_sales
FROM sales_transactions
WHERE tenant_id = $1
  AND payment_status = 'paid'
  AND created_at >= CURRENT_DATE
`

type GetDailySummaryRow struct {
	TransactionCount int64       `db:"transaction_count" json:"transaction_count"`
	GrossSales       interface{} `db:"gross_sales" json:"gross_sales"`
	DiscountTotal    interface{} `db:"discount_total" json:"discount_total"`
	NetSales         interface{} `db:"net_sales" json:"net_sales"`
}

func (q *Queries) GetDailySummary(ctx context.Context, tenantID string) (GetDailySummaryRow, error) {
	row := q.db.QueryRow(ctx, getDailySummary, tenantID)
	var i GetDailySummaryRow
	err := row.Scan(
		&i.TransactionCount,
		&i.GrossSales,
		&i.DiscountTotal,
		&i.NetSales,
	)
	return i, err
}

const getTopProducts = `-- name: GetTopProducts :many
SELECT
    v.name AS variant_name,
    p.name AS product_name,
    COALESCE(SUM(si.quantity), 0) AS quantity_sold,
    COALESCE(SUM(si.subtotal), 0) AS revenue
FROM sales_items si
JOIN sales_transactions st ON st.id = si.transaction_id
JOIN variants v ON v.id = si.variant_id
JOIN products p ON p.id = v.product_id
WHERE st.tenant_id = $1
  AND st.payment_status = 'paid'
  AND st.created_at >= CURRENT_DATE
GROUP BY v.id, p.id
ORDER BY quantity_sold DESC
LIMIT 5
`

type GetTopProductsRow struct {
	VariantName  string      `db:"variant_name" json:"variant_name"`
	ProductName  string      `db:"product_name" json:"product_name"`
	QuantitySold interface{} `db:"quantity_sold" json:"quantity_sold"`
	Revenue      interface{} `db:"revenue" json:"revenue"`
}

func (q *Queries) GetTopProducts(ctx context.Context, tenantID string) ([]GetTopProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopProducts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopProductsRow{}
	for rows.Next() {
		var i GetTopProductsRow
		if err := rows.Scan(
			&i.VariantName,
			&i.ProductName,
			&i.QuantitySold,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
