// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, tenant_id, user_id, token_hash, expires_at, device_label, device_fingerprint)
VALUES ($1, $2, $3, $4, NOW() + INTERVAL '7 days', $5, $6)
`

type CreateRefreshTokenParams struct {
	ID                string  `db:"id" json:"id"`
	TenantID          string  `db:"tenant_id" json:"tenant_id"`
	UserID            string  `db:"user_id" json:"user_id"`
	TokenHash         string  `db:"token_hash" json:"token_hash"`
	DeviceLabel       *string `db:"device_label" json:"device_label"`
	DeviceFingerprint *string `db:"device_fingerprint" json:"device_fingerprint"`
}

// Simpan refresh token (sudah di-hash SHA-256) dengan TTL 7 hari.
//
// BUG DITEMUKAN & DIPERBAIKI (3 Sept 2026): daftar kolom sebelumnya menyebut
// `device_label` DUA KALI (bukan device_label + device_fingerprint yang ada
// di skema, migrations/00001). Postgres menolak INSERT dengan kolom
// terduplikasi ("column device_label specified more than once") — setiap
// login/register/refresh gagal total. Ditemukan lewat `make sqlc-vet` +
// pembacaan manual, dikonfirmasi lewat login end-to-end nyata setelah
// diperbaiki, bukan diasumsikan benar dari nama variabel Go.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceLabel,
		arg.DeviceFingerprint,
	)
	return err
}

const createStaffUser = `-- name: CreateStaffUser :one
INSERT INTO users (id, tenant_id, name, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5, $6::varchar)
RETURNING id, name, email, role, is_active, created_at
`

type CreateStaffUserParams struct {
	ID           string `db:"id" json:"id"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
	Name         string `db:"name" json:"name"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	Role         string `db:"role" json:"role"`
}

type CreateStaffUserRow struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Email     string             `db:"email" json:"email"`
	Role      string             `db:"role" json:"role"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Karyawan baru di tenant yang SUDAH ADA (owner menambah kasir/manager).
// Berbeda dari RegisterTenantOwner: tenant_id sudah diketahui, jadi kueri
// ini tetap tunduk pada aturan tenant-scope seperti kueri lain.
func (q *Queries) CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (CreateStaffUserRow, error) {
	row := q.db.QueryRow(ctx, createStaffUser,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i CreateStaffUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, tenant_id, user_id, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type GetRefreshTokenByHashRow struct {
	ID        string             `db:"id" json:"id"`
	TenantID  string             `db:"tenant_id" json:"tenant_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

// Verifikasi refresh token. Kembalikan error bila sudah direvokasi atau expired.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, tenant_id, name, email, password_hash, role, pin_hash, is_active
FROM users
WHERE email = $1 AND tenant_id = $2 AND is_active = TRUE
LIMIT 1
`

type GetUserByEmailParams struct {
	Email    string `db:"email" json:"email"`
	TenantID string `db:"tenant_id" json:"tenant_id"`
}

type GetUserByEmailRow struct {
	ID           string  `db:"id" json:"id"`
	TenantID     string  `db:"tenant_id" json:"tenant_id"`
	Name         string  `db:"name" json:"name"`
	Email        string  `db:"email" json:"email"`
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	Role         string  `db:"role" json:"role"`
	PinHash      *string `db:"pin_hash" json:"pin_hash"`
	IsActive     bool    `db:"is_active" json:"is_active"`
}

// Kueri autentikasi untuk jalur /auth/*.
// Dipakai hanya oleh internal/httpapi/auth.go — bukan seeder.
// Lookup user berdasarkan email untuk login. Hanya user aktif.
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.PinHash,
		&i.IsActive,
	)
	return i, err
}

const getUserByEmailGlobal = `-- name: GetUserByEmailGlobal :one
SELECT id, tenant_id, name, email, password_hash, role, pin_hash, is_active
FROM users
WHERE email = $1 AND is_active = TRUE
LIMIT 1
`

type GetUserByEmailGlobalRow struct {
	ID           string  `db:"id" json:"id"`
	TenantID     string  `db:"tenant_id" json:"tenant_id"`
	Name         string  `db:"name" json:"name"`
	Email        string  `db:"email" json:"email"`
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	Role         string  `db:"role" json:"role"`
	PinHash      *string `db:"pin_hash" json:"pin_hash"`
	IsActive     bool    `db:"is_active" json:"is_active"`
}

// sqlc-vet-disable: wajib-tenant-scope
// Lookup user untuk login TANPA tenant_id. Dikecualikan dari aturan
// wajib-tenant-scope dengan alasan yang sama seperti RegisterTenantOwner:
// login adalah operasi SEBELUM tenant diketahui — memaksa pemanggil menyebut
// tenant_id berarti pemilik warung harus menghafal ULID 26 karakter, dan
// kehilangan string itu mengunci dia keluar dari datanya sendiri.
//
// Aman karena `idx_users_email` UNIQUE global (00001_foundation.sql:45): satu
// email hanya pernah menunjuk satu user, jadi tenant_id hasilnya deterministik
// dan tidak bisa ditebak-tebak oleh pemanggil. Setelah baris ini didapat,
// seluruh kueri berikutnya tetap memfilter tenant_id dari hasil di sini —
// bukan dari input klien, yang justru lebih ketat daripada sebelumnya.
func (q *Queries) GetUserByEmailGlobal(ctx context.Context, email string) (GetUserByEmailGlobalRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailGlobal, email)
	var i GetUserByEmailGlobalRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.PinHash,
		&i.IsActive,
	)
	return i, err
}

const getUserForPinChange = `-- name: GetUserForPinChange :one
SELECT id, role, password_hash, is_active
FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetUserForPinChangeParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type GetUserForPinChangeRow struct {
	ID           string `db:"id" json:"id"`
	Role         string `db:"role" json:"role"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	IsActive     bool   `db:"is_active" json:"is_active"`
}

// Verifikasi password SEBELUM mengubah PIN sendiri. Password diminta lagi
// meski sesi sudah hidup, dan itu disengaja: PIN inilah yang kelak dipakai
// menyetujui refund TANPA login. Siapa pun yang menemukan ponsel manager
// dalam keadaan terbuka tidak boleh bisa menanam PIN miliknya sendiri.
func (q *Queries) GetUserForPinChange(ctx context.Context, arg GetUserForPinChangeParams) (GetUserForPinChangeRow, error) {
	row := q.db.QueryRow(ctx, getUserForPinChange, arg.TenantID, arg.ID)
	var i GetUserForPinChangeRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getUserWithTenant = `-- name: GetUserWithTenant :one
SELECT
    u.id         AS user_id,
    u.tenant_id,
    u.name       AS user_name,
    u.email,
    u.role,
    t.name       AS tenant_name,
    t.plan_tier,
    t.plan_status
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE u.id = $1 AND u.is_active = TRUE
`

type GetUserWithTenantRow struct {
	UserID     string `db:"user_id" json:"user_id"`
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	UserName   string `db:"user_name" json:"user_name"`
	Email      string `db:"email" json:"email"`
	Role       string `db:"role" json:"role"`
	TenantName string `db:"tenant_name" json:"tenant_name"`
	PlanTier   string `db:"plan_tier" json:"plan_tier"`
	PlanStatus string `db:"plan_status" json:"plan_status"`
}

// Setelah login sukses, ambil info tenant untuk disertakan dalam JWT claims.
func (q *Queries) GetUserWithTenant(ctx context.Context, id string) (GetUserWithTenantRow, error) {
	row := q.db.QueryRow(ctx, getUserWithTenant, id)
	var i GetUserWithTenantRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.UserName,
		&i.Email,
		&i.Role,
		&i.TenantName,
		&i.PlanTier,
		&i.PlanStatus,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, name, email, role, is_active, (pin_hash IS NOT NULL)::boolean AS punya_pin
FROM users
WHERE tenant_id = $1
ORDER BY is_active DESC, role, name
`

type ListStaffRow struct {
	ID       string `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	Email    string `db:"email" json:"email"`
	Role     string `db:"role" json:"role"`
	IsActive bool   `db:"is_active" json:"is_active"`
	PunyaPin bool   `db:"punya_pin" json:"punya_pin"`
}

// Daftar karyawan untuk layar Pengaturan. TIDAK menyertakan password_hash
// maupun pin_hash — keduanya tidak pernah keluar dari server.
func (q *Queries) ListStaff(ctx context.Context, tenantID string) ([]ListStaffRow, error) {
	rows, err := q.db.Query(ctx, listStaff, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaffRow{}
	for rows.Next() {
		var i ListStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.IsActive,
			&i.PunyaPin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerTenantOwner = `-- name: RegisterTenantOwner :one
INSERT INTO users (id, tenant_id, name, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5, 'owner')
RETURNING id
`

type RegisterTenantOwnerParams struct {
	ID           string `db:"id" json:"id"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
	Name         string `db:"name" json:"name"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

// sqlc-vet-disable: wajib-tenant-scope
// Buat tenant baru + user owner sekaligus dalam satu transaksi (dipanggil
// dari handler POST /auth/register). Query ini hanya untuk registrasi awal —
// tenant_id belum ada, jadi dikecualikan dari aturan wajib-tenant-scope.
func (q *Queries) RegisterTenantOwner(ctx context.Context, arg RegisterTenantOwnerParams) (string, error) {
	row := q.db.QueryRow(ctx, registerTenantOwner,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAllUserTokensParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	UserID   string `db:"user_id" json:"user_id"`
}

// Revoke semua token aktif milik user (logout-all / compromised account).
func (q *Queries) RevokeAllUserTokens(ctx context.Context, arg RevokeAllUserTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, arg.TenantID, arg.UserID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE tenant_id = $1 AND token_hash = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	TokenHash string `db:"token_hash" json:"token_hash"`
}

// Revoke satu token spesifik (logout atau rotate). tenant_id sebagai
// parameter WAJIB (SECURITY.md §2B "Aturan Emas SQL") meski token_hash
// sendiri unik secara global — pertahanan berlapis, bukan cuma soal
// tereksploitasi atau tidak.
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.TenantID, arg.TokenHash)
	return err
}

const setStaffActive = `-- name: SetStaffActive :execrows
UPDATE users
SET is_active = $3::boolean
WHERE tenant_id = $1 AND id = $2
`

type SetStaffActiveParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

// Karyawan yang berhenti DINONAKTIFKAN, tidak dihapus: transaksi, refund,
// dan ledger stok yang ia catat tetap merujuk namanya. Owner tidak bisa
// menonaktifkan dirinya sendiri (dicegah di handler) — tenant tanpa satu
// pun akun aktif tidak bisa dibuka siapa pun lagi.
func (q *Queries) SetStaffActive(ctx context.Context, arg SetStaffActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStaffActive, arg.TenantID, arg.ID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPin = `-- name: SetUserPin :execrows
UPDATE users
SET pin_hash = $3
WHERE tenant_id = $1 AND id = $2
`

type SetUserPinParams struct {
	TenantID string  `db:"tenant_id" json:"tenant_id"`
	ID       string  `db:"id" json:"id"`
	PinHash  *string `db:"pin_hash" json:"pin_hash"`
}

// Hanya untuk DIRI SENDIRI (pemanggil mengirim id dari klaim JWT-nya).
// NULL = PIN dihapus; manager itu tidak bisa menyetujui apa pun lagi.
func (q *Queries) SetUserPin(ctx context.Context, arg SetUserPinParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserPin, arg.TenantID, arg.ID, arg.PinHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
