// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, tenant_id, user_id, token_hash, expires_at, device_label, device_label)
VALUES ($1, $2, $3, $4, NOW() + INTERVAL '7 days', $5, $6)
`

type CreateRefreshTokenParams struct {
	ID            string  `db:"id" json:"id"`
	TenantID      string  `db:"tenant_id" json:"tenant_id"`
	UserID        string  `db:"user_id" json:"user_id"`
	TokenHash     string  `db:"token_hash" json:"token_hash"`
	DeviceLabel   *string `db:"device_label" json:"device_label"`
	DeviceLabel_2 *string `db:"device_label_2" json:"device_label_2"`
}

// Simpan refresh token (sudah di-hash SHA-256) dengan TTL 7 hari.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceLabel,
		arg.DeviceLabel_2,
	)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, tenant_id, user_id, expires_at, revoked_at
FROM refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type GetRefreshTokenByHashRow struct {
	ID        string             `db:"id" json:"id"`
	TenantID  string             `db:"tenant_id" json:"tenant_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

// Verifikasi refresh token. Kembalikan error bila sudah direvokasi atau expired.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, tenant_id, name, email, password_hash, role, pin_hash, is_active
FROM users
WHERE email = $1 AND tenant_id = $2 AND is_active = TRUE
LIMIT 1
`

type GetUserByEmailParams struct {
	Email    string `db:"email" json:"email"`
	TenantID string `db:"tenant_id" json:"tenant_id"`
}

type GetUserByEmailRow struct {
	ID           string  `db:"id" json:"id"`
	TenantID     string  `db:"tenant_id" json:"tenant_id"`
	Name         string  `db:"name" json:"name"`
	Email        string  `db:"email" json:"email"`
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	Role         string  `db:"role" json:"role"`
	PinHash      *string `db:"pin_hash" json:"pin_hash"`
	IsActive     bool    `db:"is_active" json:"is_active"`
}

// Kueri autentikasi untuk jalur /auth/*.
// Dipakai hanya oleh internal/httpapi/auth.go — bukan seeder.
// Lookup user berdasarkan email untuk login. Hanya user aktif.
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.PinHash,
		&i.IsActive,
	)
	return i, err
}

const getUserWithTenant = `-- name: GetUserWithTenant :one
SELECT
    u.id         AS user_id,
    u.tenant_id,
    u.name       AS user_name,
    u.email,
    u.role,
    t.name       AS tenant_name,
    t.plan_tier,
    t.plan_status
FROM users u
JOIN tenants t ON t.id = u.tenant_id
WHERE u.id = $1 AND u.is_active = TRUE
`

type GetUserWithTenantRow struct {
	UserID     string `db:"user_id" json:"user_id"`
	TenantID   string `db:"tenant_id" json:"tenant_id"`
	UserName   string `db:"user_name" json:"user_name"`
	Email      string `db:"email" json:"email"`
	Role       string `db:"role" json:"role"`
	TenantName string `db:"tenant_name" json:"tenant_name"`
	PlanTier   string `db:"plan_tier" json:"plan_tier"`
	PlanStatus string `db:"plan_status" json:"plan_status"`
}

// Setelah login sukses, ambil info tenant untuk disertakan dalam JWT claims.
func (q *Queries) GetUserWithTenant(ctx context.Context, id string) (GetUserWithTenantRow, error) {
	row := q.db.QueryRow(ctx, getUserWithTenant, id)
	var i GetUserWithTenantRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.UserName,
		&i.Email,
		&i.Role,
		&i.TenantName,
		&i.PlanTier,
		&i.PlanStatus,
	)
	return i, err
}

const registerTenantOwner = `-- name: RegisterTenantOwner :one
INSERT INTO users (id, tenant_id, name, email, password_hash, role)
VALUES ($1, $2, $3, $4, $5, 'owner')
RETURNING id
`

type RegisterTenantOwnerParams struct {
	ID           string `db:"id" json:"id"`
	TenantID     string `db:"tenant_id" json:"tenant_id"`
	Name         string `db:"name" json:"name"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

// sqlc-vet-disable: wajib-tenant-scope
// Buat tenant baru + user owner sekaligus dalam satu transaksi (dipanggil
// dari handler POST /auth/register). Query ini hanya untuk registrasi awal —
// tenant_id belum ada, jadi dikecualikan dari aturan wajib-tenant-scope.
func (q *Queries) RegisterTenantOwner(ctx context.Context, arg RegisterTenantOwnerParams) (string, error) {
	row := q.db.QueryRow(ctx, registerTenantOwner,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Revoke semua token aktif milik user (logout-all / compromised account).
func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE token_hash = $1 AND revoked_at IS NULL
`

// Revoke satu token spesifik (logout atau rotate).
func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
