// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const convertUom = `-- name: ConvertUom :one
SELECT factor
FROM uom_conversions
WHERE tenant_id = $1 AND variant_id = $2 AND from_uom = $3 AND to_uom = $4
`

type ConvertUomParams struct {
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	VariantID string `db:"variant_id" json:"variant_id"`
	FromUom   string `db:"from_uom" json:"from_uom"`
	ToUom     string `db:"to_uom" json:"to_uom"`
}

func (q *Queries) ConvertUom(ctx context.Context, arg ConvertUomParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, convertUom,
		arg.TenantID,
		arg.VariantID,
		arg.FromUom,
		arg.ToUom,
	)
	var factor decimal.Decimal
	err := row.Scan(&factor)
	return factor, err
}

const getBomComponents = `-- name: GetBomComponents :many
SELECT b.component_variant_id, b.quantity, b.uom, b.waste_pct
FROM bom_components b
WHERE b.tenant_id = $1 AND b.parent_variant_id = $2
`

type GetBomComponentsParams struct {
	TenantID        string `db:"tenant_id" json:"tenant_id"`
	ParentVariantID string `db:"parent_variant_id" json:"parent_variant_id"`
}

type GetBomComponentsRow struct {
	ComponentVariantID string          `db:"component_variant_id" json:"component_variant_id"`
	Quantity           decimal.Decimal `db:"quantity" json:"quantity"`
	Uom                string          `db:"uom" json:"uom"`
	WastePct           decimal.Decimal `db:"waste_pct" json:"waste_pct"`
}

func (q *Queries) GetBomComponents(ctx context.Context, arg GetBomComponentsParams) ([]GetBomComponentsRow, error) {
	rows, err := q.db.Query(ctx, getBomComponents, arg.TenantID, arg.ParentVariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBomComponentsRow{}
	for rows.Next() {
		var i GetBomComponentsRow
		if err := rows.Scan(
			&i.ComponentVariantID,
			&i.Quantity,
			&i.Uom,
			&i.WastePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantForCheckout = `-- name: GetVariantForCheckout :one
SELECT
    v.id, v.item_type, v.uom, v.uom_precision, COALESCE(o.price, v.price) AS price,
    v.cost_price, v.stock_quantity, COALESCE(sc.to_uom, '')::VARCHAR AS stock_uom, COALESCE(sc.factor, 0)::DECIMAL AS stock_factor
FROM variants v
LEFT JOIN outlet_price_overrides o ON o.variant_id = v.id AND o.tenant_id = v.tenant_id AND o.outlet_id = $3
LEFT JOIN LATERAL (
    -- Satuan STOK bila berbeda dari satuan jual (ADR-0012): bibit dijual per
    -- ml tetapi stoknya dihitung dalam gram. Konversi yang berlaku adalah
    -- yang BERANGKAT dari satuan jual varian.
    SELECT c.to_uom, c.factor
    FROM uom_conversions c
    WHERE c.tenant_id = v.tenant_id AND c.variant_id = v.id AND c.from_uom = v.uom
    ORDER BY c.created_at
    LIMIT 1
) sc ON TRUE
WHERE v.tenant_id = $1 AND v.id = $2 AND v.is_active
`

type GetVariantForCheckoutParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
	OutletID string `db:"outlet_id" json:"outlet_id"`
}

type GetVariantForCheckoutRow struct {
	ID            string          `db:"id" json:"id"`
	ItemType      string          `db:"item_type" json:"item_type"`
	Uom           string          `db:"uom" json:"uom"`
	UomPrecision  int16           `db:"uom_precision" json:"uom_precision"`
	Price         decimal.Decimal `db:"price" json:"price"`
	CostPrice     decimal.Decimal `db:"cost_price" json:"cost_price"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
	StockUom      string          `db:"stock_uom" json:"stock_uom"`
	StockFactor   decimal.Decimal `db:"stock_factor" json:"stock_factor"`
}

func (q *Queries) GetVariantForCheckout(ctx context.Context, arg GetVariantForCheckoutParams) (GetVariantForCheckoutRow, error) {
	row := q.db.QueryRow(ctx, getVariantForCheckout, arg.TenantID, arg.ID, arg.OutletID)
	var i GetVariantForCheckoutRow
	err := row.Scan(
		&i.ID,
		&i.ItemType,
		&i.Uom,
		&i.UomPrecision,
		&i.Price,
		&i.CostPrice,
		&i.StockQuantity,
		&i.StockUom,
		&i.StockFactor,
	)
	return i, err
}

const listCatalogForSync = `-- name: ListCatalogForSync :many
SELECT
    v.id, v.product_id, p.category_id, p.name AS product_name, v.name AS variant_name,
    v.sku, v.barcode, v.item_type, v.uom, v.uom_precision,
    COALESCE(o.price, v.price) AS price, v.stock_quantity, v.min_stock_alert,
    v.is_active, GREATEST(v.created_at, p.created_at) AS updated_at,
    COALESCE(sc.to_uom, '')::VARCHAR AS stock_uom, COALESCE(sc.factor, 0)::DECIMAL AS stock_factor
FROM variants v
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
LEFT JOIN outlet_price_overrides o ON o.variant_id = v.id AND o.tenant_id = v.tenant_id AND o.outlet_id = $2
LEFT JOIN LATERAL (
    -- Satuan STOK bila berbeda dari satuan jual (ADR-0012): bibit dijual per
    -- ml tetapi stoknya dihitung dalam gram. Konversi yang berlaku adalah
    -- yang BERANGKAT dari satuan jual varian.
    SELECT c.to_uom, c.factor
    FROM uom_conversions c
    WHERE c.tenant_id = v.tenant_id AND c.variant_id = v.id AND c.from_uom = v.uom
    ORDER BY c.created_at
    LIMIT 1
) sc ON TRUE
WHERE v.tenant_id = $1
ORDER BY v.id
LIMIT $3
`

type ListCatalogForSyncParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	OutletID string `db:"outlet_id" json:"outlet_id"`
	Limit    int32  `db:"limit" json:"limit"`
}

type ListCatalogForSyncRow struct {
	ID            string          `db:"id" json:"id"`
	ProductID     string          `db:"product_id" json:"product_id"`
	CategoryID    *string         `db:"category_id" json:"category_id"`
	ProductName   string          `db:"product_name" json:"product_name"`
	VariantName   string          `db:"variant_name" json:"variant_name"`
	Sku           *string         `db:"sku" json:"sku"`
	Barcode       *string         `db:"barcode" json:"barcode"`
	ItemType      string          `db:"item_type" json:"item_type"`
	Uom           string          `db:"uom" json:"uom"`
	UomPrecision  int16           `db:"uom_precision" json:"uom_precision"`
	Price         decimal.Decimal `db:"price" json:"price"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
	MinStockAlert decimal.Decimal `db:"min_stock_alert" json:"min_stock_alert"`
	IsActive      bool            `db:"is_active" json:"is_active"`
	UpdatedAt     interface{}     `db:"updated_at" json:"updated_at"`
	StockUom      string          `db:"stock_uom" json:"stock_uom"`
	StockFactor   decimal.Decimal `db:"stock_factor" json:"stock_factor"`
}

func (q *Queries) ListCatalogForSync(ctx context.Context, arg ListCatalogForSyncParams) ([]ListCatalogForSyncRow, error) {
	rows, err := q.db.Query(ctx, listCatalogForSync, arg.TenantID, arg.OutletID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogForSyncRow{}
	for rows.Next() {
		var i ListCatalogForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.CategoryID,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.Barcode,
			&i.ItemType,
			&i.Uom,
			&i.UomPrecision,
			&i.Price,
			&i.StockQuantity,
			&i.MinStockAlert,
			&i.IsActive,
			&i.UpdatedAt,
			&i.StockUom,
			&i.StockFactor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, tenant_id, category_id, name, description, image_url, is_active, created_at
FROM products
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	Limit    int32  `db:"limit" json:"limit"`
	Offset   int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupVariantByBarcode = `-- name: LookupVariantByBarcode :one
SELECT
    v.id, v.product_id, p.name AS product_name, v.name AS variant_name,
    v.sku, v.barcode, v.item_type, v.uom, v.uom_precision,
    COALESCE(o.price, v.price) AS price, v.stock_quantity, v.min_stock_alert
FROM variants v
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
LEFT JOIN outlet_price_overrides o ON o.variant_id = v.id AND o.tenant_id = v.tenant_id AND o.outlet_id = $3
WHERE v.tenant_id = $1 AND v.barcode = $2 AND v.is_active
LIMIT 1
`

type LookupVariantByBarcodeParams struct {
	TenantID string  `db:"tenant_id" json:"tenant_id"`
	Barcode  *string `db:"barcode" json:"barcode"`
	OutletID string  `db:"outlet_id" json:"outlet_id"`
}

type LookupVariantByBarcodeRow struct {
	ID            string          `db:"id" json:"id"`
	ProductID     string          `db:"product_id" json:"product_id"`
	ProductName   string          `db:"product_name" json:"product_name"`
	VariantName   string          `db:"variant_name" json:"variant_name"`
	Sku           *string         `db:"sku" json:"sku"`
	Barcode       *string         `db:"barcode" json:"barcode"`
	ItemType      string          `db:"item_type" json:"item_type"`
	Uom           string          `db:"uom" json:"uom"`
	UomPrecision  int16           `db:"uom_precision" json:"uom_precision"`
	Price         decimal.Decimal `db:"price" json:"price"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
	MinStockAlert decimal.Decimal `db:"min_stock_alert" json:"min_stock_alert"`
}

func (q *Queries) LookupVariantByBarcode(ctx context.Context, arg LookupVariantByBarcodeParams) (LookupVariantByBarcodeRow, error) {
	row := q.db.QueryRow(ctx, lookupVariantByBarcode, arg.TenantID, arg.Barcode, arg.OutletID)
	var i LookupVariantByBarcodeRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.Barcode,
		&i.ItemType,
		&i.Uom,
		&i.UomPrecision,
		&i.Price,
		&i.StockQuantity,
		&i.MinStockAlert,
	)
	return i, err
}

const searchVariants = `-- name: SearchVariants :many
SELECT
    v.id, p.name AS product_name, v.name AS variant_name, v.item_type,
    v.uom, v.uom_precision, COALESCE(o.price, v.price) AS price, v.stock_quantity
FROM variants v
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
LEFT JOIN outlet_price_overrides o ON o.variant_id = v.id AND o.tenant_id = v.tenant_id AND o.outlet_id = $2
WHERE v.tenant_id = $1 AND v.is_active AND (p.name ILIKE '%' || $3 || '%' OR v.sku ILIKE '%' || $3 || '%')
ORDER BY p.name, v.name
LIMIT $4
`

type SearchVariantsParams struct {
	TenantID string  `db:"tenant_id" json:"tenant_id"`
	OutletID string  `db:"outlet_id" json:"outlet_id"`
	Column3  *string `db:"column_3" json:"column_3"`
	Limit    int32   `db:"limit" json:"limit"`
}

type SearchVariantsRow struct {
	ID            string          `db:"id" json:"id"`
	ProductName   string          `db:"product_name" json:"product_name"`
	VariantName   string          `db:"variant_name" json:"variant_name"`
	ItemType      string          `db:"item_type" json:"item_type"`
	Uom           string          `db:"uom" json:"uom"`
	UomPrecision  int16           `db:"uom_precision" json:"uom_precision"`
	Price         decimal.Decimal `db:"price" json:"price"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
}

func (q *Queries) SearchVariants(ctx context.Context, arg SearchVariantsParams) ([]SearchVariantsRow, error) {
	rows, err := q.db.Query(ctx, searchVariants,
		arg.TenantID,
		arg.OutletID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchVariantsRow{}
	for rows.Next() {
		var i SearchVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.VariantName,
			&i.ItemType,
			&i.Uom,
			&i.UomPrecision,
			&i.Price,
			&i.StockQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    is_active = COALESCE($5, is_active)
WHERE tenant_id = $1 AND id = $2
`

type UpdateProductParams struct {
	TenantID    string  `db:"tenant_id" json:"tenant_id"`
	ID          string  `db:"id" json:"id"`
	Name        *string `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	IsActive    *bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	return err
}

const updateVariant = `-- name: UpdateVariant :exec
UPDATE variants
SET
    name = COALESCE($3, name),
    price = COALESCE($4, price),
    sku = COALESCE($5, sku),
    barcode = COALESCE($6, barcode),
    is_active = COALESCE($7, is_active)
WHERE tenant_id = $1 AND id = $2
`

type UpdateVariantParams struct {
	TenantID string              `db:"tenant_id" json:"tenant_id"`
	ID       string              `db:"id" json:"id"`
	Name     *string             `db:"name" json:"name"`
	Price    decimal.NullDecimal `db:"price" json:"price"`
	Sku      *string             `db:"sku" json:"sku"`
	Barcode  *string             `db:"barcode" json:"barcode"`
	IsActive *bool               `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) error {
	_, err := q.db.Exec(ctx, updateVariant,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.Sku,
		arg.Barcode,
		arg.IsActive,
	)
	return err
}
