// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createSaleIdempotent = `-- name: CreateSaleIdempotent :one

INSERT INTO sales_transactions (
    id, tenant_id, outlet_id, cashier_id, shift_id, customer_id,
    receipt_number, subtotal, discount_total, tax_total, grand_total,
    payment_status,
    offline_created_at, offline_created_at_adj, device_clock_offset_s, device_id,
    synced_at, is_late_arrival, is_sandbox
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12,
    $13, $14, $15, $16,
    now(), $17, $18
)
ON CONFLICT (id) DO NOTHING
RETURNING id, receipt_number, grand_total, created_at
`

type CreateSaleIdempotentParams struct {
	ID                  string             `db:"id" json:"id"`
	TenantID            string             `db:"tenant_id" json:"tenant_id"`
	OutletID            string             `db:"outlet_id" json:"outlet_id"`
	CashierID           string             `db:"cashier_id" json:"cashier_id"`
	ShiftID             *string            `db:"shift_id" json:"shift_id"`
	CustomerID          *string            `db:"customer_id" json:"customer_id"`
	ReceiptNumber       string             `db:"receipt_number" json:"receipt_number"`
	Subtotal            decimal.Decimal    `db:"subtotal" json:"subtotal"`
	DiscountTotal       decimal.Decimal    `db:"discount_total" json:"discount_total"`
	TaxTotal            decimal.Decimal    `db:"tax_total" json:"tax_total"`
	GrandTotal          decimal.Decimal    `db:"grand_total" json:"grand_total"`
	PaymentStatus       string             `db:"payment_status" json:"payment_status"`
	OfflineCreatedAt    pgtype.Timestamptz `db:"offline_created_at" json:"offline_created_at"`
	OfflineCreatedAtAdj pgtype.Timestamptz `db:"offline_created_at_adj" json:"offline_created_at_adj"`
	DeviceClockOffsetS  *int32             `db:"device_clock_offset_s" json:"device_clock_offset_s"`
	DeviceID            *string            `db:"device_id" json:"device_id"`
	IsLateArrival       bool               `db:"is_late_arrival" json:"is_late_arrival"`
	IsSandbox           bool               `db:"is_sandbox" json:"is_sandbox"`
}

type CreateSaleIdempotentRow struct {
	ID            string             `db:"id" json:"id"`
	ReceiptNumber string             `db:"receipt_number" json:"receipt_number"`
	GrandTotal    decimal.Decimal    `db:"grand_total" json:"grand_total"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// ═══════════════════════════════════════════════════════════════════════
//
//	JALUR UANG — anggaran total p99 < 5ms (PRD §4)
//
//	Seluruh kueri di berkas ini berjalan dalam SATU transaksi SQL:
//
//	  BEGIN
//	    CreateSaleIdempotent      → 0 baris berarti duplikat, bukan error
//	    InsertSalesItems          (copyfrom)
//	    InsertPayment             (per metode bayar; FR-22 split payment)
//	    DecrementStock*           → mengunci baris variants
//	    InsertStockEvents         (copyfrom)
//	    InsertOutboxEvent         → mengatasi masalah dual-write
//	  COMMIT
//
//	Urutan penting: stok dikurangi SETELAH transaksi tersimpan, agar kegagalan
//	stok tidak meninggalkan transaksi yatim.
//
// ═══════════════════════════════════════════════════════════════════════
// HOT PATH. ULID dibuat KLIEN — inilah kunci idempotensi.
//
// ON CONFLICT DO NOTHING + RETURNING: bila 0 baris kembali, transaksi ini SUDAH
// pernah masuk. Itu bukan kegagalan melainkan kelas ACCEPTED
// (ERROR-CATALOG §4): klien menandainya 'synced' dan melanjutkan.
//
// Tanpa perilaku ini, transaksi yang sudah aman di server akan tersangkut
// selamanya di antrean lokal sampai IndexedDB penuh — satu-satunya jalur
// menuju "kasir tidak bisa berjualan".
func (q *Queries) CreateSaleIdempotent(ctx context.Context, arg CreateSaleIdempotentParams) (CreateSaleIdempotentRow, error) {
	row := q.db.QueryRow(ctx, createSaleIdempotent,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.CashierID,
		arg.ShiftID,
		arg.CustomerID,
		arg.ReceiptNumber,
		arg.Subtotal,
		arg.DiscountTotal,
		arg.TaxTotal,
		arg.GrandTotal,
		arg.PaymentStatus,
		arg.OfflineCreatedAt,
		arg.OfflineCreatedAtAdj,
		arg.DeviceClockOffsetS,
		arg.DeviceID,
		arg.IsLateArrival,
		arg.IsSandbox,
	)
	var i CreateSaleIdempotentRow
	err := row.Scan(
		&i.ID,
		&i.ReceiptNumber,
		&i.GrandTotal,
		&i.CreatedAt,
	)
	return i, err
}

const decrementStockAllowNegative = `-- name: DecrementStockAllowNegative :one
UPDATE variants
SET stock_quantity = stock_quantity - $3
WHERE tenant_id = $1
  AND id        = $2
  AND item_type IN ('stock', 'composite')
RETURNING stock_quantity
`

type DecrementStockAllowNegativeParams struct {
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	ID            string          `db:"id" json:"id"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
}

// SINKRONISASI OFFLINE. Stok BOLEH menjadi negatif.
//
// Barang sudah keluar secara fisik, pelanggan sudah pergi, uang sudah diterima.
// Menolak sync berarti menghapus penjualan nyata dari catatan.
// Stok minus adalah INFORMASI ("lakukan opname di sini"), bukan kerusakan data.
// (OFFLINE-SYNC-SPEC §2 prinsip 3, §3A)
func (q *Queries) DecrementStockAllowNegative(ctx context.Context, arg DecrementStockAllowNegativeParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, decrementStockAllowNegative, arg.TenantID, arg.ID, arg.StockQuantity)
	var stock_quantity decimal.Decimal
	err := row.Scan(&stock_quantity)
	return stock_quantity, err
}

const decrementStockStrict = `-- name: DecrementStockStrict :one

UPDATE variants
SET stock_quantity = stock_quantity - $3
WHERE tenant_id = $1
  AND id        = $2
  AND is_active
  AND item_type IN ('stock', 'composite')
  AND stock_quantity >= $3
RETURNING stock_quantity
`

type DecrementStockStrictParams struct {
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	ID            string          `db:"id" json:"id"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
}

// ── PEMOTONGAN STOK ────────────────────────────────────────────────────
// Dua kueri berbeda dan itu DISENGAJA. Perbedaannya adalah keputusan produk,
// bukan detail teknis. (ERROR-CATALOG §5)
// HOT PATH — checkout ONLINE. Menolak bila stok tidak cukup.
//
// UPDATE tunggal ini sudah atomik dan mengambil kunci baris; tidak perlu
// SELECT ... FOR UPDATE terpisah. Inilah alasan mutex Redis TIDAK dipakai
// di sini — menambahkan Redis ke jalur ini berarti menambah titik kegagalan
// pada bagian sistem yang paling tidak boleh gagal. (REDIS-STRATEGY §5)
//
// 0 baris kembali → INSUFFICIENT_STOCK (kelas PERMANENT).
func (q *Queries) DecrementStockStrict(ctx context.Context, arg DecrementStockStrictParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, decrementStockStrict, arg.TenantID, arg.ID, arg.StockQuantity)
	var stock_quantity decimal.Decimal
	err := row.Scan(&stock_quantity)
	return stock_quantity, err
}

const getApproverForPin = `-- name: GetApproverForPin :one
SELECT id, role, pin_hash, is_active
FROM users
WHERE tenant_id = $1 AND id = $2
`

type GetApproverForPinParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type GetApproverForPinRow struct {
	ID       string  `db:"id" json:"id"`
	Role     string  `db:"role" json:"role"`
	PinHash  *string `db:"pin_hash" json:"pin_hash"`
	IsActive bool    `db:"is_active" json:"is_active"`
}

// Manager/owner yang MENYETUJUI refund kasir (RBAC-MODEL §"Void transaksi":
// kasir wajib PIN manager). Bukan user yang sedang login — approved_by
// HARUS identitas manager, bukan kasir menyetujui diri sendiri.
func (q *Queries) GetApproverForPin(ctx context.Context, arg GetApproverForPinParams) (GetApproverForPinRow, error) {
	row := q.db.QueryRow(ctx, getApproverForPin, arg.TenantID, arg.ID)
	var i GetApproverForPinRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.PinHash,
		&i.IsActive,
	)
	return i, err
}

const getSaleByID = `-- name: GetSaleByID :one
SELECT id, receipt_number, grand_total, subtotal, discount_total, tax_total, created_at
FROM sales_transactions
WHERE tenant_id = $1
  AND id        = $2
`

type GetSaleByIDParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type GetSaleByIDRow struct {
	ID            string             `db:"id" json:"id"`
	ReceiptNumber string             `db:"receipt_number" json:"receipt_number"`
	GrandTotal    decimal.Decimal    `db:"grand_total" json:"grand_total"`
	Subtotal      decimal.Decimal    `db:"subtotal" json:"subtotal"`
	DiscountTotal decimal.Decimal    `db:"discount_total" json:"discount_total"`
	TaxTotal      decimal.Decimal    `db:"tax_total" json:"tax_total"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Dipakai saat CreateSaleIdempotent mengembalikan 0 baris (idempotency hit,
// ERROR-CATALOG §B DUPLICATE_TRANSACTION) — klien menerima record yang SUDAH
// ada, bukan error, persis seperti openapi.yaml POST /sales respons 200.
func (q *Queries) GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (GetSaleByIDRow, error) {
	row := q.db.QueryRow(ctx, getSaleByID, arg.TenantID, arg.ID)
	var i GetSaleByIDRow
	err := row.Scan(
		&i.ID,
		&i.ReceiptNumber,
		&i.GrandTotal,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.CreatedAt,
	)
	return i, err
}

const getSaleForRefund = `-- name: GetSaleForRefund :one
SELECT id, outlet_id, cashier_id, grand_total, payment_status
FROM sales_transactions
WHERE tenant_id = $1 AND id = $2
`

type GetSaleForRefundParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type GetSaleForRefundRow struct {
	ID            string          `db:"id" json:"id"`
	OutletID      string          `db:"outlet_id" json:"outlet_id"`
	CashierID     string          `db:"cashier_id" json:"cashier_id"`
	GrandTotal    decimal.Decimal `db:"grand_total" json:"grand_total"`
	PaymentStatus string          `db:"payment_status" json:"payment_status"`
}

// Dipakai PostRefund untuk menegakkan REFUND_EXCEEDS_TOTAL (ERROR-CATALOG §B)
// — tanpa ini, refund_total tidak pernah dibandingkan dengan grand_total asli.
func (q *Queries) GetSaleForRefund(ctx context.Context, arg GetSaleForRefundParams) (GetSaleForRefundRow, error) {
	row := q.db.QueryRow(ctx, getSaleForRefund, arg.TenantID, arg.ID)
	var i GetSaleForRefundRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.CashierID,
		&i.GrandTotal,
		&i.PaymentStatus,
	)
	return i, err
}

const getSalesItemForRefund = `-- name: GetSalesItemForRefund :one
SELECT variant_id, uom
FROM sales_items
WHERE tenant_id = $1 AND transaction_id = $2 AND id = $3
`

type GetSalesItemForRefundParams struct {
	TenantID      string `db:"tenant_id" json:"tenant_id"`
	TransactionID string `db:"transaction_id" json:"transaction_id"`
	ID            string `db:"id" json:"id"`
}

type GetSalesItemForRefundRow struct {
	VariantID string `db:"variant_id" json:"variant_id"`
	Uom       string `db:"uom" json:"uom"`
}

// Validasi item yang mau di-restock benar-benar milik transaksi ini
// (mencegah refund_items menunjuk ke sales_item transaksi/tenant lain).
func (q *Queries) GetSalesItemForRefund(ctx context.Context, arg GetSalesItemForRefundParams) (GetSalesItemForRefundRow, error) {
	row := q.db.QueryRow(ctx, getSalesItemForRefund, arg.TenantID, arg.TransactionID, arg.ID)
	var i GetSalesItemForRefundRow
	err := row.Scan(&i.VariantID, &i.Uom)
	return i, err
}

const getSyncReceipt = `-- name: GetSyncReceipt :one
SELECT idempotency_key, request_hash, response_status, response_body
FROM sync_receipts
WHERE tenant_id       = $1
  AND idempotency_key = $2
`

type GetSyncReceiptParams struct {
	TenantID       string `db:"tenant_id" json:"tenant_id"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
}

type GetSyncReceiptRow struct {
	IdempotencyKey string          `db:"idempotency_key" json:"idempotency_key"`
	RequestHash    string          `db:"request_hash" json:"request_hash"`
	ResponseStatus int32           `db:"response_status" json:"response_status"`
	ResponseBody   json.RawMessage `db:"response_body" json:"response_body"`
}

// Dipanggil SEBELUM memproses batch. Bila key sudah ada dengan hash body yang
// sama, kembalikan respons tersimpan apa adanya — klien menerima jawaban
// identik seperti percobaan pertama.
func (q *Queries) GetSyncReceipt(ctx context.Context, arg GetSyncReceiptParams) (GetSyncReceiptRow, error) {
	row := q.db.QueryRow(ctx, getSyncReceipt, arg.TenantID, arg.IdempotencyKey)
	var i GetSyncReceiptRow
	err := row.Scan(
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
	)
	return i, err
}

const incrementStockForRefund = `-- name: IncrementStockForRefund :one
UPDATE variants
SET stock_quantity = stock_quantity + $3
WHERE tenant_id = $1
  AND id        = $2
  AND item_type IN ('stock', 'composite')
RETURNING stock_quantity
`

type IncrementStockForRefundParams struct {
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	ID            string          `db:"id" json:"id"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
}

// Kebalikan DecrementStockAllowNegative — barang fisik kembali ke rak.
// item_type dibatasi sama seperti pemotongan stok checkout.
func (q *Queries) IncrementStockForRefund(ctx context.Context, arg IncrementStockForRefundParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, incrementStockForRefund, arg.TenantID, arg.ID, arg.StockQuantity)
	var stock_quantity decimal.Decimal
	err := row.Scan(&stock_quantity)
	return stock_quantity, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (
    id, tenant_id, outlet_id, actor_user_id, actor_admin_id,
    action_type, reference_id, metadata, ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertAuditLogParams struct {
	ID           string  `db:"id" json:"id"`
	TenantID     string  `db:"tenant_id" json:"tenant_id"`
	OutletID     *string `db:"outlet_id" json:"outlet_id"`
	ActorUserID  *string `db:"actor_user_id" json:"actor_user_id"`
	ActorAdminID *string `db:"actor_admin_id" json:"actor_admin_id"`
	ActionType   string  `db:"action_type" json:"action_type"`
	ReferenceID  *string `db:"reference_id" json:"reference_id"`
	Metadata     []byte  `db:"metadata" json:"metadata"`
	IpAddress    *string `db:"ip_address" json:"ip_address"`
}

// SECURITY §6 — append-only. Setiap aksi sensitif: void, diskon manual,
// buka laci tanpa transaksi, akses break-glass platform admin.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.ActorUserID,
		arg.ActorAdminID,
		arg.ActionType,
		arg.ReferenceID,
		arg.Metadata,
		arg.IpAddress,
	)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO event_outbox (
    id, tenant_id, event_type, version, payload, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type InsertOutboxEventParams struct {
	ID         string             `db:"id" json:"id"`
	TenantID   string             `db:"tenant_id" json:"tenant_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	Version    int16              `db:"version" json:"version"`
	Payload    json.RawMessage    `db:"payload" json:"payload"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

// Ditulis dalam TRANSAKSI YANG SAMA dengan penjualan.
//
// Postgres dan Redis tidak berbagi transaksi: bila Redis mati setelah COMMIT,
// event akan hilang tanpa cara mendeteksinya. Outbox memindahkan penerbitan
// ke proses terpisah, sehingga Redis boleh mati tanpa menghentikan kasir.
// (EVENT-ARCHITECTURE §5)
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.Version,
		arg.Payload,
		arg.OccurredAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (
    id, tenant_id, transaction_id, payment_method, amount, reference_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type InsertPaymentParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	TransactionID string          `db:"transaction_id" json:"transaction_id"`
	PaymentMethod string          `db:"payment_method" json:"payment_method"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	ReferenceID   *string         `db:"reference_id" json:"reference_id"`
}

// FR-22: satu transaksi boleh punya beberapa baris (Rp 20.000 tunai + Rp 30.000 QRIS).
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.ID,
		arg.TenantID,
		arg.TransactionID,
		arg.PaymentMethod,
		arg.Amount,
		arg.ReferenceID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertRefund = `-- name: InsertRefund :one
INSERT INTO refunds (id, tenant_id, transaction_id, shift_id, refund_type, amount, reason, approved_by, restock)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertRefundParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	TransactionID string          `db:"transaction_id" json:"transaction_id"`
	ShiftID       *string         `db:"shift_id" json:"shift_id"`
	RefundType    string          `db:"refund_type" json:"refund_type"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Reason        string          `db:"reason" json:"reason"`
	ApprovedBy    string          `db:"approved_by" json:"approved_by"`
	Restock       bool            `db:"restock" json:"restock"`
}

func (q *Queries) InsertRefund(ctx context.Context, arg InsertRefundParams) (string, error) {
	row := q.db.QueryRow(ctx, insertRefund,
		arg.ID,
		arg.TenantID,
		arg.TransactionID,
		arg.ShiftID,
		arg.RefundType,
		arg.Amount,
		arg.Reason,
		arg.ApprovedBy,
		arg.Restock,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertRefundItem = `-- name: InsertRefundItem :one
INSERT INTO refund_items (id, tenant_id, refund_id, sales_item_id, quantity, amount)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertRefundItemParams struct {
	ID          string          `db:"id" json:"id"`
	TenantID    string          `db:"tenant_id" json:"tenant_id"`
	RefundID    string          `db:"refund_id" json:"refund_id"`
	SalesItemID string          `db:"sales_item_id" json:"sales_item_id"`
	Quantity    decimal.Decimal `db:"quantity" json:"quantity"`
	Amount      decimal.Decimal `db:"amount" json:"amount"`
}

func (q *Queries) InsertRefundItem(ctx context.Context, arg InsertRefundItemParams) (string, error) {
	row := q.db.QueryRow(ctx, insertRefundItem,
		arg.ID,
		arg.TenantID,
		arg.RefundID,
		arg.SalesItemID,
		arg.Quantity,
		arg.Amount,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

type InsertSalesItemsParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	TransactionID string          `db:"transaction_id" json:"transaction_id"`
	VariantID     string          `db:"variant_id" json:"variant_id"`
	Quantity      decimal.Decimal `db:"quantity" json:"quantity"`
	Uom           string          `db:"uom" json:"uom"`
	UnitPrice     decimal.Decimal `db:"unit_price" json:"unit_price"`
	UnitCost      decimal.Decimal `db:"unit_cost" json:"unit_cost"`
	Subtotal      decimal.Decimal `db:"subtotal" json:"subtotal"`
}

type InsertStockEventsParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	OutletID      string          `db:"outlet_id" json:"outlet_id"`
	VariantID     string          `db:"variant_id" json:"variant_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	QuantityDelta decimal.Decimal `db:"quantity_delta" json:"quantity_delta"`
	BalanceAfter  decimal.Decimal `db:"balance_after" json:"balance_after"`
	Uom           string          `db:"uom" json:"uom"`
	ReferenceID   *string         `db:"reference_id" json:"reference_id"`
	ActorUserID   *string         `db:"actor_user_id" json:"actor_user_id"`
}

const listApprovers = `-- name: ListApprovers :many
SELECT id, name, role, (pin_hash IS NOT NULL)::boolean AS punya_pin
FROM users
WHERE tenant_id = $1
  AND is_active
  AND role IN ('owner', 'manager')
ORDER BY role, name
`

type ListApproversRow struct {
	ID       string `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	Role     string `db:"role" json:"role"`
	PunyaPin bool   `db:"punya_pin" json:"punya_pin"`
}

// Siapa yang bisa dimintai PIN saat kasir perlu persetujuan (refund, void,
// diskon besar). Hanya nama & peran — TIDAK ADA pin_hash di sini; daftar ini
// dikirim ke perangkat kasir, dan hash PIN tidak boleh ikut keluar dari
// server dalam keadaan apa pun.
//
// Manager yang BELUM mengatur PIN tetap ditampilkan, ditandai lewat
// `punya_pin`: kasir yang memanggil manajer ke kasir lalu menemukan PIN-nya
// belum ada akan menyalahkan aplikasi, bukan pengaturan akunnya.
func (q *Queries) ListApprovers(ctx context.Context, tenantID string) ([]ListApproversRow, error) {
	rows, err := q.db.Query(ctx, listApprovers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApproversRow{}
	for rows.Next() {
		var i ListApproversRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.PunyaPin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSyncReceipt = `-- name: SaveSyncReceipt :exec
INSERT INTO sync_receipts (
    idempotency_key, tenant_id, outlet_id, device_id,
    request_hash, response_status, response_body, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now() + interval '7 days'
)
ON CONFLICT (idempotency_key) DO NOTHING
`

type SaveSyncReceiptParams struct {
	IdempotencyKey string          `db:"idempotency_key" json:"idempotency_key"`
	TenantID       string          `db:"tenant_id" json:"tenant_id"`
	OutletID       string          `db:"outlet_id" json:"outlet_id"`
	DeviceID       string          `db:"device_id" json:"device_id"`
	RequestHash    string          `db:"request_hash" json:"request_hash"`
	ResponseStatus int32           `db:"response_status" json:"response_status"`
	ResponseBody   json.RawMessage `db:"response_body" json:"response_body"`
}

// Retensi 7 hari; dibersihkan job harian. (RETENTION §2)
func (q *Queries) SaveSyncReceipt(ctx context.Context, arg SaveSyncReceiptParams) error {
	_, err := q.db.Exec(ctx, saveSyncReceipt,
		arg.IdempotencyKey,
		arg.TenantID,
		arg.OutletID,
		arg.DeviceID,
		arg.RequestHash,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const sumRefundsForTransaction = `-- name: SumRefundsForTransaction :one
SELECT COALESCE(SUM(amount), 0)::decimal AS total_refunded
FROM refunds
WHERE tenant_id = $1 AND transaction_id = $2
`

type SumRefundsForTransactionParams struct {
	TenantID      string `db:"tenant_id" json:"tenant_id"`
	TransactionID string `db:"transaction_id" json:"transaction_id"`
}

// Refund SEBELUMNYA pada transaksi yang sama — dijumlahkan dengan permintaan
// baru lewat money.RemainingRefundable sebelum refund ini disimpan.
func (q *Queries) SumRefundsForTransaction(ctx context.Context, arg SumRefundsForTransactionParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, sumRefundsForTransaction, arg.TenantID, arg.TransactionID)
	var total_refunded decimal.Decimal
	err := row.Scan(&total_refunded)
	return total_refunded, err
}

const upsertDeviceSyncState = `-- name: UpsertDeviceSyncState :exec
INSERT INTO device_sync_state (
    id, tenant_id, outlet_id, device_id,
    last_push_at, pending_count, storage_used_pct,
    persistent_storage_granted, app_version
) VALUES (
    $1, $2, $3, $4, now(), $5, $6, $7, $8
)
ON CONFLICT (tenant_id, outlet_id, device_id) DO UPDATE
SET last_push_at               = now(),
    pending_count              = EXCLUDED.pending_count,
    storage_used_pct           = EXCLUDED.storage_used_pct,
    persistent_storage_granted = EXCLUDED.persistent_storage_granted,
    app_version                = EXCLUDED.app_version
`

type UpsertDeviceSyncStateParams struct {
	ID                       string  `db:"id" json:"id"`
	TenantID                 string  `db:"tenant_id" json:"tenant_id"`
	OutletID                 string  `db:"outlet_id" json:"outlet_id"`
	DeviceID                 string  `db:"device_id" json:"device_id"`
	PendingCount             int32   `db:"pending_count" json:"pending_count"`
	StorageUsedPct           *int16  `db:"storage_used_pct" json:"storage_used_pct"`
	PersistentStorageGranted *bool   `db:"persistent_storage_granted" json:"persistent_storage_granted"`
	AppVersion               *string `db:"app_version" json:"app_version"`
}

// Telemetri perangkat ikut bersama sync. storage_used_pct adalah peringatan dini
// sebelum IndexedDB penuh — server bisa tampak sehat sempurna sementara sebuah
// perangkat kasir mendekati kegagalan total. (OBSERVABILITY §3)
func (q *Queries) UpsertDeviceSyncState(ctx context.Context, arg UpsertDeviceSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceSyncState,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.DeviceID,
		arg.PendingCount,
		arg.StorageUsedPct,
		arg.PersistentStorageGranted,
		arg.AppVersion,
	)
	return err
}

const voidTransaction = `-- name: VoidTransaction :one

UPDATE sales_transactions
SET payment_status = 'void'
WHERE tenant_id      = $1
  AND id             = $2
  AND payment_status = 'paid'
RETURNING id, grand_total
`

type VoidTransactionParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type VoidTransactionRow struct {
	ID         string          `db:"id" json:"id"`
	GrandTotal decimal.Decimal `db:"grand_total" json:"grand_total"`
}

// ── VOID & IDEMPOTENSI ─────────────────────────────────────────────────
// Hanya transaksi 'paid' yang bisa di-void; mencoba void dua kali
// mengembalikan 0 baris → TRANSACTION_ALREADY_VOIDED (kelas PERMANENT).
func (q *Queries) VoidTransaction(ctx context.Context, arg VoidTransactionParams) (VoidTransactionRow, error) {
	row := q.db.QueryRow(ctx, voidTransaction, arg.TenantID, arg.ID)
	var i VoidTransactionRow
	err := row.Scan(&i.ID, &i.GrandTotal)
	return i, err
}
