// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertSalesItems implements pgx.CopyFromSource.
type iteratorForInsertSalesItems struct {
	rows                 []InsertSalesItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSalesItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSalesItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TenantID,
		r.rows[0].TransactionID,
		r.rows[0].VariantID,
		r.rows[0].Quantity,
		r.rows[0].Uom,
		r.rows[0].UnitPrice,
		r.rows[0].UnitCost,
		r.rows[0].Subtotal,
	}, nil
}

func (r iteratorForInsertSalesItems) Err() error {
	return nil
}

// HOT PATH. quantity DECIMAL(14,3) — 0,25 kg tepung · 30 ml parfum.
// unit_price & unit_cost DISALIN saat transaksi: laporan tidak pernah
// menghitung ulang memakai harga sekarang.
func (q *Queries) InsertSalesItems(ctx context.Context, arg []InsertSalesItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"sales_items"}, []string{"id", "tenant_id", "transaction_id", "variant_id", "quantity", "uom", "unit_price", "unit_cost", "subtotal"}, &iteratorForInsertSalesItems{rows: arg})
}

// iteratorForInsertStockEvents implements pgx.CopyFromSource.
type iteratorForInsertStockEvents struct {
	rows                 []InsertStockEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStockEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStockEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].TenantID,
		r.rows[0].OutletID,
		r.rows[0].VariantID,
		r.rows[0].EventType,
		r.rows[0].QuantityDelta,
		r.rows[0].BalanceAfter,
		r.rows[0].Uom,
		r.rows[0].ReferenceID,
		r.rows[0].ActorUserID,
	}, nil
}

func (r iteratorForInsertStockEvents) Err() error {
	return nil
}

// Ledger append-only. variants.stock_quantity hanyalah cache;
// KEBENARAN stok ada di tabel ini. (DATA-MODEL §4C)
func (q *Queries) InsertStockEvents(ctx context.Context, arg []InsertStockEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"stock_events"}, []string{"id", "tenant_id", "outlet_id", "variant_id", "event_type", "quantity_delta", "balance_after", "uom", "reference_id", "actor_user_id"}, &iteratorForInsertStockEvents{rows: arg})
}
