// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const customerBelongsToTenant = `-- name: CustomerBelongsToTenant :one
SELECT EXISTS (
    SELECT 1 FROM customers WHERE tenant_id = $1 AND id = $2 AND merged_into_id IS NULL
)
`

type CustomerBelongsToTenantParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

// Foreign key hanya menjamin pelanggan ADA, bukan milik tenant yang sama.
// Tanpa pemeriksaan ini, penjualan tenant A bisa merujuk pelanggan tenant B.
func (q *Queries) CustomerBelongsToTenant(ctx context.Context, arg CustomerBelongsToTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, customerBelongsToTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertCustomerFromSync = `-- name: InsertCustomerFromSync :execrows
INSERT INTO customers (
    id, tenant_id, name, phone, member_code, social_handle, follows_store_social,
    first_seen_at, notes
) VALUES (
    $1, $2, $7, $3, $4, $8, $5, $6, NULL
)
ON CONFLICT (id) DO NOTHING
`

type InsertCustomerFromSyncParams struct {
	ID                 string             `db:"id" json:"id"`
	TenantID           string             `db:"tenant_id" json:"tenant_id"`
	Phone              *string            `db:"phone" json:"phone"`
	MemberCode         *string            `db:"member_code" json:"member_code"`
	FollowsStoreSocial bool               `db:"follows_store_social" json:"follows_store_social"`
	FirstSeenAt        pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	Name               *string            `db:"name" json:"name"`
	SocialHandle       *string            `db:"social_handle" json:"social_handle"`
}

// Member didaftarkan di PERANGKAT (bisa offline) dengan ULID klien — id
// adalah kunci idempotensi: kiriman ulang yang sama menghasilkan 0 baris
// (duplicate), bukan galat. Tabrakan nomor WA / kode member tetap galat
// unik (idx_customers_phone / idx_customers_member_code) dan DITOLAK.
func (q *Queries) InsertCustomerFromSync(ctx context.Context, arg InsertCustomerFromSyncParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCustomerFromSync,
		arg.ID,
		arg.TenantID,
		arg.Phone,
		arg.MemberCode,
		arg.FollowsStoreSocial,
		arg.FirstSeenAt,
		arg.Name,
		arg.SocialHandle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCustomersForSync = `-- name: ListCustomersForSync :many
SELECT id, name, phone, member_code, social_handle, follows_store_social, merchandise_given_at
FROM customers
WHERE tenant_id = $1 AND is_active AND merged_into_id IS NULL AND member_code IS NOT NULL
ORDER BY created_at
LIMIT 5000
`

type ListCustomersForSyncRow struct {
	ID                 string             `db:"id" json:"id"`
	Name               *string            `db:"name" json:"name"`
	Phone              *string            `db:"phone" json:"phone"`
	MemberCode         *string            `db:"member_code" json:"member_code"`
	SocialHandle       *string            `db:"social_handle" json:"social_handle"`
	FollowsStoreSocial bool               `db:"follows_store_social" json:"follows_store_social"`
	MerchandiseGivenAt pgtype.Timestamptz `db:"merchandise_given_at" json:"merchandise_given_at"`
}

// Yang dikirim ke perangkat kasir HANYA nama, WA, kode member, akun sosial
// media, dan status merchandise — bukan email/tanggal lahir/catatan
// (DATA-MODEL §5 "jangan simpan email & tanggal lahir di perangkat").
func (q *Queries) ListCustomersForSync(ctx context.Context, tenantID string) ([]ListCustomersForSyncRow, error) {
	rows, err := q.db.Query(ctx, listCustomersForSync, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomersForSyncRow{}
	for rows.Next() {
		var i ListCustomersForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.MemberCode,
			&i.SocialHandle,
			&i.FollowsStoreSocial,
			&i.MerchandiseGivenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCustomerPurchase = `-- name: MarkCustomerPurchase :one
UPDATE customers
SET last_seen_at = GREATEST(COALESCE(last_seen_at, $3::timestamptz), $3::timestamptz),
    merchandise_given_at = COALESCE(merchandise_given_at, $3::timestamptz)
WHERE tenant_id = $1 AND id = $2
RETURNING merchandise_given_at = $3::timestamptz AS pembelian_pertama
`

type MarkCustomerPurchaseParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	ID       string             `db:"id" json:"id"`
	At       pgtype.Timestamptz `db:"at" json:"at"`
}

// Dipanggil di transaksi penjualan yang sama. merchandise_given_at hanya
// diisi SEKALI — pada transaksi pertama member — dan tidak pernah ditimpa.
// Mengembalikan apakah transaksi ini yang pertama.
func (q *Queries) MarkCustomerPurchase(ctx context.Context, arg MarkCustomerPurchaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, markCustomerPurchase, arg.TenantID, arg.ID, arg.At)
	var pembelian_pertama bool
	err := row.Scan(&pembelian_pertama)
	return pembelian_pertama, err
}
