// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AuditLog struct {
	ID           string             `db:"id" json:"id"`
	TenantID     string             `db:"tenant_id" json:"tenant_id"`
	OutletID     *string            `db:"outlet_id" json:"outlet_id"`
	ActorUserID  *string            `db:"actor_user_id" json:"actor_user_id"`
	ActorAdminID *string            `db:"actor_admin_id" json:"actor_admin_id"`
	ActionType   string             `db:"action_type" json:"action_type"`
	ReferenceID  *string            `db:"reference_id" json:"reference_id"`
	Metadata     []byte             `db:"metadata" json:"metadata"`
	IpAddress    *string            `db:"ip_address" json:"ip_address"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BackgroundJob struct {
	ID           string             `db:"id" json:"id"`
	TenantID     *string            `db:"tenant_id" json:"tenant_id"`
	JobType      string             `db:"job_type" json:"job_type"`
	Status       string             `db:"status" json:"status"`
	Payload      []byte             `db:"payload" json:"payload"`
	Result       []byte             `db:"result" json:"result"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
	AttemptCount int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts  int32              `db:"max_attempts" json:"max_attempts"`
	NextRetryAt  pgtype.Timestamptz `db:"next_retry_at" json:"next_retry_at"`
	CreatedBy    *string            `db:"created_by" json:"created_by"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	FinishedAt   pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type BomComponent struct {
	ID                 string             `db:"id" json:"id"`
	TenantID           string             `db:"tenant_id" json:"tenant_id"`
	ParentVariantID    string             `db:"parent_variant_id" json:"parent_variant_id"`
	ComponentVariantID string             `db:"component_variant_id" json:"component_variant_id"`
	Quantity           decimal.Decimal    `db:"quantity" json:"quantity"`
	Uom                string             `db:"uom" json:"uom"`
	WastePct           decimal.Decimal    `db:"waste_pct" json:"waste_pct"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type BreakglassSession struct {
	ID               string             `db:"id" json:"id"`
	AdminID          string             `db:"admin_id" json:"admin_id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	Reason           string             `db:"reason" json:"reason"`
	TicketRef        *string            `db:"ticket_ref" json:"ticket_ref"`
	StartedAt        pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	EndedAt          pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	TenantNotifiedAt pgtype.Timestamptz `db:"tenant_notified_at" json:"tenant_notified_at"`
}

type CashMovement struct {
	ID          string             `db:"id" json:"id"`
	TenantID    string             `db:"tenant_id" json:"tenant_id"`
	ShiftID     string             `db:"shift_id" json:"shift_id"`
	Direction   string             `db:"direction" json:"direction"`
	Amount      decimal.Decimal    `db:"amount" json:"amount"`
	Reason      string             `db:"reason" json:"reason"`
	ActorUserID string             `db:"actor_user_id" json:"actor_user_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Category struct {
	ID         string             `db:"id" json:"id"`
	TenantID   string             `db:"tenant_id" json:"tenant_id"`
	Name       string             `db:"name" json:"name"`
	SortOrder  int32              `db:"sort_order" json:"sort_order"`
	ColorToken *string            `db:"color_token" json:"color_token"`
	IsActive   bool               `db:"is_active" json:"is_active"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Customer struct {
	ID           string             `db:"id" json:"id"`
	TenantID     string             `db:"tenant_id" json:"tenant_id"`
	Name         *string            `db:"name" json:"name"`
	Phone        *string            `db:"phone" json:"phone"`
	Email        *string            `db:"email" json:"email"`
	BirthDate    pgtype.Date        `db:"birth_date" json:"birth_date"`
	Notes        *string            `db:"notes" json:"notes"`
	FirstSeenAt  pgtype.Timestamptz `db:"first_seen_at" json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	MergedIntoID *string            `db:"merged_into_id" json:"merged_into_id"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CustomerConsent struct {
	ID          string             `db:"id" json:"id"`
	TenantID    string             `db:"tenant_id" json:"tenant_id"`
	CustomerID  string             `db:"customer_id" json:"customer_id"`
	ConsentType string             `db:"consent_type" json:"consent_type"`
	Granted     bool               `db:"granted" json:"granted"`
	GrantedAt   pgtype.Timestamptz `db:"granted_at" json:"granted_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CapturedBy  *string            `db:"captured_by" json:"captured_by"`
	Source      *string            `db:"source" json:"source"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CustomerInteraction struct {
	ID              string             `db:"id" json:"id"`
	TenantID        string             `db:"tenant_id" json:"tenant_id"`
	CustomerID      string             `db:"customer_id" json:"customer_id"`
	InteractionType string             `db:"interaction_type" json:"interaction_type"`
	Channel         *string            `db:"channel" json:"channel"`
	Content         *string            `db:"content" json:"content"`
	ActorUserID     *string            `db:"actor_user_id" json:"actor_user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CustomerLink struct {
	ID         string             `db:"id" json:"id"`
	IdentityID string             `db:"identity_id" json:"identity_id"`
	TenantID   string             `db:"tenant_id" json:"tenant_id"`
	CustomerID string             `db:"customer_id" json:"customer_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CustomerSegment struct {
	ID             string              `db:"id" json:"id"`
	TenantID       string              `db:"tenant_id" json:"tenant_id"`
	CustomerID     string              `db:"customer_id" json:"customer_id"`
	Segment        string              `db:"segment" json:"segment"`
	RecencyDays    *int32              `db:"recency_days" json:"recency_days"`
	FrequencyCount *int32              `db:"frequency_count" json:"frequency_count"`
	MonetaryTotal  decimal.NullDecimal `db:"monetary_total" json:"monetary_total"`
	ChurnRisk      *string             `db:"churn_risk" json:"churn_risk"`
	Reasoning      string              `db:"reasoning" json:"reasoning"`
	ComputedAt     pgtype.Timestamptz  `db:"computed_at" json:"computed_at"`
}

type DailyOutletSummary struct {
	ID                      string             `db:"id" json:"id"`
	TenantID                string             `db:"tenant_id" json:"tenant_id"`
	OutletID                string             `db:"outlet_id" json:"outlet_id"`
	BusinessDate            pgtype.Date        `db:"business_date" json:"business_date"`
	TransactionCount        int32              `db:"transaction_count" json:"transaction_count"`
	GrossSales              decimal.Decimal    `db:"gross_sales" json:"gross_sales"`
	DiscountTotal           decimal.Decimal    `db:"discount_total" json:"discount_total"`
	NetSales                decimal.Decimal    `db:"net_sales" json:"net_sales"`
	CogsTotal               decimal.Decimal    `db:"cogs_total" json:"cogs_total"`
	GrossProfit             decimal.Decimal    `db:"gross_profit" json:"gross_profit"`
	PaymentBreakdown        json.RawMessage    `db:"payment_breakdown" json:"payment_breakdown"`
	OfflineTransactionCount int32              `db:"offline_transaction_count" json:"offline_transaction_count"`
	UniqueCustomerCount     *int32             `db:"unique_customer_count" json:"unique_customer_count"`
	ComputedAt              pgtype.Timestamptz `db:"computed_at" json:"computed_at"`
}

type DeviceSyncState struct {
	ID                       string             `db:"id" json:"id"`
	TenantID                 string             `db:"tenant_id" json:"tenant_id"`
	OutletID                 string             `db:"outlet_id" json:"outlet_id"`
	DeviceID                 string             `db:"device_id" json:"device_id"`
	LastPullCursor           *string            `db:"last_pull_cursor" json:"last_pull_cursor"`
	LastPullAt               pgtype.Timestamptz `db:"last_pull_at" json:"last_pull_at"`
	LastPushAt               pgtype.Timestamptz `db:"last_push_at" json:"last_push_at"`
	PendingCount             int32              `db:"pending_count" json:"pending_count"`
	StorageUsedPct           *int16             `db:"storage_used_pct" json:"storage_used_pct"`
	PersistentStorageGranted *bool              `db:"persistent_storage_granted" json:"persistent_storage_granted"`
	AppVersion               *string            `db:"app_version" json:"app_version"`
}

type Distributor struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Phone     *string            `db:"phone" json:"phone"`
	Email     *string            `db:"email" json:"email"`
	IsActive  bool               `db:"is_active" json:"is_active"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type DistributorTenantLink struct {
	ID            string             `db:"id" json:"id"`
	DistributorID string             `db:"distributor_id" json:"distributor_id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	IdentityID    *string            `db:"identity_id" json:"identity_id"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type EventOutbox struct {
	ID          string             `db:"id" json:"id"`
	TenantID    string             `db:"tenant_id" json:"tenant_id"`
	EventType   string             `db:"event_type" json:"event_type"`
	Version     int16              `db:"version" json:"version"`
	Payload     json.RawMessage    `db:"payload" json:"payload"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
}

type Identity struct {
	ID           string             `db:"id" json:"id"`
	Email        *string            `db:"email" json:"email"`
	Phone        *string            `db:"phone" json:"phone"`
	PasswordHash *string            `db:"password_hash" json:"password_hash"`
	VerifiedAt   pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Outlet struct {
	ID               string             `db:"id" json:"id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	Name             string             `db:"name" json:"name"`
	Address          *string            `db:"address" json:"address"`
	Phone            *string            `db:"phone" json:"phone"`
	Timezone         string             `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time        `db:"business_day_start" json:"business_day_start"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ReceiptFooter    *string            `db:"receipt_footer" json:"receipt_footer"`
	WarrantyDays     int16              `db:"warranty_days" json:"warranty_days"`
}

type OutletPriceOverride struct {
	ID            string             `db:"id" json:"id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	OutletID      string             `db:"outlet_id" json:"outlet_id"`
	VariantID     string             `db:"variant_id" json:"variant_id"`
	Price         decimal.Decimal    `db:"price" json:"price"`
	EffectiveFrom pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
}

type Payment struct {
	ID            string             `db:"id" json:"id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	TransactionID string             `db:"transaction_id" json:"transaction_id"`
	PaymentMethod string             `db:"payment_method" json:"payment_method"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	ReferenceID   *string            `db:"reference_id" json:"reference_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PlatformAdmin struct {
	ID           string             `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	Name         string             `db:"name" json:"name"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	TotpSecret   string             `db:"totp_secret" json:"totp_secret"`
	Role         string             `db:"role" json:"role"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type PredictionOutcome struct {
	ID                 string             `db:"id" json:"id"`
	TenantID           string             `db:"tenant_id" json:"tenant_id"`
	PredictionID       string             `db:"prediction_id" json:"prediction_id"`
	ActualStockoutDate pgtype.Date        `db:"actual_stockout_date" json:"actual_stockout_date"`
	WasFollowed        *bool              `db:"was_followed" json:"was_followed"`
	ErrorDays          *int32             `db:"error_days" json:"error_days"`
	RecordedAt         pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type Product struct {
	ID          string             `db:"id" json:"id"`
	TenantID    string             `db:"tenant_id" json:"tenant_id"`
	CategoryID  *string            `db:"category_id" json:"category_id"`
	Name        string             `db:"name" json:"name"`
	Description *string            `db:"description" json:"description"`
	ImageUrl    *string            `db:"image_url" json:"image_url"`
	IsActive    bool               `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ProductPerformanceSummary struct {
	ID           string             `db:"id" json:"id"`
	TenantID     string             `db:"tenant_id" json:"tenant_id"`
	OutletID     string             `db:"outlet_id" json:"outlet_id"`
	VariantID    string             `db:"variant_id" json:"variant_id"`
	PeriodStart  pgtype.Date        `db:"period_start" json:"period_start"`
	PeriodType   string             `db:"period_type" json:"period_type"`
	QuantitySold decimal.Decimal    `db:"quantity_sold" json:"quantity_sold"`
	Revenue      decimal.Decimal    `db:"revenue" json:"revenue"`
	GrossProfit  decimal.Decimal    `db:"gross_profit" json:"gross_profit"`
	RankInOutlet *int32             `db:"rank_in_outlet" json:"rank_in_outlet"`
	ComputedAt   pgtype.Timestamptz `db:"computed_at" json:"computed_at"`
}

type RefreshToken struct {
	ID                string             `db:"id" json:"id"`
	TenantID          string             `db:"tenant_id" json:"tenant_id"`
	UserID            string             `db:"user_id" json:"user_id"`
	TokenHash         string             `db:"token_hash" json:"token_hash"`
	DeviceLabel       *string            `db:"device_label" json:"device_label"`
	DeviceFingerprint *string            `db:"device_fingerprint" json:"device_fingerprint"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedReason     *string            `db:"revoked_reason" json:"revoked_reason"`
	LastUsedAt        pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Refund struct {
	ID            string             `db:"id" json:"id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	TransactionID string             `db:"transaction_id" json:"transaction_id"`
	ShiftID       *string            `db:"shift_id" json:"shift_id"`
	RefundType    string             `db:"refund_type" json:"refund_type"`
	Amount        decimal.Decimal    `db:"amount" json:"amount"`
	Reason        string             `db:"reason" json:"reason"`
	ApprovedBy    string             `db:"approved_by" json:"approved_by"`
	Restock       bool               `db:"restock" json:"restock"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RefundItem struct {
	ID          string          `db:"id" json:"id"`
	TenantID    string          `db:"tenant_id" json:"tenant_id"`
	RefundID    string          `db:"refund_id" json:"refund_id"`
	SalesItemID string          `db:"sales_item_id" json:"sales_item_id"`
	Quantity    decimal.Decimal `db:"quantity" json:"quantity"`
	Amount      decimal.Decimal `db:"amount" json:"amount"`
}

type RestockPrediction struct {
	ID                    string              `db:"id" json:"id"`
	TenantID              string              `db:"tenant_id" json:"tenant_id"`
	OutletID              string              `db:"outlet_id" json:"outlet_id"`
	VariantID             string              `db:"variant_id" json:"variant_id"`
	PredictedStockoutDate pgtype.Date         `db:"predicted_stockout_date" json:"predicted_stockout_date"`
	RecommendedQty        decimal.NullDecimal `db:"recommended_qty" json:"recommended_qty"`
	Uom                   *string             `db:"uom" json:"uom"`
	Confidence            *string             `db:"confidence" json:"confidence"`
	Method                *string             `db:"method" json:"method"`
	Reasoning             string              `db:"reasoning" json:"reasoning"`
	ComputedAt            pgtype.Timestamptz  `db:"computed_at" json:"computed_at"`
}

type RoleTemplate struct {
	ID          string             `db:"id" json:"id"`
	TenantID    *string            `db:"tenant_id" json:"tenant_id"`
	Code        string             `db:"code" json:"code"`
	Name        string             `db:"name" json:"name"`
	Permissions json.RawMessage    `db:"permissions" json:"permissions"`
	IsSystem    bool               `db:"is_system" json:"is_system"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SalesItem struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	TransactionID string          `db:"transaction_id" json:"transaction_id"`
	VariantID     string          `db:"variant_id" json:"variant_id"`
	Quantity      decimal.Decimal `db:"quantity" json:"quantity"`
	Uom           string          `db:"uom" json:"uom"`
	UnitPrice     decimal.Decimal `db:"unit_price" json:"unit_price"`
	UnitCost      decimal.Decimal `db:"unit_cost" json:"unit_cost"`
	Subtotal      decimal.Decimal `db:"subtotal" json:"subtotal"`
}

type SalesTransaction struct {
	ID                  string             `db:"id" json:"id"`
	TenantID            string             `db:"tenant_id" json:"tenant_id"`
	OutletID            string             `db:"outlet_id" json:"outlet_id"`
	CashierID           string             `db:"cashier_id" json:"cashier_id"`
	ShiftID             *string            `db:"shift_id" json:"shift_id"`
	CustomerID          *string            `db:"customer_id" json:"customer_id"`
	ReceiptNumber       string             `db:"receipt_number" json:"receipt_number"`
	Subtotal            decimal.Decimal    `db:"subtotal" json:"subtotal"`
	DiscountTotal       decimal.Decimal    `db:"discount_total" json:"discount_total"`
	TaxTotal            decimal.Decimal    `db:"tax_total" json:"tax_total"`
	GrandTotal          decimal.Decimal    `db:"grand_total" json:"grand_total"`
	PaymentStatus       string             `db:"payment_status" json:"payment_status"`
	OfflineCreatedAt    pgtype.Timestamptz `db:"offline_created_at" json:"offline_created_at"`
	OfflineCreatedAtAdj pgtype.Timestamptz `db:"offline_created_at_adj" json:"offline_created_at_adj"`
	DeviceClockOffsetS  *int32             `db:"device_clock_offset_s" json:"device_clock_offset_s"`
	DeviceID            *string            `db:"device_id" json:"device_id"`
	SyncedAt            pgtype.Timestamptz `db:"synced_at" json:"synced_at"`
	IsLateArrival       bool               `db:"is_late_arrival" json:"is_late_arrival"`
	IsSandbox           bool               `db:"is_sandbox" json:"is_sandbox"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Shift struct {
	ID           string              `db:"id" json:"id"`
	TenantID     string              `db:"tenant_id" json:"tenant_id"`
	OutletID     string              `db:"outlet_id" json:"outlet_id"`
	CashierID    string              `db:"cashier_id" json:"cashier_id"`
	OpenedAt     pgtype.Timestamptz  `db:"opened_at" json:"opened_at"`
	ClosedAt     pgtype.Timestamptz  `db:"closed_at" json:"closed_at"`
	OpeningCash  decimal.Decimal     `db:"opening_cash" json:"opening_cash"`
	ExpectedCash decimal.NullDecimal `db:"expected_cash" json:"expected_cash"`
	CountedCash  decimal.NullDecimal `db:"counted_cash" json:"counted_cash"`
	Variance     decimal.NullDecimal `db:"variance" json:"variance"`
	Status       string              `db:"status" json:"status"`
	ClosedBy     *string             `db:"closed_by" json:"closed_by"`
	CreatedAt    pgtype.Timestamptz  `db:"created_at" json:"created_at"`
}

type SopExecution struct {
	ID            string             `db:"id" json:"id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	OutletID      string             `db:"outlet_id" json:"outlet_id"`
	SopTemplateID string             `db:"sop_template_id" json:"sop_template_id"`
	ShiftID       *string            `db:"shift_id" json:"shift_id"`
	ActorUserID   string             `db:"actor_user_id" json:"actor_user_id"`
	Status        string             `db:"status" json:"status"`
	SkipReason    *string            `db:"skip_reason" json:"skip_reason"`
	Results       []byte             `db:"results" json:"results"`
	StartedAt     pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt   pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SopTemplate struct {
	ID           string             `db:"id" json:"id"`
	TenantID     *string            `db:"tenant_id" json:"tenant_id"`
	Archetype    *string            `db:"archetype" json:"archetype"`
	Code         string             `db:"code" json:"code"`
	Name         string             `db:"name" json:"name"`
	TriggerType  string             `db:"trigger_type" json:"trigger_type"`
	ScheduleCron *string            `db:"schedule_cron" json:"schedule_cron"`
	RequiredRole *string            `db:"required_role" json:"required_role"`
	IsBlocking   bool               `db:"is_blocking" json:"is_blocking"`
	Steps        json.RawMessage    `db:"steps" json:"steps"`
	IsSystem     bool               `db:"is_system" json:"is_system"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type StockEvent struct {
	ID            string             `db:"id" json:"id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	OutletID      string             `db:"outlet_id" json:"outlet_id"`
	VariantID     string             `db:"variant_id" json:"variant_id"`
	EventType     string             `db:"event_type" json:"event_type"`
	QuantityDelta decimal.Decimal    `db:"quantity_delta" json:"quantity_delta"`
	BalanceAfter  decimal.Decimal    `db:"balance_after" json:"balance_after"`
	Uom           string             `db:"uom" json:"uom"`
	ReferenceID   *string            `db:"reference_id" json:"reference_id"`
	ActorUserID   *string            `db:"actor_user_id" json:"actor_user_id"`
	Note          *string            `db:"note" json:"note"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type StockOpname struct {
	ID         string             `db:"id" json:"id"`
	TenantID   string             `db:"tenant_id" json:"tenant_id"`
	OutletID   string             `db:"outlet_id" json:"outlet_id"`
	Status     string             `db:"status" json:"status"`
	StartedBy  string             `db:"started_by" json:"started_by"`
	ApprovedBy *string            `db:"approved_by" json:"approved_by"`
	StartedAt  pgtype.Timestamptz `db:"started_at" json:"started_at"`
	ApprovedAt pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
}

type StockOpnameItem struct {
	ID              string              `db:"id" json:"id"`
	TenantID        string              `db:"tenant_id" json:"tenant_id"`
	OpnameID        string              `db:"opname_id" json:"opname_id"`
	VariantID       string              `db:"variant_id" json:"variant_id"`
	SystemQuantity  decimal.Decimal     `db:"system_quantity" json:"system_quantity"`
	CountedQuantity decimal.Decimal     `db:"counted_quantity" json:"counted_quantity"`
	Variance        decimal.NullDecimal `db:"variance" json:"variance"`
}

type StockTransfer struct {
	ID           string             `db:"id" json:"id"`
	TenantID     string             `db:"tenant_id" json:"tenant_id"`
	FromOutletID string             `db:"from_outlet_id" json:"from_outlet_id"`
	ToOutletID   string             `db:"to_outlet_id" json:"to_outlet_id"`
	Status       string             `db:"status" json:"status"`
	SentBy       string             `db:"sent_by" json:"sent_by"`
	ReceivedBy   *string            `db:"received_by" json:"received_by"`
	SentAt       pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	ReceivedAt   pgtype.Timestamptz `db:"received_at" json:"received_at"`
}

type StockTransferItem struct {
	ID               string              `db:"id" json:"id"`
	TenantID         string              `db:"tenant_id" json:"tenant_id"`
	TransferID       string              `db:"transfer_id" json:"transfer_id"`
	VariantID        string              `db:"variant_id" json:"variant_id"`
	QuantitySent     decimal.Decimal     `db:"quantity_sent" json:"quantity_sent"`
	QuantityReceived decimal.NullDecimal `db:"quantity_received" json:"quantity_received"`
	Uom              string              `db:"uom" json:"uom"`
}

type SyncReceipt struct {
	IdempotencyKey string             `db:"idempotency_key" json:"idempotency_key"`
	TenantID       string             `db:"tenant_id" json:"tenant_id"`
	OutletID       string             `db:"outlet_id" json:"outlet_id"`
	DeviceID       string             `db:"device_id" json:"device_id"`
	RequestHash    string             `db:"request_hash" json:"request_hash"`
	ResponseStatus int32              `db:"response_status" json:"response_status"`
	ResponseBody   json.RawMessage    `db:"response_body" json:"response_body"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type Tenant struct {
	ID           string             `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	BusinessType *string            `db:"business_type" json:"business_type"`
	PlanTier     string             `db:"plan_tier" json:"plan_tier"`
	PlanStatus   string             `db:"plan_status" json:"plan_status"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UomConversion struct {
	ID        string             `db:"id" json:"id"`
	TenantID  string             `db:"tenant_id" json:"tenant_id"`
	VariantID string             `db:"variant_id" json:"variant_id"`
	FromUom   string             `db:"from_uom" json:"from_uom"`
	ToUom     string             `db:"to_uom" json:"to_uom"`
	Factor    decimal.Decimal    `db:"factor" json:"factor"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID           string             `db:"id" json:"id"`
	TenantID     string             `db:"tenant_id" json:"tenant_id"`
	Name         string             `db:"name" json:"name"`
	Email        string             `db:"email" json:"email"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Role         string             `db:"role" json:"role"`
	PinHash      *string            `db:"pin_hash" json:"pin_hash"`
	IsActive     bool               `db:"is_active" json:"is_active"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserOutletAssignment struct {
	ID        string             `db:"id" json:"id"`
	TenantID  string             `db:"tenant_id" json:"tenant_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	OutletID  string             `db:"outlet_id" json:"outlet_id"`
	IsPrimary bool               `db:"is_primary" json:"is_primary"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type UserPermission struct {
	ID         string             `db:"id" json:"id"`
	TenantID   string             `db:"tenant_id" json:"tenant_id"`
	UserID     string             `db:"user_id" json:"user_id"`
	Permission string             `db:"permission" json:"permission"`
	Granted    bool               `db:"granted" json:"granted"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Variant struct {
	ID            string             `db:"id" json:"id"`
	TenantID      string             `db:"tenant_id" json:"tenant_id"`
	ProductID     string             `db:"product_id" json:"product_id"`
	Name          string             `db:"name" json:"name"`
	Sku           *string            `db:"sku" json:"sku"`
	Barcode       *string            `db:"barcode" json:"barcode"`
	ItemType      string             `db:"item_type" json:"item_type"`
	Uom           string             `db:"uom" json:"uom"`
	UomPrecision  int16              `db:"uom_precision" json:"uom_precision"`
	Price         decimal.Decimal    `db:"price" json:"price"`
	CostPrice     decimal.Decimal    `db:"cost_price" json:"cost_price"`
	StockQuantity decimal.Decimal    `db:"stock_quantity" json:"stock_quantity"`
	MinStockAlert decimal.Decimal    `db:"min_stock_alert" json:"min_stock_alert"`
	IsActive      bool               `db:"is_active" json:"is_active"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type WebhookEvent struct {
	ID              string             `db:"id" json:"id"`
	Provider        string             `db:"provider" json:"provider"`
	ExternalEventID string             `db:"external_event_id" json:"external_event_id"`
	TenantID        *string            `db:"tenant_id" json:"tenant_id"`
	TransactionID   *string            `db:"transaction_id" json:"transaction_id"`
	SignatureValid  bool               `db:"signature_valid" json:"signature_valid"`
	Payload         json.RawMessage    `db:"payload" json:"payload"`
	ReceivedAt      pgtype.Timestamptz `db:"received_at" json:"received_at"`
	ProcessedAt     pgtype.Timestamptz `db:"processed_at" json:"processed_at"`
	ProcessStatus   string             `db:"process_status" json:"process_status"`
}
