// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outlet.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutlet = `-- name: InsertOutlet :one
INSERT INTO outlets (id, tenant_id, name, address, phone, timezone, business_day_start)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, address, phone, is_active, created_at, timezone, business_day_start, receipt_footer, warranty_days, social_handle
`

type InsertOutletParams struct {
	ID               string      `db:"id" json:"id"`
	TenantID         string      `db:"tenant_id" json:"tenant_id"`
	Name             string      `db:"name" json:"name"`
	Address          *string     `db:"address" json:"address"`
	Phone            *string     `db:"phone" json:"phone"`
	Timezone         string      `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time `db:"business_day_start" json:"business_day_start"`
}

type InsertOutletRow struct {
	ID               string             `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Address          *string            `db:"address" json:"address"`
	Phone            *string            `db:"phone" json:"phone"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Timezone         string             `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time        `db:"business_day_start" json:"business_day_start"`
	ReceiptFooter    *string            `db:"receipt_footer" json:"receipt_footer"`
	WarrantyDays     int16              `db:"warranty_days" json:"warranty_days"`
	SocialHandle     *string            `db:"social_handle" json:"social_handle"`
}

func (q *Queries) InsertOutlet(ctx context.Context, arg InsertOutletParams) (InsertOutletRow, error) {
	row := q.db.QueryRow(ctx, insertOutlet,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Timezone,
		arg.BusinessDayStart,
	)
	var i InsertOutletRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.Timezone,
		&i.BusinessDayStart,
		&i.ReceiptFooter,
		&i.WarrantyDays,
		&i.SocialHandle,
	)
	return i, err
}

const listOutlets = `-- name: ListOutlets :many
SELECT id, tenant_id, name, address, phone, is_active, created_at, timezone, business_day_start,
       receipt_footer, warranty_days, social_handle
FROM outlets
WHERE tenant_id = $1
ORDER BY created_at ASC
`

type ListOutletsRow struct {
	ID               string             `db:"id" json:"id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	Name             string             `db:"name" json:"name"`
	Address          *string            `db:"address" json:"address"`
	Phone            *string            `db:"phone" json:"phone"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Timezone         string             `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time        `db:"business_day_start" json:"business_day_start"`
	ReceiptFooter    *string            `db:"receipt_footer" json:"receipt_footer"`
	WarrantyDays     int16              `db:"warranty_days" json:"warranty_days"`
	SocialHandle     *string            `db:"social_handle" json:"social_handle"`
}

func (q *Queries) ListOutlets(ctx context.Context, tenantID string) ([]ListOutletsRow, error) {
	rows, err := q.db.Query(ctx, listOutlets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutletsRow{}
	for rows.Next() {
		var i ListOutletsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.Timezone,
			&i.BusinessDayStart,
			&i.ReceiptFooter,
			&i.WarrantyDays,
			&i.SocialHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutletsForUser = `-- name: ListOutletsForUser :many
SELECT o.id, o.tenant_id, o.name, o.address, o.phone, o.is_active, o.created_at,
       o.timezone, o.business_day_start, o.receipt_footer, o.warranty_days, o.social_handle
FROM outlets o
JOIN user_outlet_assignments uoa ON uoa.outlet_id = o.id
WHERE uoa.tenant_id = $1 AND uoa.user_id = $2
ORDER BY uoa.is_primary DESC, o.created_at ASC
`

type ListOutletsForUserParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	UserID   string `db:"user_id" json:"user_id"`
}

type ListOutletsForUserRow struct {
	ID               string             `db:"id" json:"id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	Name             string             `db:"name" json:"name"`
	Address          *string            `db:"address" json:"address"`
	Phone            *string            `db:"phone" json:"phone"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Timezone         string             `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time        `db:"business_day_start" json:"business_day_start"`
	ReceiptFooter    *string            `db:"receipt_footer" json:"receipt_footer"`
	WarrantyDays     int16              `db:"warranty_days" json:"warranty_days"`
	SocialHandle     *string            `db:"social_handle" json:"social_handle"`
}

// MULTI-OUTLET.md §3: "Ini adalah celah keamanan, bukan fitur Fase 2" — tanpa
// ini, GET /outlets mengembalikan SELURUH outlet tenant ke siapa pun yang
// login, termasuk kasir yang seharusnya hanya melihat cabang tempat ia
// ditugaskan. Seeder (internal/seed) sudah menugaskan owner/manager ke
// SELURUH outlet dan kasir hanya ke outlet utama, jadi join ini otomatis
// benar untuk semua peran tanpa cabang kasus khusus di kode Go.
func (q *Queries) ListOutletsForUser(ctx context.Context, arg ListOutletsForUserParams) ([]ListOutletsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOutletsForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutletsForUserRow{}
	for rows.Next() {
		var i ListOutletsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.Timezone,
			&i.BusinessDayStart,
			&i.ReceiptFooter,
			&i.WarrantyDays,
			&i.SocialHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutlet = `-- name: UpdateOutlet :execrows
UPDATE outlets
SET
    name = COALESCE($3, name),
    address = COALESCE($4, address),
    phone = COALESCE($5, phone),
    timezone = COALESCE($6, timezone),
    business_day_start = COALESCE($7, business_day_start),
    is_active = COALESCE($8, is_active),
    receipt_footer = COALESCE($9, receipt_footer),
    warranty_days = COALESCE($10, warranty_days),
    social_handle = COALESCE($11, social_handle)
WHERE tenant_id = $1 AND id = $2
`

type UpdateOutletParams struct {
	TenantID         string      `db:"tenant_id" json:"tenant_id"`
	ID               string      `db:"id" json:"id"`
	Name             *string     `db:"name" json:"name"`
	Address          *string     `db:"address" json:"address"`
	Phone            *string     `db:"phone" json:"phone"`
	Timezone         *string     `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time `db:"business_day_start" json:"business_day_start"`
	IsActive         *bool       `db:"is_active" json:"is_active"`
	ReceiptFooter    *string     `db:"receipt_footer" json:"receipt_footer"`
	WarrantyDays     *int16      `db:"warranty_days" json:"warranty_days"`
	SocialHandle     *string     `db:"social_handle" json:"social_handle"`
}

// :execrows, bukan :exec — id yang salah atau milik tenant lain harus
// menjadi 404, bukan "Outlet diupdate" yang tidak mengubah apa pun.
func (q *Queries) UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOutlet,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Timezone,
		arg.BusinessDayStart,
		arg.IsActive,
		arg.ReceiptFooter,
		arg.WarrantyDays,
		arg.SocialHandle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
