// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outlet.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutlet = `-- name: InsertOutlet :one
INSERT INTO outlets (id, tenant_id, name, address, phone, timezone, business_day_start)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, address, phone, is_active, created_at, timezone, business_day_start
`

type InsertOutletParams struct {
	ID               string      `db:"id" json:"id"`
	TenantID         string      `db:"tenant_id" json:"tenant_id"`
	Name             string      `db:"name" json:"name"`
	Address          *string     `db:"address" json:"address"`
	Phone            *string     `db:"phone" json:"phone"`
	Timezone         string      `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time `db:"business_day_start" json:"business_day_start"`
}

type InsertOutletRow struct {
	ID               string             `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Address          *string            `db:"address" json:"address"`
	Phone            *string            `db:"phone" json:"phone"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Timezone         string             `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time        `db:"business_day_start" json:"business_day_start"`
}

func (q *Queries) InsertOutlet(ctx context.Context, arg InsertOutletParams) (InsertOutletRow, error) {
	row := q.db.QueryRow(ctx, insertOutlet,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Timezone,
		arg.BusinessDayStart,
	)
	var i InsertOutletRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.Timezone,
		&i.BusinessDayStart,
	)
	return i, err
}

const listOutlets = `-- name: ListOutlets :many
SELECT id, tenant_id, name, address, phone, is_active, created_at, timezone, business_day_start
FROM outlets
WHERE tenant_id = $1
ORDER BY created_at ASC
`

type ListOutletsRow struct {
	ID               string             `db:"id" json:"id"`
	TenantID         string             `db:"tenant_id" json:"tenant_id"`
	Name             string             `db:"name" json:"name"`
	Address          *string            `db:"address" json:"address"`
	Phone            *string            `db:"phone" json:"phone"`
	IsActive         bool               `db:"is_active" json:"is_active"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Timezone         string             `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time        `db:"business_day_start" json:"business_day_start"`
}

func (q *Queries) ListOutlets(ctx context.Context, tenantID string) ([]ListOutletsRow, error) {
	rows, err := q.db.Query(ctx, listOutlets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutletsRow{}
	for rows.Next() {
		var i ListOutletsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.Timezone,
			&i.BusinessDayStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutlet = `-- name: UpdateOutlet :exec
UPDATE outlets
SET
    name = COALESCE($3, name),
    address = COALESCE($4, address),
    phone = COALESCE($5, phone),
    timezone = COALESCE($6, timezone),
    business_day_start = COALESCE($7, business_day_start),
    is_active = COALESCE($8, is_active)
WHERE tenant_id = $1 AND id = $2
`

type UpdateOutletParams struct {
	TenantID         string      `db:"tenant_id" json:"tenant_id"`
	ID               string      `db:"id" json:"id"`
	Name             *string     `db:"name" json:"name"`
	Address          *string     `db:"address" json:"address"`
	Phone            *string     `db:"phone" json:"phone"`
	Timezone         *string     `db:"timezone" json:"timezone"`
	BusinessDayStart pgtype.Time `db:"business_day_start" json:"business_day_start"`
	IsActive         *bool       `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateOutlet(ctx context.Context, arg UpdateOutletParams) error {
	_, err := q.db.Exec(ctx, updateOutlet,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Timezone,
		arg.BusinessDayStart,
		arg.IsActive,
	)
	return err
}
