// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_nota.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getPublicNota = `-- name: GetPublicNota :one

SELECT
    s.id, s.receipt_number, s.grand_total, s.payment_status,
    COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at)::timestamptz AS sold_at,
    (s.customer_id IS NOT NULL)::BOOLEAN AS has_member,
    -- Kartu member untuk halaman nota (opsi tanpa login). NULL bila nota ini
    -- bukan atas nama member. ` + "`" + `merchandise_given` + "`" + ` tidak tercetak di kertas,
    -- tetapi ia hanya menjawab "apakah merchandise perdana sudah diambil"
    -- untuk member yang notanya sedang dipegang — tidak membuka riwayat
    -- belanja apa pun.
    cust.member_code,
    cust.name AS member_name,
    (cust.merchandise_given_at IS NOT NULL)::BOOLEAN AS member_merchandise_given,
    EXISTS (
        SELECT 1 FROM refunds r WHERE r.tenant_id = s.tenant_id AND r.transaction_id = s.id
    )::BOOLEAN AS refunded,
    EXISTS (
        SELECT 1 FROM customers c WHERE c.tenant_id = s.tenant_id AND c.signup_sale_id = s.id
    )::BOOLEAN AS signup_used,
    o.name AS outlet_name, o.address AS outlet_address, o.phone AS outlet_phone,
    o.warranty_days, o.social_handle, o.timezone
FROM sales_transactions s
JOIN outlets o ON o.id = s.outlet_id AND o.tenant_id = s.tenant_id
LEFT JOIN LATERAL (
    SELECT c.member_code, c.name, c.merchandise_given_at
    FROM customers c
    WHERE c.tenant_id = s.tenant_id
      AND c.is_active
      AND c.merged_into_id IS NULL
      AND (c.id = s.customer_id OR c.signup_sale_id = s.id)
    ORDER BY (c.id = s.customer_id) DESC
    LIMIT 1
) cust ON TRUE
WHERE s.tenant_id = $1 AND s.id = $2 AND NOT s.is_sandbox
`

type GetPublicNotaParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type GetPublicNotaRow struct {
	ID                     string             `db:"id" json:"id"`
	ReceiptNumber          string             `db:"receipt_number" json:"receipt_number"`
	GrandTotal             decimal.Decimal    `db:"grand_total" json:"grand_total"`
	PaymentStatus          string             `db:"payment_status" json:"payment_status"`
	SoldAt                 pgtype.Timestamptz `db:"sold_at" json:"sold_at"`
	HasMember              bool               `db:"has_member" json:"has_member"`
	MemberCode             *string            `db:"member_code" json:"member_code"`
	MemberName             *string            `db:"member_name" json:"member_name"`
	MemberMerchandiseGiven bool               `db:"member_merchandise_given" json:"member_merchandise_given"`
	Refunded               bool               `db:"refunded" json:"refunded"`
	SignupUsed             bool               `db:"signup_used" json:"signup_used"`
	OutletName             string             `db:"outlet_name" json:"outlet_name"`
	OutletAddress          *string            `db:"outlet_address" json:"outlet_address"`
	OutletPhone            *string            `db:"outlet_phone" json:"outlet_phone"`
	WarrantyDays           int16              `db:"warranty_days" json:"warranty_days"`
	SocialHandle           *string            `db:"social_handle" json:"social_handle"`
	Timezone               string             `db:"timezone" json:"timezone"`
}

// Halaman nota publik (ADR-0013). Dibaca TANPA login oleh server web toko,
// berbekal (tenant_id, id nota) dari QR di nota. Aturan emas tetap berlaku:
// setiap kueri memfilter tenant_id — id nota saja TIDAK cukup.
//
// Yang boleh keluar dari sini: data toko, isi nota, dan APA YANG SUDAH
// TERCETAK DI KERTAS NOTA ITU SENDIRI. Yang TIDAK: kasir, HPP, riwayat
// belanja, nomor WhatsApp, atau apa pun milik nota lain.
//
// Batas "sudah tercetak di kertas" itu yang mengizinkan kode & nama member
// ikut keluar (lihat GetPublicNota): nota member mencetak
// "Member M-XXXXXX (Nama)" beserta barcode CODE128-nya (escpos.ts), jadi
// siapa pun yang bisa menyusun URL ini SUDAH memegang kertas yang memuat
// keduanya. Nomor WA TIDAK pernah tercetak, dan karena itu tidak pernah
// dikembalikan — meski ia kolom yang bersebelahan di tabel yang sama.
// Member yang terkait nota ini, lewat DUA jalan yang keduanya berarti
// "orang yang memegang kertas ini":
//  1. kasir menempelkan member saat checkout  → s.customer_id
//  2. ia mendaftar DARI nota ini di halaman publik → signup_sale_id
//
// Jalan kedua wajib ada: pendaftaran lewat nota TIDAK mengisi customer_id
// nota itu, jadi tanpa ini kartu member justru tidak pernah muncul bagi
// orang yang baru saja mendaftar — satu-satunya saat ia paling ingin
// menyimpan kodenya.
//
// Keduanya tidak bisa terisi sekaligus: nota yang sudah atas nama member
// tidak pernah boleh dipakai mendaftar (bolehDaftar di public_nota.go),
// dan LIMIT 1 membuat hasilnya tetap deterministik bila kelak berubah.
func (q *Queries) GetPublicNota(ctx context.Context, arg GetPublicNotaParams) (GetPublicNotaRow, error) {
	row := q.db.QueryRow(ctx, getPublicNota, arg.TenantID, arg.ID)
	var i GetPublicNotaRow
	err := row.Scan(
		&i.ID,
		&i.ReceiptNumber,
		&i.GrandTotal,
		&i.PaymentStatus,
		&i.SoldAt,
		&i.HasMember,
		&i.MemberCode,
		&i.MemberName,
		&i.MemberMerchandiseGiven,
		&i.Refunded,
		&i.SignupUsed,
		&i.OutletName,
		&i.OutletAddress,
		&i.OutletPhone,
		&i.WarrantyDays,
		&i.SocialHandle,
		&i.Timezone,
	)
	return i, err
}

const insertCustomerFromNota = `-- name: InsertCustomerFromNota :execrows
INSERT INTO customers (
    id, tenant_id, name, phone, member_code, social_handle, follows_store_social,
    first_seen_at, signup_sale_id
) VALUES (
    $1, $2, $6, $3, $4, $7, TRUE, now(), $5
)
`

type InsertCustomerFromNotaParams struct {
	ID           string  `db:"id" json:"id"`
	TenantID     string  `db:"tenant_id" json:"tenant_id"`
	Phone        *string `db:"phone" json:"phone"`
	MemberCode   *string `db:"member_code" json:"member_code"`
	SignupSaleID *string `db:"signup_sale_id" json:"signup_sale_id"`
	Name         *string `db:"name" json:"name"`
	SocialHandle *string `db:"social_handle" json:"social_handle"`
}

// Satu pendaftaran per nota ditegakkan idx_customers_signup_sale; nomor WA
// yang sudah terdaftar ditolak idx_customers_phone. Keduanya galat 23505
// yang dibedakan dari nama constraint-nya.
func (q *Queries) InsertCustomerFromNota(ctx context.Context, arg InsertCustomerFromNotaParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCustomerFromNota,
		arg.ID,
		arg.TenantID,
		arg.Phone,
		arg.MemberCode,
		arg.SignupSaleID,
		arg.Name,
		arg.SocialHandle,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPublicNotaItems = `-- name: ListPublicNotaItems :many
SELECT p.name AS product_name, v.name AS variant_name, si.quantity, si.uom, si.subtotal
FROM sales_items si
JOIN variants v ON v.id = si.variant_id AND v.tenant_id = si.tenant_id
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
WHERE si.tenant_id = $1 AND si.transaction_id = $2
ORDER BY si.id
LIMIT 200
`

type ListPublicNotaItemsParams struct {
	TenantID      string `db:"tenant_id" json:"tenant_id"`
	TransactionID string `db:"transaction_id" json:"transaction_id"`
}

type ListPublicNotaItemsRow struct {
	ProductName string          `db:"product_name" json:"product_name"`
	VariantName string          `db:"variant_name" json:"variant_name"`
	Quantity    decimal.Decimal `db:"quantity" json:"quantity"`
	Uom         string          `db:"uom" json:"uom"`
	Subtotal    decimal.Decimal `db:"subtotal" json:"subtotal"`
}

func (q *Queries) ListPublicNotaItems(ctx context.Context, arg ListPublicNotaItemsParams) ([]ListPublicNotaItemsRow, error) {
	rows, err := q.db.Query(ctx, listPublicNotaItems, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicNotaItemsRow{}
	for rows.Next() {
		var i ListPublicNotaItemsRow
		if err := rows.Scan(
			&i.ProductName,
			&i.VariantName,
			&i.Quantity,
			&i.Uom,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
