// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

type Querier interface {
	// Stok masuk / barang rusak / koreksi opname dari layar Stok.
	//
	// UPDATE tunggal ini sudah atomik dan mengambil kunci baris (alasan yang sama
	// dengan DecrementStockStrict di checkout.sql). `delta` BERTANDA: positif
	// menambah, negatif mengurangi, dan dihitung dalam SATUAN STOK (gram untuk
	// bibit, ADR-0012).
	//
	// Jasa dan sewa (item_type lain) sengaja tidak punya stok, jadi 0 baris
	// kembali = varian tidak ada, milik tenant lain, atau tidak berstok.
	AdjustStock(ctx context.Context, arg AdjustStockParams) (decimal.Decimal, error)
	// expected = saldo awal + tunai masuk + kas masuk − kas keluar.
	//
	// Transaksi yang tiba TERLAMBAT (is_late_arrival) sengaja DIKECUALIKAN:
	// Z-Report yang sudah dicetak tidak boleh berubah retroaktif, karena kasir
	// sudah menghitung uang fisik dan menandatangani hasilnya. (OFFLINE-SYNC-SPEC §3C)
	CalculateExpectedCash(ctx context.Context, arg CalculateExpectedCashParams) (CalculateExpectedCashRow, error)
	// variance = counted − expected. Negatif maupun positif sama-sama perlu diselidiki.
	//
	// Cast eksplisit ::numeric WAJIB di sini: tanpanya Postgres tidak bisa
	// meng-infer tipe $4/$5 dari ekspresi aritmetika `$5 - $4` walau keduanya
	// juga dipakai di SET lain sebagai kolom numeric — gagal dengan
	// "operator is not unique: unknown - unknown" (ditemukan saat kueri ini
	// benar-benar dijalankan pertama kali, lihat queries/README.md).
	CloseShift(ctx context.Context, arg CloseShiftParams) (CloseShiftRow, error)
	ConvertUom(ctx context.Context, arg ConvertUomParams) (decimal.Decimal, error)
	// Jumlah BARIS barang terjual, bukan penjumlahan kuantitas: menjumlahkan
	// 30 ml dengan 2 botol menghasilkan angka yang tidak berarti apa-apa
	// (alasan yang sama dengan totalItemCount di layar kasir).
	CountReportItems(ctx context.Context, arg CountReportItemsParams) (int32, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (string, error)
	CreateOutlet(ctx context.Context, arg CreateOutletParams) (string, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (string, error)
	// Simpan refresh token (sudah di-hash SHA-256) dengan TTL 7 hari.
	//
	// BUG DITEMUKAN & DIPERBAIKI (3 Sept 2026): daftar kolom sebelumnya menyebut
	// `device_label` DUA KALI (bukan device_label + device_fingerprint yang ada
	// di skema, migrations/00001). Postgres menolak INSERT dengan kolom
	// terduplikasi ("column device_label specified more than once") — setiap
	// login/register/refresh gagal total. Ditemukan lewat `make sqlc-vet` +
	// pembacaan manual, dikonfirmasi lewat login end-to-end nyata setelah
	// diperbaiki, bukan diasumsikan benar dari nama variabel Go.
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Dipakai HANYA oleh seeder untuk mengisi kasus tepi "refund parsial"
	// (TESTING-STRATEGY.md §4). Jalur HTTP /sales/{id}/refund BELUM diimplementasikan
	// sesi ini (lihat CLAUDE.md §7) — kueri ini sengaja tidak dipakai handler mana pun.
	CreateRefund(ctx context.Context, arg CreateRefundParams) (string, error)
	// ═══════════════════════════════════════════════════════════════════════
	//  JALUR UANG — anggaran total p99 < 5ms (PRD §4)
	//
	//  Seluruh kueri di berkas ini berjalan dalam SATU transaksi SQL:
	//
	//    BEGIN
	//      CreateSaleIdempotent      → 0 baris berarti duplikat, bukan error
	//      InsertSalesItems          (copyfrom)
	//      InsertPayment             (per metode bayar; FR-22 split payment)
	//      DecrementStock*           → mengunci baris variants
	//      InsertStockEvents         (copyfrom)
	//      InsertOutboxEvent         → mengatasi masalah dual-write
	//    COMMIT
	//
	//  Urutan penting: stok dikurangi SETELAH transaksi tersimpan, agar kegagalan
	//  stok tidak meninggalkan transaksi yatim.
	// ═══════════════════════════════════════════════════════════════════════
	// HOT PATH. ULID dibuat KLIEN — inilah kunci idempotensi.
	//
	// ON CONFLICT DO NOTHING + RETURNING: bila 0 baris kembali, transaksi ini SUDAH
	// pernah masuk. Itu bukan kegagalan melainkan kelas ACCEPTED
	// (ERROR-CATALOG §4): klien menandainya 'synced' dan melanjutkan.
	//
	// Tanpa perilaku ini, transaksi yang sudah aman di server akan tersangkut
	// selamanya di antrean lokal sampai IndexedDB penuh — satu-satunya jalur
	// menuju "kasir tidak bisa berjualan".
	CreateSaleIdempotent(ctx context.Context, arg CreateSaleIdempotentParams) (CreateSaleIdempotentRow, error)
	// Karyawan baru di tenant yang SUDAH ADA (owner menambah kasir/manager).
	// Berbeda dari RegisterTenantOwner: tenant_id sudah diketahui, jadi kueri
	// ini tetap tunduk pada aturan tenant-scope seperti kueri lain.
	CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (CreateStaffUserRow, error)
	// Kueri untuk cmd/seed SAJA — bukan jalur produksi.
	//
	// Kenapa lewat sqlc, bukan SQL mentah di dalam cmd/seed: supaya seeder memakai
	// Queries yang SAMA dengan handler HTTP. Kalau skema kueri berubah, seeder ikut
	// pecah saat compile — bukan diam-diam menulis data yang sudah tidak sesuai
	// bentuk tabel. (docs/15-development/LOCAL-SETUP.md §4)
	// tenants adalah tabel akar — ia SENDIRI adalah tenant_id, belum ada tenant_id
	// di atasnya untuk difilter.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	CreateUserOutletAssignment(ctx context.Context, arg CreateUserOutletAssignmentParams) error
	CreateVariant(ctx context.Context, arg CreateVariantParams) (string, error)
	// Foreign key hanya menjamin pelanggan ADA, bukan milik tenant yang sama.
	// Tanpa pemeriksaan ini, penjualan tenant A bisa merujuk pelanggan tenant B.
	CustomerBelongsToTenant(ctx context.Context, arg CustomerBelongsToTenantParams) (bool, error)
	// SINKRONISASI OFFLINE. Stok BOLEH menjadi negatif.
	//
	// Barang sudah keluar secara fisik, pelanggan sudah pergi, uang sudah diterima.
	// Menolak sync berarti menghapus penjualan nyata dari catatan.
	// Stok minus adalah INFORMASI ("lakukan opname di sini"), bukan kerusakan data.
	// (OFFLINE-SYNC-SPEC §2 prinsip 3, §3A)
	DecrementStockAllowNegative(ctx context.Context, arg DecrementStockAllowNegativeParams) (decimal.Decimal, error)
	// ── PEMOTONGAN STOK ────────────────────────────────────────────────────
	// Dua kueri berbeda dan itu DISENGAJA. Perbedaannya adalah keputusan produk,
	// bukan detail teknis. (ERROR-CATALOG §5)
	// HOT PATH — checkout ONLINE. Menolak bila stok tidak cukup.
	//
	// UPDATE tunggal ini sudah atomik dan mengambil kunci baris; tidak perlu
	// SELECT ... FOR UPDATE terpisah. Inilah alasan mutex Redis TIDAK dipakai
	// di sini — menambahkan Redis ke jalur ini berarti menambah titik kegagalan
	// pada bagian sistem yang paling tidak boleh gagal. (REDIS-STRATEGY §5)
	//
	// 0 baris kembali → INSUFFICIENT_STOCK (kelas PERMANENT).
	DecrementStockStrict(ctx context.Context, arg DecrementStockStrictParams) (decimal.Decimal, error)
	// Manager/owner yang MENYETUJUI refund kasir (RBAC-MODEL §"Void transaksi":
	// kasir wajib PIN manager). Bukan user yang sedang login — approved_by
	// HARUS identitas manager, bukan kasir menyetujui diri sendiri.
	GetApproverForPin(ctx context.Context, arg GetApproverForPinParams) (GetApproverForPinRow, error)
	GetBomComponents(ctx context.Context, arg GetBomComponentsParams) ([]GetBomComponentsRow, error)
	GetDailySummary(ctx context.Context, tenantID string) (GetDailySummaryRow, error)
	// Ember terpisah invarian §6 #5: transaksi hari itu yang baru tiba SETELAH
	// shift-nya ditutup. Nyata dan sah, tetapi tidak boleh menggeser angka yang
	// sudah dicetak. Pemilik melihatnya sebagai baris tersendiri.
	GetLateArrivalBucket(ctx context.Context, arg GetLateArrivalBucketParams) (GetLateArrivalBucketRow, error)
	// Shift kasir. Kasir tidak bisa bertransaksi tanpa shift terbuka (FR-30).
	// HOT PATH — dipanggil di awal setiap checkout untuk memperoleh shift_id.
	// Memakai indeks unik parsial idx_shifts_one_open.
	GetOpenShift(ctx context.Context, arg GetOpenShiftParams) (GetOpenShiftRow, error)
	// Halaman nota publik (ADR-0013). Dibaca TANPA login oleh server web toko,
	// berbekal (tenant_id, id nota) dari QR di nota. Aturan emas tetap berlaku:
	// setiap kueri memfilter tenant_id — id nota saja TIDAK cukup.
	//
	// Yang boleh keluar dari sini: data toko, isi nota, dan APA YANG SUDAH
	// TERCETAK DI KERTAS NOTA ITU SENDIRI. Yang TIDAK: kasir, HPP, riwayat
	// belanja, nomor WhatsApp, atau apa pun milik nota lain.
	//
	// Batas "sudah tercetak di kertas" itu yang mengizinkan kode & nama member
	// ikut keluar (lihat GetPublicNota): nota member mencetak
	// "Member M-XXXXXX (Nama)" beserta barcode CODE128-nya (escpos.ts), jadi
	// siapa pun yang bisa menyusun URL ini SUDAH memegang kertas yang memuat
	// keduanya. Nomor WA TIDAK pernah tercetak, dan karena itu tidak pernah
	// dikembalikan — meski ia kolom yang bersebelahan di tabel yang sama.
	// Member yang terkait nota ini, lewat DUA jalan yang keduanya berarti
	// "orang yang memegang kertas ini":
	//   1. kasir menempelkan member saat checkout  → s.customer_id
	//   2. ia mendaftar DARI nota ini di halaman publik → signup_sale_id
	// Jalan kedua wajib ada: pendaftaran lewat nota TIDAK mengisi customer_id
	// nota itu, jadi tanpa ini kartu member justru tidak pernah muncul bagi
	// orang yang baru saja mendaftar — satu-satunya saat ia paling ingin
	// menyimpan kodenya.
	//
	// Keduanya tidak bisa terisi sekaligus: nota yang sudah atas nama member
	// tidak pernah boleh dipakai mendaftar (bolehDaftar di public_nota.go),
	// dan LIMIT 1 membuat hasilnya tetap deterministik bila kelak berubah.
	GetPublicNota(ctx context.Context, arg GetPublicNotaParams) (GetPublicNotaRow, error)
	// Verifikasi refresh token. Kembalikan error bila sudah direvokasi atau expired.
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error)
	// Dipakai saat CreateSaleIdempotent mengembalikan 0 baris (idempotency hit,
	// ERROR-CATALOG §B DUPLICATE_TRANSACTION) — klien menerima record yang SUDAH
	// ada, bukan error, persis seperti openapi.yaml POST /sales respons 200.
	GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (GetSaleByIDRow, error)
	GetSaleDetail(ctx context.Context, arg GetSaleDetailParams) (GetSaleDetailRow, error)
	// Dipakai PostRefund untuk menegakkan REFUND_EXCEEDS_TOTAL (ERROR-CATALOG §B)
	// — tanpa ini, refund_total tidak pernah dibandingkan dengan grand_total asli.
	GetSaleForRefund(ctx context.Context, arg GetSaleForRefundParams) (GetSaleForRefundRow, error)
	// Validasi item yang mau di-restock benar-benar milik transaksi ini
	// (mencegah refund_items menunjuk ke sales_item transaksi/tenant lain).
	GetSalesItemForRefund(ctx context.Context, arg GetSalesItemForRefundParams) (GetSalesItemForRefundRow, error)
	// Laporan penjualan harian / tutup buku (Z-Report).
	//
	// DUA aturan yang membentuk seluruh berkas ini:
	//
	//  1. **Waktu laporan = waktu TERKOREKSI perangkat**, bukan waktu server.
	//     `COALESCE(offline_created_at_adj, offline_created_at, created_at)` —
	//     transaksi yang dibuat offline pukul 20.00 lalu terkirim pukul 23.00
	//     milik hari ia terjadi, bukan hari ia sampai. (skema 00005 baris
	//     "Laporan memakai versi terkoreksi; audit memakai yang mentah")
	//
	//  2. **Z-Report yang sudah dicetak tidak pernah berubah** (invarian §6 #5).
	//     Karena itu `is_late_arrival` DIKECUALIKAN dari semua angka utama dan
	//     dilaporkan di embernya sendiri — sama seperti CalculateExpectedCash.
	//     Tanpa pengecualian itu, laporan kemarin yang sudah ditandatangani
	//     kasir bisa berubah sendiri hari ini.
	//
	// `is_sandbox` dikecualikan di mana-mana: data percobaan onboarding tidak
	// pernah masuk laporan mana pun.
	// Angka induk laporan. Void dihitung terpisah — barangnya kembali dan
	// uangnya tidak pernah jadi pendapatan, tetapi pemilik tetap perlu tahu
	// berapa banyak yang dibatalkan hari itu.
	GetSalesReportSummary(ctx context.Context, arg GetSalesReportSummaryParams) (GetSalesReportSummaryRow, error)
	// Satuan tempat stock_quantity dihitung: satuan STOK bila varian punya
	// konversi (bibit: gram), selain itu satuan jual. Dipakai untuk mengisi
	// stock_events.uom — ledger stok tidak boleh menebak satuan.
	GetStockUom(ctx context.Context, arg GetStockUomParams) (string, error)
	// Dipanggil SEBELUM memproses batch. Bila key sudah ada dengan hash body yang
	// sama, kembalikan respons tersimpan apa adanya — klien menerima jawaban
	// identik seperti percobaan pertama.
	GetSyncReceipt(ctx context.Context, arg GetSyncReceiptParams) (GetSyncReceiptRow, error)
	GetTopProducts(ctx context.Context, tenantID string) ([]GetTopProductsRow, error)
	// Kueri autentikasi untuk jalur /auth/*.
	// Dipakai hanya oleh internal/httpapi/auth.go — bukan seeder.
	// Lookup user berdasarkan email untuk login. Hanya user aktif.
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	// sqlc-vet-disable: wajib-tenant-scope
	// Lookup user untuk login TANPA tenant_id. Dikecualikan dari aturan
	// wajib-tenant-scope dengan alasan yang sama seperti RegisterTenantOwner:
	// login adalah operasi SEBELUM tenant diketahui — memaksa pemanggil menyebut
	// tenant_id berarti pemilik warung harus menghafal ULID 26 karakter, dan
	// kehilangan string itu mengunci dia keluar dari datanya sendiri.
	//
	// Aman karena `idx_users_email` UNIQUE global (00001_foundation.sql:45): satu
	// email hanya pernah menunjuk satu user, jadi tenant_id hasilnya deterministik
	// dan tidak bisa ditebak-tebak oleh pemanggil. Setelah baris ini didapat,
	// seluruh kueri berikutnya tetap memfilter tenant_id dari hasil di sini —
	// bukan dari input klien, yang justru lebih ketat daripada sebelumnya.
	GetUserByEmailGlobal(ctx context.Context, email string) (GetUserByEmailGlobalRow, error)
	// Verifikasi password SEBELUM mengubah PIN sendiri. Password diminta lagi
	// meski sesi sudah hidup, dan itu disengaja: PIN inilah yang kelak dipakai
	// menyetujui refund TANPA login. Siapa pun yang menemukan ponsel manager
	// dalam keadaan terbuka tidak boleh bisa menanam PIN miliknya sendiri.
	GetUserForPinChange(ctx context.Context, arg GetUserForPinChangeParams) (GetUserForPinChangeRow, error)
	// Setelah login sukses, ambil info tenant untuk disertakan dalam JWT claims.
	GetUserWithTenant(ctx context.Context, id string) (GetUserWithTenantRow, error)
	// Satuan jual + konversi ke satuan stok, TANPA filter is_active: void atau
	// refund atas barang yang sudah dinonaktifkan tetap harus mengembalikan stok
	// dalam satuan yang benar.
	GetVariantConversion(ctx context.Context, arg GetVariantConversionParams) (GetVariantConversionRow, error)
	// Isian layar "Ubah barang". Termasuk HPP, yang SENGAJA tidak ikut
	// /sync/pull: margin usaha adalah informasi paling sensitif bagi pemilik
	// UMKM (SECURITY.md §3), dan apa pun yang disinkronkan ikut tersimpan di
	// IndexedDB setiap ponsel kasir — yang hanya dijaga kunci layar ponsel
	// (lihat lib/auth/access.ts). Pemanggil WAJIB menyaringnya per peran.
	GetVariantDetail(ctx context.Context, arg GetVariantDetailParams) (GetVariantDetailRow, error)
	GetVariantForCheckout(ctx context.Context, arg GetVariantForCheckoutParams) (GetVariantForCheckoutRow, error)
	// Kebalikan DecrementStockAllowNegative — barang fisik kembali ke rak.
	// item_type dibatasi sama seperti pemotongan stok checkout.
	IncrementStockForRefund(ctx context.Context, arg IncrementStockForRefundParams) (decimal.Decimal, error)
	// SECURITY §6 — append-only. Setiap aksi sensitif: void, diskon manual,
	// buka laci tanpa transaksi, akses break-glass platform admin.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) (string, error)
	// Satu pendaftaran per nota ditegakkan idx_customers_signup_sale; nomor WA
	// yang sudah terdaftar ditolak idx_customers_phone. Keduanya galat 23505
	// yang dibedakan dari nama constraint-nya.
	InsertCustomerFromNota(ctx context.Context, arg InsertCustomerFromNotaParams) (int64, error)
	// Member didaftarkan di PERANGKAT (bisa offline) dengan ULID klien — id
	// adalah kunci idempotensi: kiriman ulang yang sama menghasilkan 0 baris
	// (duplicate), bukan galat. Tabrakan nomor WA / kode member tetap galat
	// unik (idx_customers_phone / idx_customers_member_code) dan DITOLAK.
	InsertCustomerFromSync(ctx context.Context, arg InsertCustomerFromSyncParams) (int64, error)
	// Ditulis dalam TRANSAKSI YANG SAMA dengan penjualan.
	//
	// Postgres dan Redis tidak berbagi transaksi: bila Redis mati setelah COMMIT,
	// event akan hilang tanpa cara mendeteksinya. Outbox memindahkan penerbitan
	// ke proses terpisah, sehingga Redis boleh mati tanpa menghentikan kasir.
	// (EVENT-ARCHITECTURE §5)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (string, error)
	InsertOutlet(ctx context.Context, arg InsertOutletParams) (InsertOutletRow, error)
	// FR-22: satu transaksi boleh punya beberapa baris (Rp 20.000 tunai + Rp 30.000 QRIS).
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (string, error)
	InsertRefund(ctx context.Context, arg InsertRefundParams) (string, error)
	InsertRefundItem(ctx context.Context, arg InsertRefundItemParams) (string, error)
	// HOT PATH. quantity DECIMAL(14,3) — 0,25 kg tepung · 30 ml parfum.
	// unit_price & unit_cost DISALIN saat transaksi: laporan tidak pernah
	// menghitung ulang memakai harga sekarang.
	InsertSalesItems(ctx context.Context, arg []InsertSalesItemsParams) (int64, error)
	InsertStockEvent(ctx context.Context, arg InsertStockEventParams) (string, error)
	// Ledger append-only. variants.stock_quantity hanyalah cache;
	// KEBENARAN stok ada di tabel ini. (DATA-MODEL §4C)
	InsertStockEvents(ctx context.Context, arg []InsertStockEventsParams) (int64, error)
	InsertStockOpname(ctx context.Context, arg InsertStockOpnameParams) (string, error)
	InsertStockOpnameItem(ctx context.Context, arg InsertStockOpnameItemParams) (InsertStockOpnameItemRow, error)
	// Konversi satuan jual → satuan stok (ADR-0012): bibit dijual per ml,
	// stoknya gram. from_uom diambil dari varian itu sendiri supaya tidak
	// mungkin menyimpan konversi yang tidak akan pernah terpakai.
	InsertUomConversion(ctx context.Context, arg InsertUomConversionParams) (int64, error)
	// Siapa yang bisa dimintai PIN saat kasir perlu persetujuan (refund, void,
	// diskon besar). Hanya nama & peran — TIDAK ADA pin_hash di sini; daftar ini
	// dikirim ke perangkat kasir, dan hash PIN tidak boleh ikut keluar dari
	// server dalam keadaan apa pun.
	//
	// Manager yang BELUM mengatur PIN tetap ditampilkan, ditandai lewat
	// `punya_pin`: kasir yang memanggil manajer ke kasir lalu menemukan PIN-nya
	// belum ada akan menyalahkan aplikasi, bukan pengaturan akunnya.
	ListApprovers(ctx context.Context, tenantID string) ([]ListApproversRow, error)
	ListCatalogForSync(ctx context.Context, arg ListCatalogForSyncParams) ([]ListCatalogForSyncRow, error)
	// Yang dikirim ke perangkat kasir HANYA nama, WA, kode member, akun sosial
	// media, dan status merchandise — bukan email/tanggal lahir/catatan
	// (DATA-MODEL §5 "jangan simpan email & tanggal lahir di perangkat").
	ListCustomersForSync(ctx context.Context, tenantID string) ([]ListCustomersForSyncRow, error)
	// Daftar member untuk layar /member. Berbeda dari ListCustomersForSync:
	// yang ini dibaca pemilik di satu layar (bukan dicermin ke tiap perangkat),
	// jadi ia boleh mencari, menghitung belanja, dan dibatasi halaman.
	//
	// Email & tanggal lahir TETAP tidak ikut — bukan karena perangkat, tetapi
	// karena tidak ada satu pun fitur yang memakainya (DATA-MODEL §5). Kolom
	// yang tidak pernah dibaca lebih baik tidak pernah dikirim.
	ListMembers(ctx context.Context, arg ListMembersParams) ([]ListMembersRow, error)
	ListOutlets(ctx context.Context, tenantID string) ([]ListOutletsRow, error)
	// MULTI-OUTLET.md §3: "Ini adalah celah keamanan, bukan fitur Fase 2" — tanpa
	// ini, GET /outlets mengembalikan SELURUH outlet tenant ke siapa pun yang
	// login, termasuk kasir yang seharusnya hanya melihat cabang tempat ia
	// ditugaskan. Seeder (internal/seed) sudah menugaskan owner/manager ke
	// SELURUH outlet dan kasir hanya ke outlet utama, jadi join ini otomatis
	// benar untuk semua peran tanpa cabang kasus khusus di kode Go.
	ListOutletsForUser(ctx context.Context, arg ListOutletsForUserParams) ([]ListOutletsForUserRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListPublicNotaItems(ctx context.Context, arg ListPublicNotaItemsParams) ([]ListPublicNotaItemsRow, error)
	ListSaleItems(ctx context.Context, arg ListSaleItemsParams) ([]ListSaleItemsRow, error)
	ListSalePayments(ctx context.Context, arg ListSalePaymentsParams) ([]ListSalePaymentsRow, error)
	ListSaleRefunds(ctx context.Context, arg ListSaleRefundsParams) ([]ListSaleRefundsRow, error)
	// Riwayat transaksi: mencari nota lama untuk klaim garansi, refund, dan void.
	// Semua kueri memfilter tenant_id; pemanggilnya juga membatasi outlet.
	// Daftar transaksi terbaru dengan total refund yang sudah pernah terjadi,
	// supaya layar riwayat bisa menandai "sudah direfund" tanpa N+1 kueri.
	// Data percobaan (is_sandbox) dikecualikan, sama seperti seluruh laporan.
	ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error)
	// Satu baris per shift: siapa kasirnya, berapa kas diharapkan, berapa yang
	// dihitung, dan selisihnya. Shift yang MASIH TERBUKA ikut tampil dengan
	// nilai kosong — pemilik perlu tahu laporannya belum final.
	ListShiftsForReport(ctx context.Context, arg ListShiftsForReportParams) ([]ListShiftsForReportRow, error)
	// Daftar karyawan untuk layar Pengaturan. TIDAK menyertakan password_hash
	// maupun pin_hash — keduanya tidak pernah keluar dari server.
	ListStaff(ctx context.Context, tenantID string) ([]ListStaffRow, error)
	// Laporan pergerakan stok (ledger append-only = KEBENARAN stok, DATA-MODEL
	// §4C). Dipakai pemilik untuk melihat stok keluar bibit dalam gram.
	ListStockEvents(ctx context.Context, arg ListStockEventsParams) ([]ListStockEventsRow, error)
	// `uom` di sini adalah satuan STOK (satuan tempat stock_quantity dihitung):
	// gram untuk bibit yang dijual per ml (ADR-0012), selain itu satuan jual.
	ListStockLevels(ctx context.Context, tenantID string) ([]ListStockLevelsRow, error)
	// Barang terlaris periode ini, dalam SATUAN JUAL (ml untuk bibit) — ini
	// laporan penjualan, bukan laporan stok. Pergerakan gram ada di
	// /laporan-stok yang membaca ledger stock_events.
	ListTopProductsForReport(ctx context.Context, arg ListTopProductsForReportParams) ([]ListTopProductsForReportRow, error)
	// Opname: baca stok tersimpan sambil mengunci barisnya. Selisih dihitung dari
	// angka INI, bukan dari angka yang dikirim klien — angka klien bisa basi
	// (dibaca sebelum penjualan terakhir) atau dipalsukan.
	LockVariantStock(ctx context.Context, arg LockVariantStockParams) (decimal.Decimal, error)
	// Satu member dari kode ATAU nomor WA, untuk layar kasir.
	//
	// Endpoint ini ada karena cermin lokal perangkat hanya diperbarui saat
	// /sync/pull. Member yang baru mendaftar sendiri lewat QR nota di web toko
	// ada di SERVER, bukan di antrean perangkat — jadi kasir yang mengetik
	// kodenya lima menit kemudian tidak menemukan siapa pun, dan pelanggan yang
	// baru saja mendaftar ditolak di meja kasir.
	//
	// Kolomnya PERSIS sama dengan ListCustomersForSync: tidak ada riwayat
	// belanja, email, atau tanggal lahir. Kasir boleh mengenali member, bukan
	// membaca berapa uang yang pernah ia belanjakan (RBAC-MODEL §CRM).
	LookupMember(ctx context.Context, arg LookupMemberParams) (LookupMemberRow, error)
	LookupVariantByBarcode(ctx context.Context, arg LookupVariantByBarcodeParams) (LookupVariantByBarcodeRow, error)
	// Dipanggil di transaksi penjualan yang sama. merchandise_given_at hanya
	// diisi SEKALI — pada transaksi pertama member — dan tidak pernah ditimpa.
	// Mengembalikan apakah transaksi ini yang pertama.
	MarkCustomerPurchase(ctx context.Context, arg MarkCustomerPurchaseParams) (bool, error)
	// Indeks unik parsial mencegah dua shift terbuka untuk kasir yang sama.
	// Bila terjadi konflik, itu bug klien — bukan kondisi yang perlu ditangani diam-diam.
	OpenShift(ctx context.Context, arg OpenShiftParams) (OpenShiftRow, error)
	// Foreign key hanya menjamin outlet ADA. Tanpa ini, mutasi stok tenant A bisa
	// dicatat atas outlet tenant B.
	OutletBelongsToTenant(ctx context.Context, arg OutletBelongsToTenantParams) (bool, error)
	// FR-31 petty cash — mempengaruhi perhitungan expected_cash di atas.
	RecordCashMovement(ctx context.Context, arg RecordCashMovementParams) (RecordCashMovementRow, error)
	// sqlc-vet-disable: wajib-tenant-scope
	// Buat tenant baru + user owner sekaligus dalam satu transaksi (dipanggil
	// dari handler POST /auth/register). Query ini hanya untuk registrasi awal —
	// tenant_id belum ada, jadi dikecualikan dari aturan wajib-tenant-scope.
	RegisterTenantOwner(ctx context.Context, arg RegisterTenantOwnerParams) (string, error)
	// Revoke semua token aktif milik user (logout-all / compromised account).
	RevokeAllUserTokens(ctx context.Context, arg RevokeAllUserTokensParams) error
	// Revoke satu token spesifik (logout atau rotate). tenant_id sebagai
	// parameter WAJIB (SECURITY.md §2B "Aturan Emas SQL") meski token_hash
	// sendiri unik secara global — pertahanan berlapis, bukan cuma soal
	// tereksploitasi atau tidak.
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	// Retensi 7 hari; dibersihkan job harian. (RETENTION §2)
	SaveSyncReceipt(ctx context.Context, arg SaveSyncReceiptParams) error
	SearchVariants(ctx context.Context, arg SearchVariantsParams) ([]SearchVariantsRow, error)
	// Karyawan yang berhenti DINONAKTIFKAN, tidak dihapus: transaksi, refund,
	// dan ledger stok yang ia catat tetap merujuk namanya. Owner tidak bisa
	// menonaktifkan dirinya sendiri (dicegah di handler) — tenant tanpa satu
	// pun akun aktif tidak bisa dibuka siapa pun lagi.
	SetStaffActive(ctx context.Context, arg SetStaffActiveParams) (int64, error)
	// Opname: stok DITETAPKAN sama dengan hasil timbang, bukan ditambah.
	SetStock(ctx context.Context, arg SetStockParams) (decimal.Decimal, error)
	// Hanya untuk DIRI SENDIRI (pemanggil mengirim id dari klaim JWT-nya).
	// NULL = PIN dihapus; manager itu tidak bisa menyetujui apa pun lagi.
	SetUserPin(ctx context.Context, arg SetUserPinParams) (int64, error)
	// Kas masuk/keluar di luar penjualan (FR-31 petty cash): ambil uang belanja,
	// setor ke bank. Tanpa ini, selisih laci tidak pernah bisa dijelaskan.
	SumCashMovementsForReport(ctx context.Context, arg SumCashMovementsForReportParams) (SumCashMovementsForReportRow, error)
	// Rincian per metode bayar. Inilah yang dicocokkan pemilik dengan isi laci
	// (tunai) dan mutasi rekening (transfer/QRIS).
	SumPaymentsByMethodForReport(ctx context.Context, arg SumPaymentsByMethodForReportParams) ([]SumPaymentsByMethodForReportRow, error)
	// Refund dihitung dari TANGGAL REFUND-nya, bukan tanggal transaksi aslinya:
	// uang keluar dari laci hari ini, jadi ia mengurangi kas hari ini. Nota
	// yang direfund bisa saja terbit minggu lalu.
	SumRefundsForReport(ctx context.Context, arg SumRefundsForReportParams) (SumRefundsForReportRow, error)
	// Refund SEBELUMNYA pada transaksi yang sama — dijumlahkan dengan permintaan
	// baru lewat money.RemainingRefundable sebelum refund ini disimpan.
	SumRefundsForTransaction(ctx context.Context, arg SumRefundsForTransactionParams) (decimal.Decimal, error)
	// Ringkasan per jenis + satuan: "terjual 412,5 g" dalam satu baris, tanpa
	// menjumlahkan gram dengan pcs.
	SumStockEventsByType(ctx context.Context, arg SumStockEventsByTypeParams) ([]SumStockEventsByTypeRow, error)
	// Koreksi data member dari layar /member. Nomor WA IKUT bisa diperbaiki —
	// salah ketik satu digit berarti pengingat WA kelak sampai ke orang lain.
	// Kode member TIDAK pernah diubah: barcodenya sudah tercetak di nota yang
	// dipegang pelanggan.
	UpdateMember(ctx context.Context, arg UpdateMemberParams) (int64, error)
	// :execrows, bukan :exec — id yang salah atau milik tenant lain harus
	// menjadi 404, bukan "Outlet diupdate" yang tidak mengubah apa pun.
	UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (int64, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error)
	// HANYA faktornya. `to_uom` tidak pernah diubah lewat sini: seluruh ledger
	// stock_events barang ini sudah tercatat dalam satuan itu, dan menggantinya
	// membuat gram dan mililiter berjumlah di kolom yang sama tanpa satu pun
	// baris yang terlihat salah.
	UpdateUomConversionFactor(ctx context.Context, arg UpdateUomConversionFactorParams) (int64, error)
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) (int64, error)
	// Telemetri perangkat ikut bersama sync. storage_used_pct adalah peringatan dini
	// sebelum IndexedDB penuh — server bisa tampak sehat sempurna sementara sebuah
	// perangkat kasir mendekati kegagalan total. (OBSERVABILITY §3)
	UpsertDeviceSyncState(ctx context.Context, arg UpsertDeviceSyncStateParams) error
	// Pembatalan hanya untuk transaksi yang MASIH lunas dan shift-nya terbuka;
	// 0 baris = sudah void, sudah tutup shift, atau bukan milik tenant ini.
	VoidSale(ctx context.Context, arg VoidSaleParams) (int64, error)
	// ── VOID & IDEMPOTENSI ─────────────────────────────────────────────────
	// Hanya transaksi 'paid' yang bisa di-void; mencoba void dua kali
	// mengembalikan 0 baris → TRANSACTION_ALREADY_VOIDED (kelas PERMANENT).
	VoidTransaction(ctx context.Context, arg VoidTransactionParams) (VoidTransactionRow, error)
}

var _ Querier = (*Queries)(nil)
