// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

type Querier interface {
	// expected = saldo awal + tunai masuk + kas masuk − kas keluar.
	//
	// Transaksi yang tiba TERLAMBAT (is_late_arrival) sengaja DIKECUALIKAN:
	// Z-Report yang sudah dicetak tidak boleh berubah retroaktif, karena kasir
	// sudah menghitung uang fisik dan menandatangani hasilnya. (OFFLINE-SYNC-SPEC §3C)
	CalculateExpectedCash(ctx context.Context, arg CalculateExpectedCashParams) (CalculateExpectedCashRow, error)
	// variance = counted − expected. Negatif maupun positif sama-sama perlu diselidiki.
	//
	// Cast eksplisit ::numeric WAJIB di sini: tanpanya Postgres tidak bisa
	// meng-infer tipe $4/$5 dari ekspresi aritmetika `$5 - $4` walau keduanya
	// juga dipakai di SET lain sebagai kolom numeric — gagal dengan
	// "operator is not unique: unknown - unknown" (ditemukan saat kueri ini
	// benar-benar dijalankan pertama kali, lihat queries/README.md).
	CloseShift(ctx context.Context, arg CloseShiftParams) (CloseShiftRow, error)
	ConvertUom(ctx context.Context, arg ConvertUomParams) (decimal.Decimal, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (string, error)
	CreateOutlet(ctx context.Context, arg CreateOutletParams) (string, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (string, error)
	// Simpan refresh token (sudah di-hash SHA-256) dengan TTL 7 hari.
	//
	// BUG DITEMUKAN & DIPERBAIKI (3 Sept 2026): daftar kolom sebelumnya menyebut
	// `device_label` DUA KALI (bukan device_label + device_fingerprint yang ada
	// di skema, migrations/00001). Postgres menolak INSERT dengan kolom
	// terduplikasi ("column device_label specified more than once") — setiap
	// login/register/refresh gagal total. Ditemukan lewat `make sqlc-vet` +
	// pembacaan manual, dikonfirmasi lewat login end-to-end nyata setelah
	// diperbaiki, bukan diasumsikan benar dari nama variabel Go.
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	// Dipakai HANYA oleh seeder untuk mengisi kasus tepi "refund parsial"
	// (TESTING-STRATEGY.md §4). Jalur HTTP /sales/{id}/refund BELUM diimplementasikan
	// sesi ini (lihat CLAUDE.md §7) — kueri ini sengaja tidak dipakai handler mana pun.
	CreateRefund(ctx context.Context, arg CreateRefundParams) (string, error)
	// ═══════════════════════════════════════════════════════════════════════
	//  JALUR UANG — anggaran total p99 < 5ms (PRD §4)
	//
	//  Seluruh kueri di berkas ini berjalan dalam SATU transaksi SQL:
	//
	//    BEGIN
	//      CreateSaleIdempotent      → 0 baris berarti duplikat, bukan error
	//      InsertSalesItems          (copyfrom)
	//      InsertPayment             (per metode bayar; FR-22 split payment)
	//      DecrementStock*           → mengunci baris variants
	//      InsertStockEvents         (copyfrom)
	//      InsertOutboxEvent         → mengatasi masalah dual-write
	//    COMMIT
	//
	//  Urutan penting: stok dikurangi SETELAH transaksi tersimpan, agar kegagalan
	//  stok tidak meninggalkan transaksi yatim.
	// ═══════════════════════════════════════════════════════════════════════
	// HOT PATH. ULID dibuat KLIEN — inilah kunci idempotensi.
	//
	// ON CONFLICT DO NOTHING + RETURNING: bila 0 baris kembali, transaksi ini SUDAH
	// pernah masuk. Itu bukan kegagalan melainkan kelas ACCEPTED
	// (ERROR-CATALOG §4): klien menandainya 'synced' dan melanjutkan.
	//
	// Tanpa perilaku ini, transaksi yang sudah aman di server akan tersangkut
	// selamanya di antrean lokal sampai IndexedDB penuh — satu-satunya jalur
	// menuju "kasir tidak bisa berjualan".
	CreateSaleIdempotent(ctx context.Context, arg CreateSaleIdempotentParams) (CreateSaleIdempotentRow, error)
	// Kueri untuk cmd/seed SAJA — bukan jalur produksi.
	//
	// Kenapa lewat sqlc, bukan SQL mentah di dalam cmd/seed: supaya seeder memakai
	// Queries yang SAMA dengan handler HTTP. Kalau skema kueri berubah, seeder ikut
	// pecah saat compile — bukan diam-diam menulis data yang sudah tidak sesuai
	// bentuk tabel. (docs/15-development/LOCAL-SETUP.md §4)
	// tenants adalah tabel akar — ia SENDIRI adalah tenant_id, belum ada tenant_id
	// di atasnya untuk difilter.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (string, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	CreateUserOutletAssignment(ctx context.Context, arg CreateUserOutletAssignmentParams) error
	CreateVariant(ctx context.Context, arg CreateVariantParams) (string, error)
	// SINKRONISASI OFFLINE. Stok BOLEH menjadi negatif.
	//
	// Barang sudah keluar secara fisik, pelanggan sudah pergi, uang sudah diterima.
	// Menolak sync berarti menghapus penjualan nyata dari catatan.
	// Stok minus adalah INFORMASI ("lakukan opname di sini"), bukan kerusakan data.
	// (OFFLINE-SYNC-SPEC §2 prinsip 3, §3A)
	DecrementStockAllowNegative(ctx context.Context, arg DecrementStockAllowNegativeParams) (decimal.Decimal, error)
	// ── PEMOTONGAN STOK ────────────────────────────────────────────────────
	// Dua kueri berbeda dan itu DISENGAJA. Perbedaannya adalah keputusan produk,
	// bukan detail teknis. (ERROR-CATALOG §5)
	// HOT PATH — checkout ONLINE. Menolak bila stok tidak cukup.
	//
	// UPDATE tunggal ini sudah atomik dan mengambil kunci baris; tidak perlu
	// SELECT ... FOR UPDATE terpisah. Inilah alasan mutex Redis TIDAK dipakai
	// di sini — menambahkan Redis ke jalur ini berarti menambah titik kegagalan
	// pada bagian sistem yang paling tidak boleh gagal. (REDIS-STRATEGY §5)
	//
	// 0 baris kembali → INSUFFICIENT_STOCK (kelas PERMANENT).
	DecrementStockStrict(ctx context.Context, arg DecrementStockStrictParams) (decimal.Decimal, error)
	GetBomComponents(ctx context.Context, arg GetBomComponentsParams) ([]GetBomComponentsRow, error)
	GetDailySummary(ctx context.Context, tenantID string) (GetDailySummaryRow, error)
	// Shift kasir. Kasir tidak bisa bertransaksi tanpa shift terbuka (FR-30).
	// HOT PATH — dipanggil di awal setiap checkout untuk memperoleh shift_id.
	// Memakai indeks unik parsial idx_shifts_one_open.
	GetOpenShift(ctx context.Context, arg GetOpenShiftParams) (GetOpenShiftRow, error)
	// Verifikasi refresh token. Kembalikan error bila sudah direvokasi atau expired.
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error)
	// Dipakai saat CreateSaleIdempotent mengembalikan 0 baris (idempotency hit,
	// ERROR-CATALOG §B DUPLICATE_TRANSACTION) — klien menerima record yang SUDAH
	// ada, bukan error, persis seperti openapi.yaml POST /sales respons 200.
	GetSaleByID(ctx context.Context, arg GetSaleByIDParams) (GetSaleByIDRow, error)
	// Dipanggil SEBELUM memproses batch. Bila key sudah ada dengan hash body yang
	// sama, kembalikan respons tersimpan apa adanya — klien menerima jawaban
	// identik seperti percobaan pertama.
	GetSyncReceipt(ctx context.Context, arg GetSyncReceiptParams) (GetSyncReceiptRow, error)
	GetTopProducts(ctx context.Context, tenantID string) ([]GetTopProductsRow, error)
	// Kueri autentikasi untuk jalur /auth/*.
	// Dipakai hanya oleh internal/httpapi/auth.go — bukan seeder.
	// Lookup user berdasarkan email untuk login. Hanya user aktif.
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (GetUserByEmailRow, error)
	// Setelah login sukses, ambil info tenant untuk disertakan dalam JWT claims.
	GetUserWithTenant(ctx context.Context, id string) (GetUserWithTenantRow, error)
	GetVariantForCheckout(ctx context.Context, arg GetVariantForCheckoutParams) (GetVariantForCheckoutRow, error)
	// SECURITY §6 — append-only. Setiap aksi sensitif: void, diskon manual,
	// buka laci tanpa transaksi, akses break-glass platform admin.
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) (string, error)
	// Ditulis dalam TRANSAKSI YANG SAMA dengan penjualan.
	//
	// Postgres dan Redis tidak berbagi transaksi: bila Redis mati setelah COMMIT,
	// event akan hilang tanpa cara mendeteksinya. Outbox memindahkan penerbitan
	// ke proses terpisah, sehingga Redis boleh mati tanpa menghentikan kasir.
	// (EVENT-ARCHITECTURE §5)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (string, error)
	InsertOutlet(ctx context.Context, arg InsertOutletParams) (InsertOutletRow, error)
	// FR-22: satu transaksi boleh punya beberapa baris (Rp 20.000 tunai + Rp 30.000 QRIS).
	InsertPayment(ctx context.Context, arg InsertPaymentParams) (string, error)
	InsertRefund(ctx context.Context, arg InsertRefundParams) (string, error)
	InsertRefundItem(ctx context.Context, arg InsertRefundItemParams) (string, error)
	// HOT PATH. quantity DECIMAL(14,3) — 0,25 kg tepung · 30 ml parfum.
	// unit_price & unit_cost DISALIN saat transaksi: laporan tidak pernah
	// menghitung ulang memakai harga sekarang.
	InsertSalesItems(ctx context.Context, arg []InsertSalesItemsParams) (int64, error)
	InsertStockEvent(ctx context.Context, arg InsertStockEventParams) (string, error)
	// Ledger append-only. variants.stock_quantity hanyalah cache;
	// KEBENARAN stok ada di tabel ini. (DATA-MODEL §4C)
	InsertStockEvents(ctx context.Context, arg []InsertStockEventsParams) (int64, error)
	InsertStockOpname(ctx context.Context, arg InsertStockOpnameParams) (string, error)
	InsertStockOpnameItem(ctx context.Context, arg InsertStockOpnameItemParams) (InsertStockOpnameItemRow, error)
	ListCatalogForSync(ctx context.Context, arg ListCatalogForSyncParams) ([]ListCatalogForSyncRow, error)
	ListOutlets(ctx context.Context, tenantID string) ([]ListOutletsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListStockLevels(ctx context.Context, tenantID string) ([]ListStockLevelsRow, error)
	LookupVariantByBarcode(ctx context.Context, arg LookupVariantByBarcodeParams) (LookupVariantByBarcodeRow, error)
	// Indeks unik parsial mencegah dua shift terbuka untuk kasir yang sama.
	// Bila terjadi konflik, itu bug klien — bukan kondisi yang perlu ditangani diam-diam.
	OpenShift(ctx context.Context, arg OpenShiftParams) (OpenShiftRow, error)
	// FR-31 petty cash — mempengaruhi perhitungan expected_cash di atas.
	RecordCashMovement(ctx context.Context, arg RecordCashMovementParams) (RecordCashMovementRow, error)
	// sqlc-vet-disable: wajib-tenant-scope
	// Buat tenant baru + user owner sekaligus dalam satu transaksi (dipanggil
	// dari handler POST /auth/register). Query ini hanya untuk registrasi awal —
	// tenant_id belum ada, jadi dikecualikan dari aturan wajib-tenant-scope.
	RegisterTenantOwner(ctx context.Context, arg RegisterTenantOwnerParams) (string, error)
	// Revoke semua token aktif milik user (logout-all / compromised account).
	RevokeAllUserTokens(ctx context.Context, arg RevokeAllUserTokensParams) error
	// Revoke satu token spesifik (logout atau rotate). tenant_id sebagai
	// parameter WAJIB (SECURITY.md §2B "Aturan Emas SQL") meski token_hash
	// sendiri unik secara global — pertahanan berlapis, bukan cuma soal
	// tereksploitasi atau tidak.
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	// Retensi 7 hari; dibersihkan job harian. (RETENTION §2)
	SaveSyncReceipt(ctx context.Context, arg SaveSyncReceiptParams) error
	SearchVariants(ctx context.Context, arg SearchVariantsParams) ([]SearchVariantsRow, error)
	UpdateOutlet(ctx context.Context, arg UpdateOutletParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateVariant(ctx context.Context, arg UpdateVariantParams) error
	// Telemetri perangkat ikut bersama sync. storage_used_pct adalah peringatan dini
	// sebelum IndexedDB penuh — server bisa tampak sehat sempurna sementara sebuah
	// perangkat kasir mendekati kegagalan total. (OBSERVABILITY §3)
	UpsertDeviceSyncState(ctx context.Context, arg UpsertDeviceSyncStateParams) error
	// ── VOID & IDEMPOTENSI ─────────────────────────────────────────────────
	// Hanya transaksi 'paid' yang bisa di-void; mencoba void dua kali
	// mengembalikan 0 baris → TRANSACTION_ALREADY_VOIDED (kelas PERMANENT).
	VoidTransaction(ctx context.Context, arg VoidTransactionParams) (VoidTransactionRow, error)
}

var _ Querier = (*Queries)(nil)
