// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countReportItems = `-- name: CountReportItems :one
SELECT COUNT(*)::int AS item_lines
FROM sales_items si
JOIN sales_transactions s ON s.id = si.transaction_id AND s.tenant_id = si.tenant_id
WHERE si.tenant_id = $1
  AND s.outlet_id = $2
  AND NOT s.is_sandbox
  AND NOT s.is_late_arrival
  AND s.payment_status = 'paid'
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) >= $3::timestamptz
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) <  $4::timestamptz
`

type CountReportItemsParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
}

// Jumlah BARIS barang terjual, bukan penjumlahan kuantitas: menjumlahkan
// 30 ml dengan 2 botol menghasilkan angka yang tidak berarti apa-apa
// (alasan yang sama dengan totalItemCount di layar kasir).
func (q *Queries) CountReportItems(ctx context.Context, arg CountReportItemsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countReportItems,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
	)
	var item_lines int32
	err := row.Scan(&item_lines)
	return item_lines, err
}

const getLateArrivalBucket = `-- name: GetLateArrivalBucket :one
SELECT
    COUNT(*)::int                          AS late_count,
    COALESCE(SUM(s.grand_total), 0)::decimal AS late_total
FROM sales_transactions s
WHERE s.tenant_id = $1
  AND s.outlet_id = $2
  AND NOT s.is_sandbox
  AND s.is_late_arrival
  AND s.payment_status = 'paid'
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) >= $3::timestamptz
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) <  $4::timestamptz
`

type GetLateArrivalBucketParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
}

type GetLateArrivalBucketRow struct {
	LateCount int32           `db:"late_count" json:"late_count"`
	LateTotal decimal.Decimal `db:"late_total" json:"late_total"`
}

// Ember terpisah invarian §6 #5: transaksi hari itu yang baru tiba SETELAH
// shift-nya ditutup. Nyata dan sah, tetapi tidak boleh menggeser angka yang
// sudah dicetak. Pemilik melihatnya sebagai baris tersendiri.
func (q *Queries) GetLateArrivalBucket(ctx context.Context, arg GetLateArrivalBucketParams) (GetLateArrivalBucketRow, error) {
	row := q.db.QueryRow(ctx, getLateArrivalBucket,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
	)
	var i GetLateArrivalBucketRow
	err := row.Scan(&i.LateCount, &i.LateTotal)
	return i, err
}

const getSalesReportSummary = `-- name: GetSalesReportSummary :one

SELECT
    COUNT(*) FILTER (WHERE s.payment_status = 'paid')::int            AS paid_count,
    COALESCE(SUM(s.subtotal)      FILTER (WHERE s.payment_status = 'paid'), 0)::decimal AS gross_sales,
    COALESCE(SUM(s.discount_total) FILTER (WHERE s.payment_status = 'paid'), 0)::decimal AS discount_total,
    COALESCE(SUM(s.tax_total)     FILTER (WHERE s.payment_status = 'paid'), 0)::decimal AS tax_total,
    COALESCE(SUM(s.grand_total)   FILTER (WHERE s.payment_status = 'paid'), 0)::decimal AS net_sales,
    COUNT(*) FILTER (WHERE s.payment_status = 'void')::int            AS void_count,
    COALESCE(SUM(s.grand_total)   FILTER (WHERE s.payment_status = 'void'), 0)::decimal AS void_total
FROM sales_transactions s
WHERE s.tenant_id = $1
  AND s.outlet_id = $2
  AND NOT s.is_sandbox
  AND NOT s.is_late_arrival
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) >= $3::timestamptz
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) <  $4::timestamptz
`

type GetSalesReportSummaryParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
}

type GetSalesReportSummaryRow struct {
	PaidCount     int32           `db:"paid_count" json:"paid_count"`
	GrossSales    decimal.Decimal `db:"gross_sales" json:"gross_sales"`
	DiscountTotal decimal.Decimal `db:"discount_total" json:"discount_total"`
	TaxTotal      decimal.Decimal `db:"tax_total" json:"tax_total"`
	NetSales      decimal.Decimal `db:"net_sales" json:"net_sales"`
	VoidCount     int32           `db:"void_count" json:"void_count"`
	VoidTotal     decimal.Decimal `db:"void_total" json:"void_total"`
}

// Laporan penjualan harian / tutup buku (Z-Report).
//
// DUA aturan yang membentuk seluruh berkas ini:
//
//  1. **Waktu laporan = waktu TERKOREKSI perangkat**, bukan waktu server.
//     `COALESCE(offline_created_at_adj, offline_created_at, created_at)` —
//     transaksi yang dibuat offline pukul 20.00 lalu terkirim pukul 23.00
//     milik hari ia terjadi, bukan hari ia sampai. (skema 00005 baris
//     "Laporan memakai versi terkoreksi; audit memakai yang mentah")
//
//  2. **Z-Report yang sudah dicetak tidak pernah berubah** (invarian §6 #5).
//     Karena itu `is_late_arrival` DIKECUALIKAN dari semua angka utama dan
//     dilaporkan di embernya sendiri — sama seperti CalculateExpectedCash.
//     Tanpa pengecualian itu, laporan kemarin yang sudah ditandatangani
//     kasir bisa berubah sendiri hari ini.
//
// `is_sandbox` dikecualikan di mana-mana: data percobaan onboarding tidak
// pernah masuk laporan mana pun.
// Angka induk laporan. Void dihitung terpisah — barangnya kembali dan
// uangnya tidak pernah jadi pendapatan, tetapi pemilik tetap perlu tahu
// berapa banyak yang dibatalkan hari itu.
func (q *Queries) GetSalesReportSummary(ctx context.Context, arg GetSalesReportSummaryParams) (GetSalesReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSalesReportSummary,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
	)
	var i GetSalesReportSummaryRow
	err := row.Scan(
		&i.PaidCount,
		&i.GrossSales,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.NetSales,
		&i.VoidCount,
		&i.VoidTotal,
	)
	return i, err
}

const listShiftsForReport = `-- name: ListShiftsForReport :many
SELECT
    sh.id,
    sh.opened_at,
    sh.closed_at,
    sh.opening_cash,
    sh.expected_cash,
    sh.counted_cash,
    sh.variance,
    sh.status,
    u.name AS cashier_name
FROM shifts sh
LEFT JOIN users u ON u.id = sh.cashier_id AND u.tenant_id = sh.tenant_id
WHERE sh.tenant_id = $1
  AND sh.outlet_id = $2
  AND sh.opened_at >= $3::timestamptz
  AND sh.opened_at <  $4::timestamptz
ORDER BY sh.opened_at
`

type ListShiftsForReportParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
}

type ListShiftsForReportRow struct {
	ID           string              `db:"id" json:"id"`
	OpenedAt     pgtype.Timestamptz  `db:"opened_at" json:"opened_at"`
	ClosedAt     pgtype.Timestamptz  `db:"closed_at" json:"closed_at"`
	OpeningCash  decimal.Decimal     `db:"opening_cash" json:"opening_cash"`
	ExpectedCash decimal.NullDecimal `db:"expected_cash" json:"expected_cash"`
	CountedCash  decimal.NullDecimal `db:"counted_cash" json:"counted_cash"`
	Variance     decimal.NullDecimal `db:"variance" json:"variance"`
	Status       string              `db:"status" json:"status"`
	CashierName  *string             `db:"cashier_name" json:"cashier_name"`
}

// Satu baris per shift: siapa kasirnya, berapa kas diharapkan, berapa yang
// dihitung, dan selisihnya. Shift yang MASIH TERBUKA ikut tampil dengan
// nilai kosong — pemilik perlu tahu laporannya belum final.
func (q *Queries) ListShiftsForReport(ctx context.Context, arg ListShiftsForReportParams) ([]ListShiftsForReportRow, error) {
	rows, err := q.db.Query(ctx, listShiftsForReport,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListShiftsForReportRow{}
	for rows.Next() {
		var i ListShiftsForReportRow
		if err := rows.Scan(
			&i.ID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.OpeningCash,
			&i.ExpectedCash,
			&i.CountedCash,
			&i.Variance,
			&i.Status,
			&i.CashierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopProductsForReport = `-- name: ListTopProductsForReport :many
SELECT
    p.name AS product_name,
    v.name AS variant_name,
    si.uom,
    SUM(si.quantity)::decimal AS quantity_sold,
    SUM(si.subtotal)::decimal AS revenue
FROM sales_items si
JOIN sales_transactions s ON s.id = si.transaction_id AND s.tenant_id = si.tenant_id
JOIN variants v ON v.id = si.variant_id AND v.tenant_id = si.tenant_id
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
WHERE si.tenant_id = $1
  AND s.outlet_id = $2
  AND NOT s.is_sandbox
  AND NOT s.is_late_arrival
  AND s.payment_status = 'paid'
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) >= $3::timestamptz
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) <  $4::timestamptz
GROUP BY p.name, v.name, si.uom
ORDER BY revenue DESC
LIMIT $5::int
`

type ListTopProductsForReportParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
	Batas    int32              `db:"batas" json:"batas"`
}

type ListTopProductsForReportRow struct {
	ProductName  string          `db:"product_name" json:"product_name"`
	VariantName  string          `db:"variant_name" json:"variant_name"`
	Uom          string          `db:"uom" json:"uom"`
	QuantitySold decimal.Decimal `db:"quantity_sold" json:"quantity_sold"`
	Revenue      decimal.Decimal `db:"revenue" json:"revenue"`
}

// Barang terlaris periode ini, dalam SATUAN JUAL (ml untuk bibit) — ini
// laporan penjualan, bukan laporan stok. Pergerakan gram ada di
// /laporan-stok yang membaca ledger stock_events.
func (q *Queries) ListTopProductsForReport(ctx context.Context, arg ListTopProductsForReportParams) ([]ListTopProductsForReportRow, error) {
	rows, err := q.db.Query(ctx, listTopProductsForReport,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
		arg.Batas,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopProductsForReportRow{}
	for rows.Next() {
		var i ListTopProductsForReportRow
		if err := rows.Scan(
			&i.ProductName,
			&i.VariantName,
			&i.Uom,
			&i.QuantitySold,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCashMovementsForReport = `-- name: SumCashMovementsForReport :one
SELECT
    COALESCE(SUM(m.amount) FILTER (WHERE m.direction = 'in'), 0)::decimal  AS cash_in,
    COALESCE(SUM(m.amount) FILTER (WHERE m.direction = 'out'), 0)::decimal AS cash_out
FROM cash_movements m
JOIN shifts sh ON sh.id = m.shift_id AND sh.tenant_id = m.tenant_id
WHERE m.tenant_id = $1
  AND sh.outlet_id = $2
  AND m.created_at >= $3::timestamptz
  AND m.created_at <  $4::timestamptz
`

type SumCashMovementsForReportParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
}

type SumCashMovementsForReportRow struct {
	CashIn  decimal.Decimal `db:"cash_in" json:"cash_in"`
	CashOut decimal.Decimal `db:"cash_out" json:"cash_out"`
}

// Kas masuk/keluar di luar penjualan (FR-31 petty cash): ambil uang belanja,
// setor ke bank. Tanpa ini, selisih laci tidak pernah bisa dijelaskan.
func (q *Queries) SumCashMovementsForReport(ctx context.Context, arg SumCashMovementsForReportParams) (SumCashMovementsForReportRow, error) {
	row := q.db.QueryRow(ctx, sumCashMovementsForReport,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
	)
	var i SumCashMovementsForReportRow
	err := row.Scan(&i.CashIn, &i.CashOut)
	return i, err
}

const sumPaymentsByMethodForReport = `-- name: SumPaymentsByMethodForReport :many
SELECT
    p.payment_method,
    COUNT(*)::int                     AS payment_count,
    COALESCE(SUM(p.amount), 0)::decimal AS total
FROM payments p
JOIN sales_transactions s ON s.id = p.transaction_id AND s.tenant_id = p.tenant_id
WHERE p.tenant_id = $1
  AND s.outlet_id = $2
  AND NOT s.is_sandbox
  AND NOT s.is_late_arrival
  AND s.payment_status = 'paid'
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) >= $3::timestamptz
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) <  $4::timestamptz
GROUP BY p.payment_method
ORDER BY p.payment_method
`

type SumPaymentsByMethodForReportParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
}

type SumPaymentsByMethodForReportRow struct {
	PaymentMethod string          `db:"payment_method" json:"payment_method"`
	PaymentCount  int32           `db:"payment_count" json:"payment_count"`
	Total         decimal.Decimal `db:"total" json:"total"`
}

// Rincian per metode bayar. Inilah yang dicocokkan pemilik dengan isi laci
// (tunai) dan mutasi rekening (transfer/QRIS).
func (q *Queries) SumPaymentsByMethodForReport(ctx context.Context, arg SumPaymentsByMethodForReportParams) ([]SumPaymentsByMethodForReportRow, error) {
	rows, err := q.db.Query(ctx, sumPaymentsByMethodForReport,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumPaymentsByMethodForReportRow{}
	for rows.Next() {
		var i SumPaymentsByMethodForReportRow
		if err := rows.Scan(&i.PaymentMethod, &i.PaymentCount, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumRefundsForReport = `-- name: SumRefundsForReport :one
SELECT
    COUNT(*)::int                        AS refund_count,
    COALESCE(SUM(r.amount), 0)::decimal  AS refund_total
FROM refunds r
JOIN sales_transactions s ON s.id = r.transaction_id AND s.tenant_id = r.tenant_id
WHERE r.tenant_id = $1
  AND s.outlet_id = $2
  AND NOT s.is_sandbox
  AND r.created_at >= $3::timestamptz
  AND r.created_at <  $4::timestamptz
`

type SumRefundsForReportParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
}

type SumRefundsForReportRow struct {
	RefundCount int32           `db:"refund_count" json:"refund_count"`
	RefundTotal decimal.Decimal `db:"refund_total" json:"refund_total"`
}

// Refund dihitung dari TANGGAL REFUND-nya, bukan tanggal transaksi aslinya:
// uang keluar dari laci hari ini, jadi ia mengurangi kas hari ini. Nota
// yang direfund bisa saja terbit minggu lalu.
func (q *Queries) SumRefundsForReport(ctx context.Context, arg SumRefundsForReportParams) (SumRefundsForReportRow, error) {
	row := q.db.QueryRow(ctx, sumRefundsForReport,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
	)
	var i SumRefundsForReportRow
	err := row.Scan(&i.RefundCount, &i.RefundTotal)
	return i, err
}
