// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales_history.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getSaleDetail = `-- name: GetSaleDetail :one
SELECT
    s.id, s.receipt_number, s.subtotal, s.discount_total, s.tax_total, s.grand_total,
    s.payment_status, s.outlet_id, s.shift_id,
    COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at)::timestamptz AS sold_at,
    s.customer_id, c.member_code, c.name AS customer_name, u.name AS cashier_name,
    COALESCE((SELECT SUM(r.amount) FROM refunds r
              WHERE r.tenant_id = s.tenant_id AND r.transaction_id = s.id), 0)::decimal AS refunded_total,
    -- Void hanya boleh selama shift-nya masih terbuka (invarian: Z-Report yang
    -- sudah dicetak tidak pernah berubah).
    COALESCE((SELECT sh.status = 'open' FROM shifts sh
              WHERE sh.id = s.shift_id AND sh.tenant_id = s.tenant_id), FALSE)::boolean AS shift_open
FROM sales_transactions s
LEFT JOIN customers c ON c.id = s.customer_id AND c.tenant_id = s.tenant_id
LEFT JOIN users u ON u.id = s.cashier_id AND u.tenant_id = s.tenant_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetSaleDetailParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type GetSaleDetailRow struct {
	ID            string             `db:"id" json:"id"`
	ReceiptNumber string             `db:"receipt_number" json:"receipt_number"`
	Subtotal      decimal.Decimal    `db:"subtotal" json:"subtotal"`
	DiscountTotal decimal.Decimal    `db:"discount_total" json:"discount_total"`
	TaxTotal      decimal.Decimal    `db:"tax_total" json:"tax_total"`
	GrandTotal    decimal.Decimal    `db:"grand_total" json:"grand_total"`
	PaymentStatus string             `db:"payment_status" json:"payment_status"`
	OutletID      string             `db:"outlet_id" json:"outlet_id"`
	ShiftID       *string            `db:"shift_id" json:"shift_id"`
	SoldAt        pgtype.Timestamptz `db:"sold_at" json:"sold_at"`
	CustomerID    *string            `db:"customer_id" json:"customer_id"`
	MemberCode    *string            `db:"member_code" json:"member_code"`
	CustomerName  *string            `db:"customer_name" json:"customer_name"`
	CashierName   *string            `db:"cashier_name" json:"cashier_name"`
	RefundedTotal decimal.Decimal    `db:"refunded_total" json:"refunded_total"`
	ShiftOpen     bool               `db:"shift_open" json:"shift_open"`
}

func (q *Queries) GetSaleDetail(ctx context.Context, arg GetSaleDetailParams) (GetSaleDetailRow, error) {
	row := q.db.QueryRow(ctx, getSaleDetail, arg.TenantID, arg.ID)
	var i GetSaleDetailRow
	err := row.Scan(
		&i.ID,
		&i.ReceiptNumber,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.TaxTotal,
		&i.GrandTotal,
		&i.PaymentStatus,
		&i.OutletID,
		&i.ShiftID,
		&i.SoldAt,
		&i.CustomerID,
		&i.MemberCode,
		&i.CustomerName,
		&i.CashierName,
		&i.RefundedTotal,
		&i.ShiftOpen,
	)
	return i, err
}

const listSaleItems = `-- name: ListSaleItems :many
SELECT si.id, si.variant_id, p.name AS product_name, v.name AS variant_name,
       si.quantity, si.uom, si.unit_price, si.subtotal
FROM sales_items si
JOIN variants v ON v.id = si.variant_id AND v.tenant_id = si.tenant_id
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
WHERE si.tenant_id = $1 AND si.transaction_id = $2
ORDER BY si.id
`

type ListSaleItemsParams struct {
	TenantID      string `db:"tenant_id" json:"tenant_id"`
	TransactionID string `db:"transaction_id" json:"transaction_id"`
}

type ListSaleItemsRow struct {
	ID          string          `db:"id" json:"id"`
	VariantID   string          `db:"variant_id" json:"variant_id"`
	ProductName string          `db:"product_name" json:"product_name"`
	VariantName string          `db:"variant_name" json:"variant_name"`
	Quantity    decimal.Decimal `db:"quantity" json:"quantity"`
	Uom         string          `db:"uom" json:"uom"`
	UnitPrice   decimal.Decimal `db:"unit_price" json:"unit_price"`
	Subtotal    decimal.Decimal `db:"subtotal" json:"subtotal"`
}

func (q *Queries) ListSaleItems(ctx context.Context, arg ListSaleItemsParams) ([]ListSaleItemsRow, error) {
	rows, err := q.db.Query(ctx, listSaleItems, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSaleItemsRow{}
	for rows.Next() {
		var i ListSaleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Quantity,
			&i.Uom,
			&i.UnitPrice,
			&i.Subtotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalePayments = `-- name: ListSalePayments :many
SELECT payment_method, amount
FROM payments
WHERE tenant_id = $1 AND transaction_id = $2
ORDER BY id
`

type ListSalePaymentsParams struct {
	TenantID      string `db:"tenant_id" json:"tenant_id"`
	TransactionID string `db:"transaction_id" json:"transaction_id"`
}

type ListSalePaymentsRow struct {
	PaymentMethod string          `db:"payment_method" json:"payment_method"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
}

func (q *Queries) ListSalePayments(ctx context.Context, arg ListSalePaymentsParams) ([]ListSalePaymentsRow, error) {
	rows, err := q.db.Query(ctx, listSalePayments, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalePaymentsRow{}
	for rows.Next() {
		var i ListSalePaymentsRow
		if err := rows.Scan(&i.PaymentMethod, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleRefunds = `-- name: ListSaleRefunds :many
SELECT r.id, r.refund_type, r.amount, r.reason, r.restock, r.created_at, u.name AS approved_by_name
FROM refunds r
LEFT JOIN users u ON u.id = r.approved_by AND u.tenant_id = r.tenant_id
WHERE r.tenant_id = $1 AND r.transaction_id = $2
ORDER BY r.created_at
`

type ListSaleRefundsParams struct {
	TenantID      string `db:"tenant_id" json:"tenant_id"`
	TransactionID string `db:"transaction_id" json:"transaction_id"`
}

type ListSaleRefundsRow struct {
	ID             string             `db:"id" json:"id"`
	RefundType     string             `db:"refund_type" json:"refund_type"`
	Amount         decimal.Decimal    `db:"amount" json:"amount"`
	Reason         string             `db:"reason" json:"reason"`
	Restock        bool               `db:"restock" json:"restock"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ApprovedByName *string            `db:"approved_by_name" json:"approved_by_name"`
}

func (q *Queries) ListSaleRefunds(ctx context.Context, arg ListSaleRefundsParams) ([]ListSaleRefundsRow, error) {
	rows, err := q.db.Query(ctx, listSaleRefunds, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSaleRefundsRow{}
	for rows.Next() {
		var i ListSaleRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.RefundType,
			&i.Amount,
			&i.Reason,
			&i.Restock,
			&i.CreatedAt,
			&i.ApprovedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many

SELECT
    s.id, s.receipt_number, s.grand_total, s.payment_status,
    COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at)::timestamptz AS sold_at,
    s.customer_id, c.member_code, u.name AS cashier_name,
    COALESCE((SELECT SUM(r.amount) FROM refunds r
              WHERE r.tenant_id = s.tenant_id AND r.transaction_id = s.id), 0)::decimal AS refunded_total,
    (SELECT COUNT(*) FROM sales_items si
     WHERE si.tenant_id = s.tenant_id AND si.transaction_id = s.id)::int AS item_count
FROM sales_transactions s
LEFT JOIN customers c ON c.id = s.customer_id AND c.tenant_id = s.tenant_id
LEFT JOIN users u ON u.id = s.cashier_id AND u.tenant_id = s.tenant_id
WHERE s.tenant_id = $1
  AND s.outlet_id = $2
  AND NOT s.is_sandbox
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) >= $3::timestamptz
  AND COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) < $4::timestamptz
  AND ($5::text IS NULL OR s.receipt_number ILIKE '%' || $5::text || '%')
ORDER BY COALESCE(s.offline_created_at_adj, s.offline_created_at, s.created_at) DESC
LIMIT $6::int
`

type ListSalesParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
	Cari     *string            `db:"cari" json:"cari"`
	Batas    int32              `db:"batas" json:"batas"`
}

type ListSalesRow struct {
	ID            string             `db:"id" json:"id"`
	ReceiptNumber string             `db:"receipt_number" json:"receipt_number"`
	GrandTotal    decimal.Decimal    `db:"grand_total" json:"grand_total"`
	PaymentStatus string             `db:"payment_status" json:"payment_status"`
	SoldAt        pgtype.Timestamptz `db:"sold_at" json:"sold_at"`
	CustomerID    *string            `db:"customer_id" json:"customer_id"`
	MemberCode    *string            `db:"member_code" json:"member_code"`
	CashierName   *string            `db:"cashier_name" json:"cashier_name"`
	RefundedTotal decimal.Decimal    `db:"refunded_total" json:"refunded_total"`
	ItemCount     int32              `db:"item_count" json:"item_count"`
}

// Riwayat transaksi: mencari nota lama untuk klaim garansi, refund, dan void.
// Semua kueri memfilter tenant_id; pemanggilnya juga membatasi outlet.
// Daftar transaksi terbaru dengan total refund yang sudah pernah terjadi,
// supaya layar riwayat bisa menandai "sudah direfund" tanpa N+1 kueri.
// Data percobaan (is_sandbox) dikecualikan, sama seperti seluruh laporan.
func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
		arg.Cari,
		arg.Batas,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRow{}
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptNumber,
			&i.GrandTotal,
			&i.PaymentStatus,
			&i.SoldAt,
			&i.CustomerID,
			&i.MemberCode,
			&i.CashierName,
			&i.RefundedTotal,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const voidSale = `-- name: VoidSale :execrows
UPDATE sales_transactions s
SET payment_status = 'void'
WHERE s.tenant_id = $1
  AND s.id = $2
  AND s.payment_status = 'paid'
  AND EXISTS (SELECT 1 FROM shifts sh
              WHERE sh.id = s.shift_id AND sh.tenant_id = s.tenant_id AND sh.status = 'open')
`

type VoidSaleParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

// Pembatalan hanya untuk transaksi yang MASIH lunas dan shift-nya terbuka;
// 0 baris = sudah void, sudah tutup shift, atau bukan milik tenant ini.
func (q *Queries) VoidSale(ctx context.Context, arg VoidSaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, voidSale, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
