// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package store

import (
	"context"

	"github.com/shopspring/decimal"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, tenant_id, name, sort_order, color_token)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateCategoryParams struct {
	ID         string  `db:"id" json:"id"`
	TenantID   string  `db:"tenant_id" json:"tenant_id"`
	Name       string  `db:"name" json:"name"`
	SortOrder  int32   `db:"sort_order" json:"sort_order"`
	ColorToken *string `db:"color_token" json:"color_token"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (string, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.SortOrder,
		arg.ColorToken,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createOutlet = `-- name: CreateOutlet :one
INSERT INTO outlets (id, tenant_id, name, address, phone, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateOutletParams struct {
	ID       string  `db:"id" json:"id"`
	TenantID string  `db:"tenant_id" json:"tenant_id"`
	Name     string  `db:"name" json:"name"`
	Address  *string `db:"address" json:"address"`
	Phone    *string `db:"phone" json:"phone"`
	Timezone string  `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateOutlet(ctx context.Context, arg CreateOutletParams) (string, error) {
	row := q.db.QueryRow(ctx, createOutlet,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Timezone,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, tenant_id, category_id, name, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateProductParams struct {
	ID          string  `db:"id" json:"id"`
	TenantID    string  `db:"tenant_id" json:"tenant_id"`
	CategoryID  *string `db:"category_id" json:"category_id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (string, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.TenantID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO refunds (
    id, tenant_id, transaction_id, shift_id, refund_type, amount, reason, approved_by, restock
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id
`

type CreateRefundParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	TransactionID string          `db:"transaction_id" json:"transaction_id"`
	ShiftID       *string         `db:"shift_id" json:"shift_id"`
	RefundType    string          `db:"refund_type" json:"refund_type"`
	Amount        decimal.Decimal `db:"amount" json:"amount"`
	Reason        string          `db:"reason" json:"reason"`
	ApprovedBy    string          `db:"approved_by" json:"approved_by"`
	Restock       bool            `db:"restock" json:"restock"`
}

// Dipakai HANYA oleh seeder untuk mengisi kasus tepi "refund parsial"
// (TESTING-STRATEGY.md §4). Jalur HTTP /sales/{id}/refund BELUM diimplementasikan
// sesi ini (lihat CLAUDE.md §7) — kueri ini sengaja tidak dipakai handler mana pun.
func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (string, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.ID,
		arg.TenantID,
		arg.TransactionID,
		arg.ShiftID,
		arg.RefundType,
		arg.Amount,
		arg.Reason,
		arg.ApprovedBy,
		arg.Restock,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (id, name, business_type, plan_tier, plan_status) -- sqlc-vet-disable: wajib-tenant-scope
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateTenantParams struct {
	ID           string  `db:"id" json:"id"`
	Name         string  `db:"name" json:"name"`
	BusinessType *string `db:"business_type" json:"business_type"`
	PlanTier     string  `db:"plan_tier" json:"plan_tier"`
	PlanStatus   string  `db:"plan_status" json:"plan_status"`
}

// Kueri untuk cmd/seed SAJA — bukan jalur produksi.
//
// Kenapa lewat sqlc, bukan SQL mentah di dalam cmd/seed: supaya seeder memakai
// Queries yang SAMA dengan handler HTTP. Kalau skema kueri berubah, seeder ikut
// pecah saat compile — bukan diam-diam menulis data yang sudah tidak sesuai
// bentuk tabel. (docs/15-development/LOCAL-SETUP.md §4)
// tenants adalah tabel akar — ia SENDIRI adalah tenant_id, belum ada tenant_id
// di atasnya untuk difilter.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (string, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.BusinessType,
		arg.PlanTier,
		arg.PlanStatus,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, tenant_id, name, email, password_hash, role, pin_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserParams struct {
	ID           string  `db:"id" json:"id"`
	TenantID     string  `db:"tenant_id" json:"tenant_id"`
	Name         string  `db:"name" json:"name"`
	Email        string  `db:"email" json:"email"`
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	Role         string  `db:"role" json:"role"`
	PinHash      *string `db:"pin_hash" json:"pin_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.PinHash,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUserOutletAssignment = `-- name: CreateUserOutletAssignment :exec
INSERT INTO user_outlet_assignments (id, tenant_id, user_id, outlet_id, is_primary)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserOutletAssignmentParams struct {
	ID        string `db:"id" json:"id"`
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	UserID    string `db:"user_id" json:"user_id"`
	OutletID  string `db:"outlet_id" json:"outlet_id"`
	IsPrimary bool   `db:"is_primary" json:"is_primary"`
}

func (q *Queries) CreateUserOutletAssignment(ctx context.Context, arg CreateUserOutletAssignmentParams) error {
	_, err := q.db.Exec(ctx, createUserOutletAssignment,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.OutletID,
		arg.IsPrimary,
	)
	return err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (
    id, tenant_id, product_id, name, sku, barcode,
    item_type, uom, uom_precision, price, cost_price, stock_quantity, min_stock_alert
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id
`

type CreateVariantParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	ProductID     string          `db:"product_id" json:"product_id"`
	Name          string          `db:"name" json:"name"`
	Sku           *string         `db:"sku" json:"sku"`
	Barcode       *string         `db:"barcode" json:"barcode"`
	ItemType      string          `db:"item_type" json:"item_type"`
	Uom           string          `db:"uom" json:"uom"`
	UomPrecision  int16           `db:"uom_precision" json:"uom_precision"`
	Price         decimal.Decimal `db:"price" json:"price"`
	CostPrice     decimal.Decimal `db:"cost_price" json:"cost_price"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
	MinStockAlert decimal.Decimal `db:"min_stock_alert" json:"min_stock_alert"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (string, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.ID,
		arg.TenantID,
		arg.ProductID,
		arg.Name,
		arg.Sku,
		arg.Barcode,
		arg.ItemType,
		arg.Uom,
		arg.UomPrecision,
		arg.Price,
		arg.CostPrice,
		arg.StockQuantity,
		arg.MinStockAlert,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
