// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shift.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const calculateExpectedCash = `-- name: CalculateExpectedCash :one
SELECT
    s.opening_cash,
    COALESCE(cash.total, 0)::numeric   AS cash_sales,
    COALESCE(mv.total_in, 0)::numeric  AS cash_in,
    COALESCE(mv.total_out, 0)::numeric AS cash_out
FROM shifts s
LEFT JOIN LATERAL (
    SELECT SUM(p.amount) AS total
    FROM payments p
    JOIN sales_transactions t
        ON t.id = p.transaction_id
       AND t.tenant_id = p.tenant_id
    WHERE p.tenant_id      = s.tenant_id
      AND t.shift_id       = s.id
      AND p.payment_method = 'cash'
      AND t.payment_status = 'paid'
      AND NOT t.is_late_arrival
      AND NOT t.is_sandbox
) cash ON TRUE
LEFT JOIN LATERAL (
    SELECT
        SUM(amount) FILTER (WHERE direction = 'in')  AS total_in,
        SUM(amount) FILTER (WHERE direction = 'out') AS total_out
    FROM cash_movements
    WHERE tenant_id = s.tenant_id
      AND shift_id  = s.id
) mv ON TRUE
WHERE s.tenant_id = $1
  AND s.id        = $2
`

type CalculateExpectedCashParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type CalculateExpectedCashRow struct {
	OpeningCash decimal.Decimal `db:"opening_cash" json:"opening_cash"`
	CashSales   decimal.Decimal `db:"cash_sales" json:"cash_sales"`
	CashIn      decimal.Decimal `db:"cash_in" json:"cash_in"`
	CashOut     decimal.Decimal `db:"cash_out" json:"cash_out"`
}

// expected = saldo awal + tunai masuk + kas masuk − kas keluar.
//
// Transaksi yang tiba TERLAMBAT (is_late_arrival) sengaja DIKECUALIKAN:
// Z-Report yang sudah dicetak tidak boleh berubah retroaktif, karena kasir
// sudah menghitung uang fisik dan menandatangani hasilnya. (OFFLINE-SYNC-SPEC §3C)
func (q *Queries) CalculateExpectedCash(ctx context.Context, arg CalculateExpectedCashParams) (CalculateExpectedCashRow, error) {
	row := q.db.QueryRow(ctx, calculateExpectedCash, arg.TenantID, arg.ID)
	var i CalculateExpectedCashRow
	err := row.Scan(
		&i.OpeningCash,
		&i.CashSales,
		&i.CashIn,
		&i.CashOut,
	)
	return i, err
}

const closeShift = `-- name: CloseShift :one
UPDATE shifts
SET closed_at     = $3,
    expected_cash = $4,
    counted_cash  = $5,
    variance      = $5::numeric - $4::numeric,
    closed_by     = $6,
    status        = 'closed'
WHERE tenant_id = $1
  AND id        = $2
  AND status    = 'open'
RETURNING id, variance, closed_at
`

type CloseShiftParams struct {
	TenantID     string              `db:"tenant_id" json:"tenant_id"`
	ID           string              `db:"id" json:"id"`
	ClosedAt     pgtype.Timestamptz  `db:"closed_at" json:"closed_at"`
	ExpectedCash decimal.NullDecimal `db:"expected_cash" json:"expected_cash"`
	CountedCash  decimal.NullDecimal `db:"counted_cash" json:"counted_cash"`
	ClosedBy     *string             `db:"closed_by" json:"closed_by"`
}

type CloseShiftRow struct {
	ID       string              `db:"id" json:"id"`
	Variance decimal.NullDecimal `db:"variance" json:"variance"`
	ClosedAt pgtype.Timestamptz  `db:"closed_at" json:"closed_at"`
}

// variance = counted − expected. Negatif maupun positif sama-sama perlu diselidiki.
//
// Cast eksplisit ::numeric WAJIB di sini: tanpanya Postgres tidak bisa
// meng-infer tipe $4/$5 dari ekspresi aritmetika `$5 - $4` walau keduanya
// juga dipakai di SET lain sebagai kolom numeric — gagal dengan
// "operator is not unique: unknown - unknown" (ditemukan saat kueri ini
// benar-benar dijalankan pertama kali, lihat queries/README.md).
func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (CloseShiftRow, error) {
	row := q.db.QueryRow(ctx, closeShift,
		arg.TenantID,
		arg.ID,
		arg.ClosedAt,
		arg.ExpectedCash,
		arg.CountedCash,
		arg.ClosedBy,
	)
	var i CloseShiftRow
	err := row.Scan(&i.ID, &i.Variance, &i.ClosedAt)
	return i, err
}

const getOpenShift = `-- name: GetOpenShift :one

SELECT
    id,
    outlet_id,
    cashier_id,
    opened_at,
    opening_cash
FROM shifts
WHERE tenant_id  = $1
  AND outlet_id  = $2
  AND cashier_id = $3
  AND status     = 'open'
`

type GetOpenShiftParams struct {
	TenantID  string `db:"tenant_id" json:"tenant_id"`
	OutletID  string `db:"outlet_id" json:"outlet_id"`
	CashierID string `db:"cashier_id" json:"cashier_id"`
}

type GetOpenShiftRow struct {
	ID          string             `db:"id" json:"id"`
	OutletID    string             `db:"outlet_id" json:"outlet_id"`
	CashierID   string             `db:"cashier_id" json:"cashier_id"`
	OpenedAt    pgtype.Timestamptz `db:"opened_at" json:"opened_at"`
	OpeningCash decimal.Decimal    `db:"opening_cash" json:"opening_cash"`
}

// Shift kasir. Kasir tidak bisa bertransaksi tanpa shift terbuka (FR-30).
// HOT PATH — dipanggil di awal setiap checkout untuk memperoleh shift_id.
// Memakai indeks unik parsial idx_shifts_one_open.
func (q *Queries) GetOpenShift(ctx context.Context, arg GetOpenShiftParams) (GetOpenShiftRow, error) {
	row := q.db.QueryRow(ctx, getOpenShift, arg.TenantID, arg.OutletID, arg.CashierID)
	var i GetOpenShiftRow
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.CashierID,
		&i.OpenedAt,
		&i.OpeningCash,
	)
	return i, err
}

const insertCashMovement = `-- name: InsertCashMovement :one
INSERT INTO cash_movements (id, tenant_id, shift_id, direction, amount, reason, actor_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertCashMovementParams struct {
	ID          string          `db:"id" json:"id"`
	TenantID    string          `db:"tenant_id" json:"tenant_id"`
	ShiftID     string          `db:"shift_id" json:"shift_id"`
	Direction   string          `db:"direction" json:"direction"`
	Amount      decimal.Decimal `db:"amount" json:"amount"`
	Reason      string          `db:"reason" json:"reason"`
	ActorUserID string          `db:"actor_user_id" json:"actor_user_id"`
}

func (q *Queries) InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) (string, error) {
	row := q.db.QueryRow(ctx, insertCashMovement,
		arg.ID,
		arg.TenantID,
		arg.ShiftID,
		arg.Direction,
		arg.Amount,
		arg.Reason,
		arg.ActorUserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const openShift = `-- name: OpenShift :one
INSERT INTO shifts (
    id, tenant_id, outlet_id, cashier_id, opened_at, opening_cash, status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'open'
)
RETURNING id, opened_at
`

type OpenShiftParams struct {
	ID          string             `db:"id" json:"id"`
	TenantID    string             `db:"tenant_id" json:"tenant_id"`
	OutletID    string             `db:"outlet_id" json:"outlet_id"`
	CashierID   string             `db:"cashier_id" json:"cashier_id"`
	OpenedAt    pgtype.Timestamptz `db:"opened_at" json:"opened_at"`
	OpeningCash decimal.Decimal    `db:"opening_cash" json:"opening_cash"`
}

type OpenShiftRow struct {
	ID       string             `db:"id" json:"id"`
	OpenedAt pgtype.Timestamptz `db:"opened_at" json:"opened_at"`
}

// Indeks unik parsial mencegah dua shift terbuka untuk kasir yang sama.
// Bila terjadi konflik, itu bug klien — bukan kondisi yang perlu ditangani diam-diam.
func (q *Queries) OpenShift(ctx context.Context, arg OpenShiftParams) (OpenShiftRow, error) {
	row := q.db.QueryRow(ctx, openShift,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.CashierID,
		arg.OpenedAt,
		arg.OpeningCash,
	)
	var i OpenShiftRow
	err := row.Scan(&i.ID, &i.OpenedAt)
	return i, err
}

const recordCashMovement = `-- name: RecordCashMovement :one
INSERT INTO cash_movements (
    id, tenant_id, shift_id, direction, amount, reason, actor_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_at
`

type RecordCashMovementParams struct {
	ID          string          `db:"id" json:"id"`
	TenantID    string          `db:"tenant_id" json:"tenant_id"`
	ShiftID     string          `db:"shift_id" json:"shift_id"`
	Direction   string          `db:"direction" json:"direction"`
	Amount      decimal.Decimal `db:"amount" json:"amount"`
	Reason      string          `db:"reason" json:"reason"`
	ActorUserID string          `db:"actor_user_id" json:"actor_user_id"`
}

type RecordCashMovementRow struct {
	ID        string             `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// FR-31 petty cash — mempengaruhi perhitungan expected_cash di atas.
func (q *Queries) RecordCashMovement(ctx context.Context, arg RecordCashMovementParams) (RecordCashMovementRow, error) {
	row := q.db.QueryRow(ctx, recordCashMovement,
		arg.ID,
		arg.TenantID,
		arg.ShiftID,
		arg.Direction,
		arg.Amount,
		arg.Reason,
		arg.ActorUserID,
	)
	var i RecordCashMovementRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
