// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const insertStockEvent = `-- name: InsertStockEvent :one
INSERT INTO stock_events (id, tenant_id, outlet_id, variant_id, event_type, quantity_delta, balance_after, uom, reference_id, actor_user_id, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertStockEventParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	OutletID      string          `db:"outlet_id" json:"outlet_id"`
	VariantID     string          `db:"variant_id" json:"variant_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	QuantityDelta decimal.Decimal `db:"quantity_delta" json:"quantity_delta"`
	BalanceAfter  decimal.Decimal `db:"balance_after" json:"balance_after"`
	Uom           string          `db:"uom" json:"uom"`
	ReferenceID   *string         `db:"reference_id" json:"reference_id"`
	ActorUserID   *string         `db:"actor_user_id" json:"actor_user_id"`
	Note          *string         `db:"note" json:"note"`
}

func (q *Queries) InsertStockEvent(ctx context.Context, arg InsertStockEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertStockEvent,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.VariantID,
		arg.EventType,
		arg.QuantityDelta,
		arg.BalanceAfter,
		arg.Uom,
		arg.ReferenceID,
		arg.ActorUserID,
		arg.Note,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertStockOpname = `-- name: InsertStockOpname :one
INSERT INTO stock_opname (id, tenant_id, outlet_id, status, started_by, approved_by, approved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertStockOpnameParams struct {
	ID         string             `db:"id" json:"id"`
	TenantID   string             `db:"tenant_id" json:"tenant_id"`
	OutletID   string             `db:"outlet_id" json:"outlet_id"`
	Status     string             `db:"status" json:"status"`
	StartedBy  string             `db:"started_by" json:"started_by"`
	ApprovedBy *string            `db:"approved_by" json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
}

func (q *Queries) InsertStockOpname(ctx context.Context, arg InsertStockOpnameParams) (string, error) {
	row := q.db.QueryRow(ctx, insertStockOpname,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.Status,
		arg.StartedBy,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertStockOpnameItem = `-- name: InsertStockOpnameItem :one
INSERT INTO stock_opname_items (id, tenant_id, opname_id, variant_id, system_quantity, counted_quantity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, variance
`

type InsertStockOpnameItemParams struct {
	ID              string          `db:"id" json:"id"`
	TenantID        string          `db:"tenant_id" json:"tenant_id"`
	OpnameID        string          `db:"opname_id" json:"opname_id"`
	VariantID       string          `db:"variant_id" json:"variant_id"`
	SystemQuantity  decimal.Decimal `db:"system_quantity" json:"system_quantity"`
	CountedQuantity decimal.Decimal `db:"counted_quantity" json:"counted_quantity"`
}

type InsertStockOpnameItemRow struct {
	ID       string              `db:"id" json:"id"`
	Variance decimal.NullDecimal `db:"variance" json:"variance"`
}

func (q *Queries) InsertStockOpnameItem(ctx context.Context, arg InsertStockOpnameItemParams) (InsertStockOpnameItemRow, error) {
	row := q.db.QueryRow(ctx, insertStockOpnameItem,
		arg.ID,
		arg.TenantID,
		arg.OpnameID,
		arg.VariantID,
		arg.SystemQuantity,
		arg.CountedQuantity,
	)
	var i InsertStockOpnameItemRow
	err := row.Scan(&i.ID, &i.Variance)
	return i, err
}

const listStockLevels = `-- name: ListStockLevels :many
SELECT v.id AS variant_id, p.name AS product_name, v.name AS variant_name, v.stock_quantity, v.uom, v.min_stock_alert
FROM variants v
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
WHERE v.tenant_id = $1 AND v.is_active = TRUE AND v.item_type IN ('stock', 'composite')
ORDER BY p.name ASC, v.name ASC
`

type ListStockLevelsRow struct {
	VariantID     string          `db:"variant_id" json:"variant_id"`
	ProductName   string          `db:"product_name" json:"product_name"`
	VariantName   string          `db:"variant_name" json:"variant_name"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
	Uom           string          `db:"uom" json:"uom"`
	MinStockAlert decimal.Decimal `db:"min_stock_alert" json:"min_stock_alert"`
}

func (q *Queries) ListStockLevels(ctx context.Context, tenantID string) ([]ListStockLevelsRow, error) {
	rows, err := q.db.Query(ctx, listStockLevels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockLevelsRow{}
	for rows.Next() {
		var i ListStockLevelsRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.StockQuantity,
			&i.Uom,
			&i.MinStockAlert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
