// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const adjustStock = `-- name: AdjustStock :one
UPDATE variants
SET stock_quantity = stock_quantity + $3::DECIMAL
WHERE tenant_id = $1
  AND id        = $2
  AND item_type IN ('stock', 'composite')
RETURNING stock_quantity
`

type AdjustStockParams struct {
	TenantID string          `db:"tenant_id" json:"tenant_id"`
	ID       string          `db:"id" json:"id"`
	Delta    decimal.Decimal `db:"delta" json:"delta"`
}

// Stok masuk / barang rusak / koreksi opname dari layar Stok.
//
// UPDATE tunggal ini sudah atomik dan mengambil kunci baris (alasan yang sama
// dengan DecrementStockStrict di checkout.sql). `delta` BERTANDA: positif
// menambah, negatif mengurangi, dan dihitung dalam SATUAN STOK (gram untuk
// bibit, ADR-0012).
//
// Jasa dan sewa (item_type lain) sengaja tidak punya stok, jadi 0 baris
// kembali = varian tidak ada, milik tenant lain, atau tidak berstok.
func (q *Queries) AdjustStock(ctx context.Context, arg AdjustStockParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, adjustStock, arg.TenantID, arg.ID, arg.Delta)
	var stock_quantity decimal.Decimal
	err := row.Scan(&stock_quantity)
	return stock_quantity, err
}

const getStockUom = `-- name: GetStockUom :one
SELECT COALESCE(sc.to_uom, v.uom)::VARCHAR AS stock_uom
FROM variants v
LEFT JOIN LATERAL (
    SELECT c.to_uom
    FROM uom_conversions c
    WHERE c.tenant_id = v.tenant_id AND c.variant_id = v.id AND c.from_uom = v.uom
    ORDER BY c.created_at
    LIMIT 1
) sc ON TRUE
WHERE v.tenant_id = $1 AND v.id = $2
`

type GetStockUomParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

// Satuan tempat stock_quantity dihitung: satuan STOK bila varian punya
// konversi (bibit: gram), selain itu satuan jual. Dipakai untuk mengisi
// stock_events.uom — ledger stok tidak boleh menebak satuan.
func (q *Queries) GetStockUom(ctx context.Context, arg GetStockUomParams) (string, error) {
	row := q.db.QueryRow(ctx, getStockUom, arg.TenantID, arg.ID)
	var stock_uom string
	err := row.Scan(&stock_uom)
	return stock_uom, err
}

const getVariantConversion = `-- name: GetVariantConversion :one
SELECT v.uom, COALESCE(sc.to_uom, '')::VARCHAR AS stock_uom,
       COALESCE(sc.factor, 0)::DECIMAL AS stock_factor
FROM variants v
LEFT JOIN LATERAL (
    SELECT c.to_uom, c.factor
    FROM uom_conversions c
    WHERE c.tenant_id = v.tenant_id AND c.variant_id = v.id AND c.from_uom = v.uom
    ORDER BY c.created_at
    LIMIT 1
) sc ON TRUE
WHERE v.tenant_id = $1 AND v.id = $2
`

type GetVariantConversionParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

type GetVariantConversionRow struct {
	Uom         string          `db:"uom" json:"uom"`
	StockUom    string          `db:"stock_uom" json:"stock_uom"`
	StockFactor decimal.Decimal `db:"stock_factor" json:"stock_factor"`
}

// Satuan jual + konversi ke satuan stok, TANPA filter is_active: void atau
// refund atas barang yang sudah dinonaktifkan tetap harus mengembalikan stok
// dalam satuan yang benar.
func (q *Queries) GetVariantConversion(ctx context.Context, arg GetVariantConversionParams) (GetVariantConversionRow, error) {
	row := q.db.QueryRow(ctx, getVariantConversion, arg.TenantID, arg.ID)
	var i GetVariantConversionRow
	err := row.Scan(&i.Uom, &i.StockUom, &i.StockFactor)
	return i, err
}

const insertStockEvent = `-- name: InsertStockEvent :one
INSERT INTO stock_events (id, tenant_id, outlet_id, variant_id, event_type, quantity_delta, balance_after, uom, reference_id, actor_user_id, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertStockEventParams struct {
	ID            string          `db:"id" json:"id"`
	TenantID      string          `db:"tenant_id" json:"tenant_id"`
	OutletID      string          `db:"outlet_id" json:"outlet_id"`
	VariantID     string          `db:"variant_id" json:"variant_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	QuantityDelta decimal.Decimal `db:"quantity_delta" json:"quantity_delta"`
	BalanceAfter  decimal.Decimal `db:"balance_after" json:"balance_after"`
	Uom           string          `db:"uom" json:"uom"`
	ReferenceID   *string         `db:"reference_id" json:"reference_id"`
	ActorUserID   *string         `db:"actor_user_id" json:"actor_user_id"`
	Note          *string         `db:"note" json:"note"`
}

func (q *Queries) InsertStockEvent(ctx context.Context, arg InsertStockEventParams) (string, error) {
	row := q.db.QueryRow(ctx, insertStockEvent,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.VariantID,
		arg.EventType,
		arg.QuantityDelta,
		arg.BalanceAfter,
		arg.Uom,
		arg.ReferenceID,
		arg.ActorUserID,
		arg.Note,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertStockOpname = `-- name: InsertStockOpname :one
INSERT INTO stock_opname (id, tenant_id, outlet_id, status, started_by, approved_by, approved_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertStockOpnameParams struct {
	ID         string             `db:"id" json:"id"`
	TenantID   string             `db:"tenant_id" json:"tenant_id"`
	OutletID   string             `db:"outlet_id" json:"outlet_id"`
	Status     string             `db:"status" json:"status"`
	StartedBy  string             `db:"started_by" json:"started_by"`
	ApprovedBy *string            `db:"approved_by" json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `db:"approved_at" json:"approved_at"`
}

func (q *Queries) InsertStockOpname(ctx context.Context, arg InsertStockOpnameParams) (string, error) {
	row := q.db.QueryRow(ctx, insertStockOpname,
		arg.ID,
		arg.TenantID,
		arg.OutletID,
		arg.Status,
		arg.StartedBy,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertStockOpnameItem = `-- name: InsertStockOpnameItem :one
INSERT INTO stock_opname_items (id, tenant_id, opname_id, variant_id, system_quantity, counted_quantity)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, variance
`

type InsertStockOpnameItemParams struct {
	ID              string          `db:"id" json:"id"`
	TenantID        string          `db:"tenant_id" json:"tenant_id"`
	OpnameID        string          `db:"opname_id" json:"opname_id"`
	VariantID       string          `db:"variant_id" json:"variant_id"`
	SystemQuantity  decimal.Decimal `db:"system_quantity" json:"system_quantity"`
	CountedQuantity decimal.Decimal `db:"counted_quantity" json:"counted_quantity"`
}

type InsertStockOpnameItemRow struct {
	ID       string              `db:"id" json:"id"`
	Variance decimal.NullDecimal `db:"variance" json:"variance"`
}

func (q *Queries) InsertStockOpnameItem(ctx context.Context, arg InsertStockOpnameItemParams) (InsertStockOpnameItemRow, error) {
	row := q.db.QueryRow(ctx, insertStockOpnameItem,
		arg.ID,
		arg.TenantID,
		arg.OpnameID,
		arg.VariantID,
		arg.SystemQuantity,
		arg.CountedQuantity,
	)
	var i InsertStockOpnameItemRow
	err := row.Scan(&i.ID, &i.Variance)
	return i, err
}

const listStockEvents = `-- name: ListStockEvents :many
SELECT se.id, se.created_at, se.event_type, se.quantity_delta, se.balance_after, se.uom,
       se.note, se.reference_id, se.variant_id,
       p.name AS product_name, v.name AS variant_name, u.name AS actor_name
FROM stock_events se
JOIN variants v ON v.id = se.variant_id AND v.tenant_id = se.tenant_id
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
LEFT JOIN users u ON u.id = se.actor_user_id AND u.tenant_id = se.tenant_id
WHERE se.tenant_id = $1
  AND se.outlet_id = $2
  AND se.created_at >= $3::timestamptz
  AND se.created_at < $4::timestamptz
  AND ($5::text IS NULL OR se.variant_id = $5::text)
ORDER BY se.created_at DESC
LIMIT $6::int
`

type ListStockEventsParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
	Variant  *string            `db:"variant" json:"variant"`
	Batas    int32              `db:"batas" json:"batas"`
}

type ListStockEventsRow struct {
	ID            string             `db:"id" json:"id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EventType     string             `db:"event_type" json:"event_type"`
	QuantityDelta decimal.Decimal    `db:"quantity_delta" json:"quantity_delta"`
	BalanceAfter  decimal.Decimal    `db:"balance_after" json:"balance_after"`
	Uom           string             `db:"uom" json:"uom"`
	Note          *string            `db:"note" json:"note"`
	ReferenceID   *string            `db:"reference_id" json:"reference_id"`
	VariantID     string             `db:"variant_id" json:"variant_id"`
	ProductName   string             `db:"product_name" json:"product_name"`
	VariantName   string             `db:"variant_name" json:"variant_name"`
	ActorName     *string            `db:"actor_name" json:"actor_name"`
}

// Laporan pergerakan stok (ledger append-only = KEBENARAN stok, DATA-MODEL
// §4C). Dipakai pemilik untuk melihat stok keluar bibit dalam gram.
func (q *Queries) ListStockEvents(ctx context.Context, arg ListStockEventsParams) ([]ListStockEventsRow, error) {
	rows, err := q.db.Query(ctx, listStockEvents,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
		arg.Variant,
		arg.Batas,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockEventsRow{}
	for rows.Next() {
		var i ListStockEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.EventType,
			&i.QuantityDelta,
			&i.BalanceAfter,
			&i.Uom,
			&i.Note,
			&i.ReferenceID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockLevels = `-- name: ListStockLevels :many
SELECT v.id AS variant_id, p.name AS product_name, v.name AS variant_name, v.stock_quantity,
       COALESCE(sc.to_uom, v.uom)::VARCHAR AS uom, v.min_stock_alert
FROM variants v
JOIN products p ON p.id = v.product_id AND p.tenant_id = v.tenant_id
LEFT JOIN LATERAL (
    -- Satuan STOK bila berbeda dari satuan jual (ADR-0012): bibit dijual per
    -- ml tetapi stoknya dihitung dalam gram. Konversi yang berlaku adalah
    -- yang BERANGKAT dari satuan jual varian.
    SELECT c.to_uom, c.factor
    FROM uom_conversions c
    WHERE c.tenant_id = v.tenant_id AND c.variant_id = v.id AND c.from_uom = v.uom
    ORDER BY c.created_at
    LIMIT 1
) sc ON TRUE
WHERE v.tenant_id = $1 AND v.is_active = TRUE AND v.item_type IN ('stock', 'composite')
ORDER BY p.name ASC, v.name ASC
`

type ListStockLevelsRow struct {
	VariantID     string          `db:"variant_id" json:"variant_id"`
	ProductName   string          `db:"product_name" json:"product_name"`
	VariantName   string          `db:"variant_name" json:"variant_name"`
	StockQuantity decimal.Decimal `db:"stock_quantity" json:"stock_quantity"`
	Uom           string          `db:"uom" json:"uom"`
	MinStockAlert decimal.Decimal `db:"min_stock_alert" json:"min_stock_alert"`
}

// `uom` di sini adalah satuan STOK (satuan tempat stock_quantity dihitung):
// gram untuk bibit yang dijual per ml (ADR-0012), selain itu satuan jual.
func (q *Queries) ListStockLevels(ctx context.Context, tenantID string) ([]ListStockLevelsRow, error) {
	rows, err := q.db.Query(ctx, listStockLevels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockLevelsRow{}
	for rows.Next() {
		var i ListStockLevelsRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.StockQuantity,
			&i.Uom,
			&i.MinStockAlert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockVariantStock = `-- name: LockVariantStock :one
SELECT stock_quantity
FROM variants
WHERE tenant_id = $1 AND id = $2 AND item_type IN ('stock', 'composite')
FOR UPDATE
`

type LockVariantStockParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

// Opname: baca stok tersimpan sambil mengunci barisnya. Selisih dihitung dari
// angka INI, bukan dari angka yang dikirim klien — angka klien bisa basi
// (dibaca sebelum penjualan terakhir) atau dipalsukan.
func (q *Queries) LockVariantStock(ctx context.Context, arg LockVariantStockParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, lockVariantStock, arg.TenantID, arg.ID)
	var stock_quantity decimal.Decimal
	err := row.Scan(&stock_quantity)
	return stock_quantity, err
}

const outletBelongsToTenant = `-- name: OutletBelongsToTenant :one
SELECT EXISTS (
    SELECT 1 FROM outlets WHERE tenant_id = $1 AND id = $2 AND is_active
)
`

type OutletBelongsToTenantParams struct {
	TenantID string `db:"tenant_id" json:"tenant_id"`
	ID       string `db:"id" json:"id"`
}

// Foreign key hanya menjamin outlet ADA. Tanpa ini, mutasi stok tenant A bisa
// dicatat atas outlet tenant B.
func (q *Queries) OutletBelongsToTenant(ctx context.Context, arg OutletBelongsToTenantParams) (bool, error) {
	row := q.db.QueryRow(ctx, outletBelongsToTenant, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setStock = `-- name: SetStock :one
UPDATE variants
SET stock_quantity = $3::DECIMAL
WHERE tenant_id = $1 AND id = $2 AND item_type IN ('stock', 'composite')
RETURNING stock_quantity
`

type SetStockParams struct {
	TenantID string          `db:"tenant_id" json:"tenant_id"`
	ID       string          `db:"id" json:"id"`
	Counted  decimal.Decimal `db:"counted" json:"counted"`
}

// Opname: stok DITETAPKAN sama dengan hasil timbang, bukan ditambah.
func (q *Queries) SetStock(ctx context.Context, arg SetStockParams) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, setStock, arg.TenantID, arg.ID, arg.Counted)
	var stock_quantity decimal.Decimal
	err := row.Scan(&stock_quantity)
	return stock_quantity, err
}

const sumStockEventsByType = `-- name: SumStockEventsByType :many
SELECT se.event_type, se.uom,
       SUM(se.quantity_delta)::DECIMAL AS total,
       COUNT(*)::int AS jumlah_baris
FROM stock_events se
WHERE se.tenant_id = $1
  AND se.outlet_id = $2
  AND se.created_at >= $3::timestamptz
  AND se.created_at < $4::timestamptz
  AND ($5::text IS NULL OR se.variant_id = $5::text)
GROUP BY se.event_type, se.uom
ORDER BY se.event_type, se.uom
`

type SumStockEventsByTypeParams struct {
	TenantID string             `db:"tenant_id" json:"tenant_id"`
	OutletID string             `db:"outlet_id" json:"outlet_id"`
	Dari     pgtype.Timestamptz `db:"dari" json:"dari"`
	Sampai   pgtype.Timestamptz `db:"sampai" json:"sampai"`
	Variant  *string            `db:"variant" json:"variant"`
}

type SumStockEventsByTypeRow struct {
	EventType   string          `db:"event_type" json:"event_type"`
	Uom         string          `db:"uom" json:"uom"`
	Total       decimal.Decimal `db:"total" json:"total"`
	JumlahBaris int32           `db:"jumlah_baris" json:"jumlah_baris"`
}

// Ringkasan per jenis + satuan: "terjual 412,5 g" dalam satu baris, tanpa
// menjumlahkan gram dengan pcs.
func (q *Queries) SumStockEventsByType(ctx context.Context, arg SumStockEventsByTypeParams) ([]SumStockEventsByTypeRow, error) {
	rows, err := q.db.Query(ctx, sumStockEventsByType,
		arg.TenantID,
		arg.OutletID,
		arg.Dari,
		arg.Sampai,
		arg.Variant,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumStockEventsByTypeRow{}
	for rows.Next() {
		var i SumStockEventsByTypeRow
		if err := rows.Scan(
			&i.EventType,
			&i.Uom,
			&i.Total,
			&i.JumlahBaris,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
